/**
 * NPC Spawner
 * Spawns all NPCs at their positions with patrol routes.
 * Generated by Insimul — La Louisiane
 */

import { Scene } from '@babylonjs/core/scene';
import { Vector3 } from '@babylonjs/core/Maths/math';
import { MeshBuilder } from '@babylonjs/core/Meshes/meshBuilder';
import { StandardMaterial } from '@babylonjs/core/Materials/standardMaterial';
import { Color3 } from '@babylonjs/core/Maths/math.color';
import type { ShadowGenerator } from '@babylonjs/core/Lights/Shadows/shadowGenerator';

const NPC_DATA = [
  {
    "characterId": "69c7efe254de6edea916a6cd",
    "name": "Élodie Boudreaux",
    "position": {
      "x": -346.42682837572846,
      "y": 0,
      "z": -332.286021090535
    },
    "patrolRadius": 20,
    "role": "questgiver",
    "occupation": "Farmer",
    "gender": "female"
  },
  {
    "characterId": "69c7efe254de6edea916a6cf",
    "name": "Geneviève Thibodeaux",
    "position": {
      "x": -336.78269749288813,
      "y": 0,
      "z": -314.20454556439364
    },
    "patrolRadius": 20,
    "role": "questgiver",
    "occupation": "Retired",
    "gender": "female"
  },
  {
    "characterId": "69c7efe254de6edea916a6d1",
    "name": "Jean-Baptiste Broussard",
    "position": {
      "x": -342.24879218797474,
      "y": 0,
      "z": -347.0358683231143
    },
    "patrolRadius": 20,
    "role": "civilian",
    "occupation": "Retired",
    "gender": "male"
  },
  {
    "characterId": "69c7efe254de6edea916a6d3",
    "name": "Émile Thibodeaux",
    "position": {
      "x": -345.50128695763254,
      "y": 0,
      "z": -330.30180144723397
    },
    "patrolRadius": 20,
    "role": "questgiver",
    "occupation": "Laborer",
    "gender": "male"
  },
  {
    "characterId": "69c7efe254de6edea916a6d5",
    "name": "Amélie Landry",
    "position": {
      "x": -329.21635629850584,
      "y": 0,
      "z": -329.83288184950425
    },
    "patrolRadius": 20,
    "role": "questgiver",
    "occupation": "Farmhand",
    "gender": "female"
  },
  {
    "characterId": "69c7efe254de6edea916a6d7",
    "name": "Céline LeBlanc",
    "position": {
      "x": -359.22453712334635,
      "y": 0,
      "z": -328.30528402656944
    },
    "patrolRadius": 20,
    "role": "civilian",
    "occupation": "Retired",
    "gender": "female"
  },
  {
    "characterId": "69c7efe254de6edea916a6d9",
    "name": "Louis Fontenot",
    "position": {
      "x": -335.0476415126909,
      "y": 0,
      "z": -308.39518247507385
    },
    "patrolRadius": 20,
    "role": "civilian",
    "occupation": "Retired",
    "gender": "male"
  },
  {
    "characterId": "69c7efe254de6edea916a6db",
    "name": "Antoine Hébert",
    "position": {
      "x": -364.093387587345,
      "y": 0,
      "z": -335.9331141077692
    },
    "patrolRadius": 20,
    "role": "civilian",
    "occupation": "Painter",
    "gender": "male"
  }
] as const;

export class NPCSpawner {
  async spawn(scene: Scene, shadowGen: ShadowGenerator): Promise<void> {
    const bodyMat = new StandardMaterial('npcBodyMat', scene);
    bodyMat.diffuseColor = new Color3(0.6, 0.5, 0.4);
    const headMat = new StandardMaterial('npcHeadMat', scene);
    headMat.diffuseColor = new Color3(0.85, 0.7, 0.6);

    for (const npc of NPC_DATA) {
      // Body capsule
      const body = MeshBuilder.CreateCapsule(
        `npc_body_${npc.characterId}`,
        { height: 1.6, radius: 0.25 },
        scene,
      );
      body.position = new Vector3(npc.position.x, 0.8, npc.position.z);
      body.material = bodyMat;
      shadowGen.addShadowCaster(body);

      // Head sphere
      const head = MeshBuilder.CreateSphere(
        `npc_head_${npc.characterId}`,
        { diameter: 0.35 },
        scene,
      );
      head.position = new Vector3(npc.position.x, 1.8, npc.position.z);
      head.material = headMat;
      shadowGen.addShadowCaster(head);

      // Store metadata on mesh for picking
      body.metadata = {
        characterId: npc.characterId,
        name: npc.name,
        role: npc.role,
        occupation: npc.occupation,
      };
    }
  }
}
