/**
 * World Generator
 * Creates terrain, buildings, roads, water features, and nature objects.
 * Generated by Insimul — La Louisiane
 */

import { Scene } from '@babylonjs/core/scene';
import { Vector3, Color3 } from '@babylonjs/core/Maths/math';
import { MeshBuilder } from '@babylonjs/core/Meshes/meshBuilder';
import { StandardMaterial } from '@babylonjs/core/Materials/standardMaterial';
import type { ShadowGenerator } from '@babylonjs/core/Lights/Shadows/shadowGenerator';

const TERRAIN_SIZE = 512;

const SETTLEMENTS = [
  {
    "id": "69c7efb954de6edea916a67b",
    "name": "Sainte-Évangéline",
    "position": {
      "x": -344.47201646090537,
      "y": 0,
      "z": -328.59472736625514
    },
    "radius": 41.577181208053695,
    "settlementType": "hamlet",
    "terrain": "plains",
    "population": 100,
    "elevationProfile": {
      "minElevation": 10,
      "maxElevation": 10,
      "meanElevation": 10,
      "elevationRange": 0,
      "slopeClass": "flat"
    },
    "streetSegments": [
      {
        "id": "street_ns_0",
        "name": "1st St",
        "direction": "NS",
        "waypoints": [
          {
            "x": -399.47201646090537,
            "y": 0,
            "z": -383.59472736625514
          },
          {
            "x": -399.47201646090537,
            "y": 0,
            "z": -328.59472736625514
          },
          {
            "x": -399.47201646090537,
            "y": 0,
            "z": -273.59472736625514
          }
        ],
        "width": 8
      },
      {
        "id": "street_ns_1",
        "name": "2nd St",
        "direction": "NS",
        "waypoints": [
          {
            "x": -344.47201646090537,
            "y": 0,
            "z": -383.59472736625514
          },
          {
            "x": -344.47201646090537,
            "y": 0,
            "z": -328.59472736625514
          },
          {
            "x": -344.47201646090537,
            "y": 0,
            "z": -273.59472736625514
          }
        ],
        "width": 8
      },
      {
        "id": "street_ns_2",
        "name": "3rd St",
        "direction": "NS",
        "waypoints": [
          {
            "x": -289.47201646090537,
            "y": 0,
            "z": -383.59472736625514
          },
          {
            "x": -289.47201646090537,
            "y": 0,
            "z": -328.59472736625514
          },
          {
            "x": -289.47201646090537,
            "y": 0,
            "z": -273.59472736625514
          }
        ],
        "width": 8
      },
      {
        "id": "street_ew_0",
        "name": "Main St",
        "direction": "EW",
        "waypoints": [
          {
            "x": -399.47201646090537,
            "y": 0,
            "z": -383.59472736625514
          },
          {
            "x": -344.47201646090537,
            "y": 0,
            "z": -383.59472736625514
          },
          {
            "x": -289.47201646090537,
            "y": 0,
            "z": -383.59472736625514
          }
        ],
        "width": 8
      },
      {
        "id": "street_ew_1",
        "name": "Oak Ave",
        "direction": "EW",
        "waypoints": [
          {
            "x": -399.47201646090537,
            "y": 0,
            "z": -328.59472736625514
          },
          {
            "x": -344.47201646090537,
            "y": 0,
            "z": -328.59472736625514
          },
          {
            "x": -289.47201646090537,
            "y": 0,
            "z": -328.59472736625514
          }
        ],
        "width": 8
      },
      {
        "id": "street_ew_2",
        "name": "Maple Ave",
        "direction": "EW",
        "waypoints": [
          {
            "x": -399.47201646090537,
            "y": 0,
            "z": -273.59472736625514
          },
          {
            "x": -344.47201646090537,
            "y": 0,
            "z": -273.59472736625514
          },
          {
            "x": -289.47201646090537,
            "y": 0,
            "z": -273.59472736625514
          }
        ],
        "width": 8
      }
    ],
    "lots": [
      {
        "id": "69c7efe454de6edea916a741",
        "address": "1 Rue Principale",
        "position": {
          "x": 106.83333333333333,
          "y": 0,
          "z": 110.75
        },
        "buildingType": "business",
        "buildingId": "69c7efe554de6edea916a770"
      },
      {
        "id": "69c7efe454de6edea916a742",
        "address": "2 Avenue du Chêne",
        "position": {
          "x": 106.83333333333333,
          "y": 0,
          "z": 134.25
        },
        "buildingType": "residence",
        "buildingId": "69c7efe554de6edea916a755"
      },
      {
        "id": "69c7efe454de6edea916a743",
        "address": "3 Rue Principale",
        "position": {
          "x": 122.5,
          "y": 0,
          "z": 110.75
        },
        "buildingType": "residence",
        "buildingId": "69c7efe554de6edea916a756"
      },
      {
        "id": "69c7efe454de6edea916a744",
        "address": "4 Avenue du Chêne",
        "position": {
          "x": 122.5,
          "y": 0,
          "z": 134.25
        },
        "buildingType": "residence",
        "buildingId": "69c7efe554de6edea916a757"
      },
      {
        "id": "69c7efe454de6edea916a745",
        "address": "5 Rue Principale",
        "position": {
          "x": 138.16666666666666,
          "y": 0,
          "z": 110.75
        },
        "buildingType": "business",
        "buildingId": "69c7efe554de6edea916a771"
      },
      {
        "id": "69c7efe454de6edea916a746",
        "address": "6 Avenue du Chêne",
        "position": {
          "x": 138.16666666666666,
          "y": 0,
          "z": 134.25
        },
        "buildingType": "residence",
        "buildingId": "69c7efe554de6edea916a758"
      },
      {
        "id": "69c7efe454de6edea916a747",
        "address": "7 Avenue du Chêne",
        "position": {
          "x": 106.83333333333333,
          "y": 0,
          "z": 165.75
        },
        "buildingType": "residence",
        "buildingId": "69c7efe554de6edea916a759"
      },
      {
        "id": "69c7efe454de6edea916a748",
        "address": "8 Avenue de l'Érable",
        "position": {
          "x": 106.83333333333333,
          "y": 0,
          "z": 189.25
        },
        "buildingType": "residence",
        "buildingId": "69c7efe554de6edea916a75a"
      },
      {
        "id": "69c7efe454de6edea916a749",
        "address": "9 Avenue du Chêne",
        "position": {
          "x": 122.5,
          "y": 0,
          "z": 165.75
        },
        "buildingType": "business",
        "buildingId": "69c7efe554de6edea916a772"
      },
      {
        "id": "69c7efe454de6edea916a74a",
        "address": "10 Avenue de l'Érable",
        "position": {
          "x": 122.5,
          "y": 0,
          "z": 189.25
        },
        "buildingType": "residence",
        "buildingId": "69c7efe554de6edea916a75b"
      },
      {
        "id": "69c7efe454de6edea916a74b",
        "address": "11 Avenue du Chêne",
        "position": {
          "x": 138.16666666666666,
          "y": 0,
          "z": 165.75
        },
        "buildingType": "residence",
        "buildingId": "69c7efe554de6edea916a75c"
      },
      {
        "id": "69c7efe454de6edea916a74c",
        "address": "12 Avenue de l'Érable",
        "position": {
          "x": 138.16666666666666,
          "y": 0,
          "z": 189.25
        },
        "buildingType": "residence",
        "buildingId": "69c7efe554de6edea916a75d"
      },
      {
        "id": "69c7efe454de6edea916a74d",
        "address": "13 Rue Principale",
        "position": {
          "x": 161.83333333333334,
          "y": 0,
          "z": 110.75
        },
        "buildingType": "business",
        "buildingId": "69c7efe554de6edea916a773"
      },
      {
        "id": "69c7efe454de6edea916a74e",
        "address": "14 Avenue du Chêne",
        "position": {
          "x": 161.83333333333334,
          "y": 0,
          "z": 134.25
        },
        "buildingType": "residence",
        "buildingId": "69c7efe554de6edea916a75e"
      },
      {
        "id": "69c7efe454de6edea916a74f",
        "address": "15 Rue Principale",
        "position": {
          "x": 177.5,
          "y": 0,
          "z": 110.75
        },
        "buildingType": "residence",
        "buildingId": "69c7efe554de6edea916a75f"
      },
      {
        "id": "69c7efe454de6edea916a750",
        "address": "16 Avenue du Chêne",
        "position": {
          "x": 177.5,
          "y": 0,
          "z": 134.25
        },
        "buildingType": "residence",
        "buildingId": "69c7efe554de6edea916a760"
      },
      {
        "id": "69c7efe454de6edea916a751",
        "address": "17 Rue Principale",
        "position": {
          "x": 193.16666666666666,
          "y": 0,
          "z": 110.75
        },
        "buildingType": "business",
        "buildingId": "69c7efe554de6edea916a774"
      },
      {
        "id": "69c7efe454de6edea916a752",
        "address": "18 Avenue du Chêne",
        "position": {
          "x": 193.16666666666666,
          "y": 0,
          "z": 134.25
        },
        "buildingType": "residence",
        "buildingId": "69c7efe554de6edea916a761"
      },
      {
        "id": "69c7efe454de6edea916a753",
        "address": "Avenue du Chêne Park",
        "position": {
          "x": 177.5,
          "y": 0,
          "z": 177.5
        },
        "buildingType": "park",
        "buildingId": null
      }
    ],
    "infrastructure": []
  }
] as const;

const BUILDINGS = [
  {
    "id": "bld_69c7efe554de6edea916a770",
    "settlementId": "69c7efb954de6edea916a67b",
    "position": {
      "x": 106.83333333333333,
      "y": 0,
      "z": 110.75
    },
    "rotation": 3.141592653589793,
    "spec": {
      "buildingRole": "Farm",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "rustic_wood",
      "baseColor": {
        "r": 0.8,
        "g": 0.55,
        "b": 0.35
      },
      "roofColor": {
        "r": 0.4,
        "g": 0.2,
        "b": 0.15
      },
      "windowColor": {
        "r": 0.85,
        "g": 0.8,
        "b": 0.55
      },
      "doorColor": {
        "r": 0.4,
        "g": 0.25,
        "b": 0.12
      },
      "materialType": "wood",
      "architectureStyle": "rustic"
    },
    "businessId": "69c7efe554de6edea916a770",
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69c7efe554de6edea916a771",
    "settlementId": "69c7efb954de6edea916a67b",
    "position": {
      "x": 106.83333333333333,
      "y": 0,
      "z": 134.25
    },
    "rotation": 0,
    "spec": {
      "buildingRole": "Shop",
      "floors": 2,
      "width": 10,
      "depth": 8,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "rustic_wood",
      "baseColor": {
        "r": 0.8,
        "g": 0.55,
        "b": 0.35
      },
      "roofColor": {
        "r": 0.4,
        "g": 0.2,
        "b": 0.15
      },
      "windowColor": {
        "r": 0.85,
        "g": 0.8,
        "b": 0.55
      },
      "doorColor": {
        "r": 0.4,
        "g": 0.25,
        "b": 0.12
      },
      "materialType": "wood",
      "architectureStyle": "rustic"
    },
    "businessId": "69c7efe554de6edea916a771",
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69c7efb954de6edea916a67b_2",
    "settlementId": "69c7efb954de6edea916a67b",
    "position": {
      "x": 122.5,
      "y": 0,
      "z": 110.75
    },
    "rotation": 3.141592653589793,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "rustic_wood",
      "baseColor": {
        "r": 0.8,
        "g": 0.55,
        "b": 0.35
      },
      "roofColor": {
        "r": 0.4,
        "g": 0.2,
        "b": 0.15
      },
      "windowColor": {
        "r": 0.85,
        "g": 0.8,
        "b": 0.55
      },
      "doorColor": {
        "r": 0.4,
        "g": 0.25,
        "b": 0.12
      },
      "materialType": "wood",
      "architectureStyle": "rustic"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69c7efb954de6edea916a67b_3",
    "settlementId": "69c7efb954de6edea916a67b",
    "position": {
      "x": 122.5,
      "y": 0,
      "z": 134.25
    },
    "rotation": 0,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "rustic_wood",
      "baseColor": {
        "r": 0.8,
        "g": 0.55,
        "b": 0.35
      },
      "roofColor": {
        "r": 0.4,
        "g": 0.2,
        "b": 0.15
      },
      "windowColor": {
        "r": 0.85,
        "g": 0.8,
        "b": 0.55
      },
      "doorColor": {
        "r": 0.4,
        "g": 0.25,
        "b": 0.12
      },
      "materialType": "wood",
      "architectureStyle": "rustic"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69c7efb954de6edea916a67b_4",
    "settlementId": "69c7efb954de6edea916a67b",
    "position": {
      "x": 138.16666666666666,
      "y": 0,
      "z": 110.75
    },
    "rotation": 3.141592653589793,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "rustic_wood",
      "baseColor": {
        "r": 0.8,
        "g": 0.55,
        "b": 0.35
      },
      "roofColor": {
        "r": 0.4,
        "g": 0.2,
        "b": 0.15
      },
      "windowColor": {
        "r": 0.85,
        "g": 0.8,
        "b": 0.55
      },
      "doorColor": {
        "r": 0.4,
        "g": 0.25,
        "b": 0.12
      },
      "materialType": "wood",
      "architectureStyle": "rustic"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69c7efb954de6edea916a67b_5",
    "settlementId": "69c7efb954de6edea916a67b",
    "position": {
      "x": 138.16666666666666,
      "y": 0,
      "z": 134.25
    },
    "rotation": 0,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "rustic_wood",
      "baseColor": {
        "r": 0.8,
        "g": 0.55,
        "b": 0.35
      },
      "roofColor": {
        "r": 0.4,
        "g": 0.2,
        "b": 0.15
      },
      "windowColor": {
        "r": 0.85,
        "g": 0.8,
        "b": 0.55
      },
      "doorColor": {
        "r": 0.4,
        "g": 0.25,
        "b": 0.12
      },
      "materialType": "wood",
      "architectureStyle": "rustic"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69c7efb954de6edea916a67b_6",
    "settlementId": "69c7efb954de6edea916a67b",
    "position": {
      "x": 106.83333333333333,
      "y": 0,
      "z": 165.75
    },
    "rotation": 3.141592653589793,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "rustic_wood",
      "baseColor": {
        "r": 0.8,
        "g": 0.55,
        "b": 0.35
      },
      "roofColor": {
        "r": 0.4,
        "g": 0.2,
        "b": 0.15
      },
      "windowColor": {
        "r": 0.85,
        "g": 0.8,
        "b": 0.55
      },
      "doorColor": {
        "r": 0.4,
        "g": 0.25,
        "b": 0.12
      },
      "materialType": "wood",
      "architectureStyle": "rustic"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69c7efb954de6edea916a67b_7",
    "settlementId": "69c7efb954de6edea916a67b",
    "position": {
      "x": 106.83333333333333,
      "y": 0,
      "z": 189.25
    },
    "rotation": 0,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "rustic_wood",
      "baseColor": {
        "r": 0.8,
        "g": 0.55,
        "b": 0.35
      },
      "roofColor": {
        "r": 0.4,
        "g": 0.2,
        "b": 0.15
      },
      "windowColor": {
        "r": 0.85,
        "g": 0.8,
        "b": 0.55
      },
      "doorColor": {
        "r": 0.4,
        "g": 0.25,
        "b": 0.12
      },
      "materialType": "wood",
      "architectureStyle": "rustic"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69c7efb954de6edea916a67b_8",
    "settlementId": "69c7efb954de6edea916a67b",
    "position": {
      "x": 122.5,
      "y": 0,
      "z": 165.75
    },
    "rotation": 3.141592653589793,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "rustic_wood",
      "baseColor": {
        "r": 0.8,
        "g": 0.55,
        "b": 0.35
      },
      "roofColor": {
        "r": 0.4,
        "g": 0.2,
        "b": 0.15
      },
      "windowColor": {
        "r": 0.85,
        "g": 0.8,
        "b": 0.55
      },
      "doorColor": {
        "r": 0.4,
        "g": 0.25,
        "b": 0.12
      },
      "materialType": "wood",
      "architectureStyle": "rustic"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69c7efb954de6edea916a67b_9",
    "settlementId": "69c7efb954de6edea916a67b",
    "position": {
      "x": 122.5,
      "y": 0,
      "z": 189.25
    },
    "rotation": 0,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "rustic_wood",
      "baseColor": {
        "r": 0.8,
        "g": 0.55,
        "b": 0.35
      },
      "roofColor": {
        "r": 0.4,
        "g": 0.2,
        "b": 0.15
      },
      "windowColor": {
        "r": 0.85,
        "g": 0.8,
        "b": 0.55
      },
      "doorColor": {
        "r": 0.4,
        "g": 0.25,
        "b": 0.12
      },
      "materialType": "wood",
      "architectureStyle": "rustic"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69c7efb954de6edea916a67b_10",
    "settlementId": "69c7efb954de6edea916a67b",
    "position": {
      "x": 138.16666666666666,
      "y": 0,
      "z": 165.75
    },
    "rotation": 3.141592653589793,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "rustic_wood",
      "baseColor": {
        "r": 0.8,
        "g": 0.55,
        "b": 0.35
      },
      "roofColor": {
        "r": 0.4,
        "g": 0.2,
        "b": 0.15
      },
      "windowColor": {
        "r": 0.85,
        "g": 0.8,
        "b": 0.55
      },
      "doorColor": {
        "r": 0.4,
        "g": 0.25,
        "b": 0.12
      },
      "materialType": "wood",
      "architectureStyle": "rustic"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69c7efb954de6edea916a67b_11",
    "settlementId": "69c7efb954de6edea916a67b",
    "position": {
      "x": 138.16666666666666,
      "y": 0,
      "z": 189.25
    },
    "rotation": 0,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "rustic_wood",
      "baseColor": {
        "r": 0.8,
        "g": 0.55,
        "b": 0.35
      },
      "roofColor": {
        "r": 0.4,
        "g": 0.2,
        "b": 0.15
      },
      "windowColor": {
        "r": 0.85,
        "g": 0.8,
        "b": 0.55
      },
      "doorColor": {
        "r": 0.4,
        "g": 0.25,
        "b": 0.12
      },
      "materialType": "wood",
      "architectureStyle": "rustic"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69c7efb954de6edea916a67b_12",
    "settlementId": "69c7efb954de6edea916a67b",
    "position": {
      "x": 161.83333333333334,
      "y": 0,
      "z": 110.75
    },
    "rotation": 3.141592653589793,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "rustic_wood",
      "baseColor": {
        "r": 0.8,
        "g": 0.55,
        "b": 0.35
      },
      "roofColor": {
        "r": 0.4,
        "g": 0.2,
        "b": 0.15
      },
      "windowColor": {
        "r": 0.85,
        "g": 0.8,
        "b": 0.55
      },
      "doorColor": {
        "r": 0.4,
        "g": 0.25,
        "b": 0.12
      },
      "materialType": "wood",
      "architectureStyle": "rustic"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69c7efb954de6edea916a67b_13",
    "settlementId": "69c7efb954de6edea916a67b",
    "position": {
      "x": 161.83333333333334,
      "y": 0,
      "z": 134.25
    },
    "rotation": 0,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "rustic_wood",
      "baseColor": {
        "r": 0.8,
        "g": 0.55,
        "b": 0.35
      },
      "roofColor": {
        "r": 0.4,
        "g": 0.2,
        "b": 0.15
      },
      "windowColor": {
        "r": 0.85,
        "g": 0.8,
        "b": 0.55
      },
      "doorColor": {
        "r": 0.4,
        "g": 0.25,
        "b": 0.12
      },
      "materialType": "wood",
      "architectureStyle": "rustic"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69c7efb954de6edea916a67b_14",
    "settlementId": "69c7efb954de6edea916a67b",
    "position": {
      "x": 177.5,
      "y": 0,
      "z": 110.75
    },
    "rotation": 3.141592653589793,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "rustic_wood",
      "baseColor": {
        "r": 0.8,
        "g": 0.55,
        "b": 0.35
      },
      "roofColor": {
        "r": 0.4,
        "g": 0.2,
        "b": 0.15
      },
      "windowColor": {
        "r": 0.85,
        "g": 0.8,
        "b": 0.55
      },
      "doorColor": {
        "r": 0.4,
        "g": 0.25,
        "b": 0.12
      },
      "materialType": "wood",
      "architectureStyle": "rustic"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69c7efb954de6edea916a67b_15",
    "settlementId": "69c7efb954de6edea916a67b",
    "position": {
      "x": 177.5,
      "y": 0,
      "z": 134.25
    },
    "rotation": 0,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "rustic_wood",
      "baseColor": {
        "r": 0.8,
        "g": 0.55,
        "b": 0.35
      },
      "roofColor": {
        "r": 0.4,
        "g": 0.2,
        "b": 0.15
      },
      "windowColor": {
        "r": 0.85,
        "g": 0.8,
        "b": 0.55
      },
      "doorColor": {
        "r": 0.4,
        "g": 0.25,
        "b": 0.12
      },
      "materialType": "wood",
      "architectureStyle": "rustic"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69c7efb954de6edea916a67b_16",
    "settlementId": "69c7efb954de6edea916a67b",
    "position": {
      "x": 193.16666666666666,
      "y": 0,
      "z": 110.75
    },
    "rotation": 3.141592653589793,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "rustic_wood",
      "baseColor": {
        "r": 0.8,
        "g": 0.55,
        "b": 0.35
      },
      "roofColor": {
        "r": 0.4,
        "g": 0.2,
        "b": 0.15
      },
      "windowColor": {
        "r": 0.85,
        "g": 0.8,
        "b": 0.55
      },
      "doorColor": {
        "r": 0.4,
        "g": 0.25,
        "b": 0.12
      },
      "materialType": "wood",
      "architectureStyle": "rustic"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69c7efb954de6edea916a67b_17",
    "settlementId": "69c7efb954de6edea916a67b",
    "position": {
      "x": 193.16666666666666,
      "y": 0,
      "z": 134.25
    },
    "rotation": 0,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "rustic_wood",
      "baseColor": {
        "r": 0.8,
        "g": 0.55,
        "b": 0.35
      },
      "roofColor": {
        "r": 0.4,
        "g": 0.2,
        "b": 0.15
      },
      "windowColor": {
        "r": 0.85,
        "g": 0.8,
        "b": 0.55
      },
      "doorColor": {
        "r": 0.4,
        "g": 0.25,
        "b": 0.12
      },
      "materialType": "wood",
      "architectureStyle": "rustic"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69c7efb954de6edea916a67b_18",
    "settlementId": "69c7efb954de6edea916a67b",
    "position": {
      "x": 177.5,
      "y": 0,
      "z": 177.5
    },
    "rotation": 3.141592653589793,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "rustic_wood",
      "baseColor": {
        "r": 0.8,
        "g": 0.55,
        "b": 0.35
      },
      "roofColor": {
        "r": 0.4,
        "g": 0.2,
        "b": 0.15
      },
      "windowColor": {
        "r": 0.85,
        "g": 0.8,
        "b": 0.55
      },
      "doorColor": {
        "r": 0.4,
        "g": 0.25,
        "b": 0.12
      },
      "materialType": "wood",
      "architectureStyle": "rustic"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69c7efb954de6edea916a67b_19",
    "settlementId": "69c7efb954de6edea916a67b",
    "position": {
      "x": -308.20349794238683,
      "y": 0,
      "z": -314.25870198902606
    },
    "rotation": 0,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "rustic_wood",
      "baseColor": {
        "r": 0.8,
        "g": 0.55,
        "b": 0.35
      },
      "roofColor": {
        "r": 0.4,
        "g": 0.2,
        "b": 0.15
      },
      "windowColor": {
        "r": 0.85,
        "g": 0.8,
        "b": 0.55
      },
      "doorColor": {
        "r": 0.4,
        "g": 0.25,
        "b": 0.12
      },
      "materialType": "wood",
      "architectureStyle": "rustic"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69c7efb954de6edea916a67b_20",
    "settlementId": "69c7efb954de6edea916a67b",
    "position": {
      "x": -388.2546982167353,
      "y": 0,
      "z": -294.4724537037037
    },
    "rotation": 0,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "rustic_wood",
      "baseColor": {
        "r": 0.8,
        "g": 0.55,
        "b": 0.35
      },
      "roofColor": {
        "r": 0.4,
        "g": 0.2,
        "b": 0.15
      },
      "windowColor": {
        "r": 0.85,
        "g": 0.8,
        "b": 0.55
      },
      "doorColor": {
        "r": 0.4,
        "g": 0.25,
        "b": 0.12
      },
      "materialType": "wood",
      "architectureStyle": "rustic"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69c7efb954de6edea916a67b_21",
    "settlementId": "69c7efb954de6edea916a67b",
    "position": {
      "x": -368.3593964334705,
      "y": 0,
      "z": -292.27056755829904
    },
    "rotation": 0,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "rustic_wood",
      "baseColor": {
        "r": 0.8,
        "g": 0.55,
        "b": 0.35
      },
      "roofColor": {
        "r": 0.4,
        "g": 0.2,
        "b": 0.15
      },
      "windowColor": {
        "r": 0.85,
        "g": 0.8,
        "b": 0.55
      },
      "doorColor": {
        "r": 0.4,
        "g": 0.25,
        "b": 0.12
      },
      "materialType": "wood",
      "architectureStyle": "rustic"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69c7efb954de6edea916a67b_22",
    "settlementId": "69c7efb954de6edea916a67b",
    "position": {
      "x": -348.61635802469135,
      "y": 0,
      "z": -294.27032750342937
    },
    "rotation": 0,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "rustic_wood",
      "baseColor": {
        "r": 0.8,
        "g": 0.55,
        "b": 0.35
      },
      "roofColor": {
        "r": 0.4,
        "g": 0.2,
        "b": 0.15
      },
      "windowColor": {
        "r": 0.85,
        "g": 0.8,
        "b": 0.55
      },
      "doorColor": {
        "r": 0.4,
        "g": 0.25,
        "b": 0.12
      },
      "materialType": "wood",
      "architectureStyle": "rustic"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69c7efb954de6edea916a67b_23",
    "settlementId": "69c7efb954de6edea916a67b",
    "position": {
      "x": -328.38360768175585,
      "y": 0,
      "z": -293.4593878600823
    },
    "rotation": 0,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "rustic_wood",
      "baseColor": {
        "r": 0.8,
        "g": 0.55,
        "b": 0.35
      },
      "roofColor": {
        "r": 0.4,
        "g": 0.2,
        "b": 0.15
      },
      "windowColor": {
        "r": 0.85,
        "g": 0.8,
        "b": 0.55
      },
      "doorColor": {
        "r": 0.4,
        "g": 0.25,
        "b": 0.12
      },
      "materialType": "wood",
      "architectureStyle": "rustic"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69c7efb954de6edea916a67b_24",
    "settlementId": "69c7efb954de6edea916a67b",
    "position": {
      "x": -309.83398491083676,
      "y": 0,
      "z": -291.41799554183814
    },
    "rotation": 0,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "rustic_wood",
      "baseColor": {
        "r": 0.8,
        "g": 0.55,
        "b": 0.35
      },
      "roofColor": {
        "r": 0.4,
        "g": 0.2,
        "b": 0.15
      },
      "windowColor": {
        "r": 0.85,
        "g": 0.8,
        "b": 0.55
      },
      "doorColor": {
        "r": 0.4,
        "g": 0.25,
        "b": 0.12
      },
      "materialType": "wood",
      "architectureStyle": "rustic"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  }
] as const;

const ROADS = [
  {
    "fromId": "node_0_0",
    "toId": "node_2_0",
    "waypoints": [
      {
        "x": -399.47201646090537,
        "y": 0,
        "z": -383.59472736625514
      },
      {
        "x": -399.47201646090537,
        "y": 0,
        "z": -328.59472736625514
      },
      {
        "x": -399.47201646090537,
        "y": 0,
        "z": -273.59472736625514
      }
    ],
    "width": 8,
    "materialKey": null
  },
  {
    "fromId": "node_0_1",
    "toId": "node_2_1",
    "waypoints": [
      {
        "x": -344.47201646090537,
        "y": 0,
        "z": -383.59472736625514
      },
      {
        "x": -344.47201646090537,
        "y": 0,
        "z": -328.59472736625514
      },
      {
        "x": -344.47201646090537,
        "y": 0,
        "z": -273.59472736625514
      }
    ],
    "width": 8,
    "materialKey": null
  },
  {
    "fromId": "node_0_2",
    "toId": "node_2_2",
    "waypoints": [
      {
        "x": -289.47201646090537,
        "y": 0,
        "z": -383.59472736625514
      },
      {
        "x": -289.47201646090537,
        "y": 0,
        "z": -328.59472736625514
      },
      {
        "x": -289.47201646090537,
        "y": 0,
        "z": -273.59472736625514
      }
    ],
    "width": 8,
    "materialKey": null
  },
  {
    "fromId": "node_0_0",
    "toId": "node_0_2",
    "waypoints": [
      {
        "x": -399.47201646090537,
        "y": 0,
        "z": -383.59472736625514
      },
      {
        "x": -344.47201646090537,
        "y": 0,
        "z": -383.59472736625514
      },
      {
        "x": -289.47201646090537,
        "y": 0,
        "z": -383.59472736625514
      }
    ],
    "width": 8,
    "materialKey": null
  },
  {
    "fromId": "node_1_0",
    "toId": "node_1_2",
    "waypoints": [
      {
        "x": -399.47201646090537,
        "y": 0,
        "z": -328.59472736625514
      },
      {
        "x": -344.47201646090537,
        "y": 0,
        "z": -328.59472736625514
      },
      {
        "x": -289.47201646090537,
        "y": 0,
        "z": -328.59472736625514
      }
    ],
    "width": 8,
    "materialKey": null
  },
  {
    "fromId": "node_2_0",
    "toId": "node_2_2",
    "waypoints": [
      {
        "x": -399.47201646090537,
        "y": 0,
        "z": -273.59472736625514
      },
      {
        "x": -344.47201646090537,
        "y": 0,
        "z": -273.59472736625514
      },
      {
        "x": -289.47201646090537,
        "y": 0,
        "z": -273.59472736625514
      }
    ],
    "width": 8,
    "materialKey": null
  }
] as const;

const WATER_FEATURES = [] as const;

const NATURE_OBJECTS = [] as const;

export class WorldGenerator {
  async generate(scene: Scene, shadowGen: ShadowGenerator): Promise<void> {
    this.createTerrain(scene);
    this.createBuildings(scene, shadowGen);
    this.createStreetNetworks(scene);
    this.createRoads(scene);
    this.createWaterFeatures(scene);
    this.createNatureObjects(scene, shadowGen);
  }

  private createTerrain(scene: Scene): void {
    const ground = MeshBuilder.CreateGround(
      'terrain',
      { width: TERRAIN_SIZE, height: TERRAIN_SIZE, subdivisions: 64 },
      scene,
    );
    const mat = new StandardMaterial('terrainMat', scene);
    mat.diffuseColor = new Color3(0.35, 0.55, 0.25);
    mat.specularColor = new Color3(0.1, 0.1, 0.1);
    ground.material = mat;
    ground.receiveShadows = true;
  }

  private createBuildings(scene: Scene, shadowGen: ShadowGenerator): void {
    for (const b of BUILDINGS) {
      const width = b.spec.width;
      const depth = b.spec.depth;
      const height = b.spec.floors * 3;

      const mesh = MeshBuilder.CreateBox(
        `building_${b.id}`,
        { width, depth, height },
        scene,
      );
      mesh.position = new Vector3(b.position.x, height / 2, b.position.z);
      mesh.rotation.y = b.rotation;

      const mat = new StandardMaterial(`buildingMat_${b.id}`, scene);
      const base = b.style?.baseColor;
      if (base) {
        mat.diffuseColor = new Color3(base.r, base.g, base.b);
      } else {
        mat.diffuseColor = new Color3(0.7, 0.65, 0.6);
      }
      mesh.material = mat;
      mesh.receiveShadows = true;
      shadowGen.addShadowCaster(mesh);

      // Roof
      if (b.spec.floors > 0) {
        const roof = MeshBuilder.CreateBox(
          `roof_${b.id}`,
          { width: width + 0.2, depth: depth + 0.2, height: 0.3 },
          scene,
        );
        roof.position = new Vector3(b.position.x, height + 0.15, b.position.z);
        roof.rotation.y = b.rotation;
        const roofMat = new StandardMaterial(`roofMat_${b.id}`, scene);
        const rc = b.style?.roofColor;
        roofMat.diffuseColor = rc
          ? new Color3(rc.r, rc.g, rc.b)
          : new Color3(0.5, 0.3, 0.2);
        roof.material = roofMat;
        shadowGen.addShadowCaster(roof);
      }
    }
  }

  private createStreetNetworks(scene: Scene): void {
    const streetMat = new StandardMaterial('streetMat', scene);
    streetMat.diffuseColor = new Color3(0.3, 0.3, 0.35);
    streetMat.specularColor = new Color3(0.05, 0.05, 0.05);

    for (const settlement of SETTLEMENTS) {
      for (const segment of settlement.streetSegments) {
        if (segment.waypoints.length < 2) continue;

        const points = segment.waypoints.map(
          (wp: any) => new Vector3(wp.x, 0.02, wp.z),
        );

        const path = MeshBuilder.CreateTube(
          `street_${segment.id}`,
          { path: points, radius: segment.width / 2, tessellation: 8, cap: 2 },
          scene,
        );
        path.material = streetMat;
        path.receiveShadows = true;
      }
    }
  }

  private createRoads(scene: Scene): void {
    const roadMat = new StandardMaterial('roadMat', scene);
    roadMat.diffuseColor = new Color3(0.4, 0.35, 0.3);
    roadMat.specularColor = new Color3(0.05, 0.05, 0.05);

    for (let i = 0; i < ROADS.length; i++) {
      const road = ROADS[i];
      if (road.waypoints.length < 2) continue;

      const points = road.waypoints.map(
        (wp: any) => new Vector3(wp.x, 0.01, wp.z),
      );

      const mesh = MeshBuilder.CreateTube(
        `road_${i}`,
        { path: points, radius: road.width / 2, tessellation: 8, cap: 2 },
        scene,
      );
      mesh.material = roadMat;
      mesh.receiveShadows = true;
    }
  }

  private createWaterFeatures(scene: Scene): void {
    for (const water of WATER_FEATURES) {
      const waterMat = new StandardMaterial(`waterMat_${water.id}`, scene);
      if (water.color) {
        waterMat.diffuseColor = new Color3(water.color.r, water.color.g, water.color.b);
      } else {
        waterMat.diffuseColor = new Color3(0.1, 0.4, 0.7);
      }
      waterMat.alpha = 1 - water.transparency;
      waterMat.specularColor = new Color3(0.3, 0.3, 0.4);

      if (water.shorelinePoints.length >= 3) {
        // Create water surface from shoreline polygon
        const shape = water.shorelinePoints.map(
          (p: any) => new Vector3(p.x, water.waterLevel, p.z),
        );
        const mesh = MeshBuilder.CreatePolygon(
          `water_${water.id}`,
          { shape, depth: 0.1 },
          scene,
        );
        mesh.position.y = water.waterLevel;
        mesh.material = waterMat;
      } else {
        // Fallback: create water surface from bounds
        const w = water.bounds.maxX - water.bounds.minX;
        const d = water.bounds.maxZ - water.bounds.minZ;
        const mesh = MeshBuilder.CreateGround(
          `water_${water.id}`,
          { width: w || water.width, height: d || water.width },
          scene,
        );
        mesh.position = new Vector3(
          water.position.x,
          water.waterLevel,
          water.position.z,
        );
        mesh.material = waterMat;
      }
    }
  }

  private createNatureObjects(scene: Scene, shadowGen: ShadowGenerator): void {
    // Group by type for shared materials
    const treeMat = new StandardMaterial('treeMat', scene);
    treeMat.diffuseColor = new Color3(0.2, 0.5, 0.15);
    const trunkMat = new StandardMaterial('trunkMat', scene);
    trunkMat.diffuseColor = new Color3(0.4, 0.25, 0.1);
    const rockMat = new StandardMaterial('rockMat', scene);
    rockMat.diffuseColor = new Color3(0.5, 0.5, 0.5);
    const bushMat = new StandardMaterial('bushMat', scene);
    bushMat.diffuseColor = new Color3(0.15, 0.4, 0.1);

    for (let i = 0; i < NATURE_OBJECTS.length; i++) {
      const obj = NATURE_OBJECTS[i];
      const pos = new Vector3(obj.position.x, obj.position.y, obj.position.z);

      switch (obj.type) {
        case 'tree': {
          const trunk = MeshBuilder.CreateCylinder(
            `trunk_${i}`,
            { diameter: 0.3 * obj.scale.x, height: 2 * obj.scale.y },
            scene,
          );
          trunk.position = pos.clone();
          trunk.position.y += obj.scale.y;
          trunk.material = trunkMat;
          shadowGen.addShadowCaster(trunk);

          const canopy = MeshBuilder.CreateSphere(
            `canopy_${i}`,
            { diameter: 2 * obj.scale.x },
            scene,
          );
          canopy.position = pos.clone();
          canopy.position.y += 2 * obj.scale.y + obj.scale.x * 0.5;
          canopy.material = treeMat;
          shadowGen.addShadowCaster(canopy);
          break;
        }
        case 'rock': {
          const rock = MeshBuilder.CreateSphere(
            `rock_${i}`,
            { diameter: obj.scale.x },
            scene,
          );
          rock.position = pos;
          rock.scaling = new Vector3(obj.scale.x, obj.scale.y * 0.6, obj.scale.z);
          rock.material = rockMat;
          shadowGen.addShadowCaster(rock);
          break;
        }
        case 'bush': {
          const bush = MeshBuilder.CreateSphere(
            `bush_${i}`,
            { diameter: obj.scale.x },
            scene,
          );
          bush.position = pos;
          bush.position.y += obj.scale.y * 0.3;
          bush.material = bushMat;
          shadowGen.addShadowCaster(bush);
          break;
        }
      }
    }
  }
}
