/**
 * Assessment Writing Task Handler
 *
 * Handles the writing section of assessment encounters.
 * The player responds to LLM-generated writing prompts via text input.
 * Scoring is done server-side by the LLM on three dimensions:
 *   - Task Completion (0-5)
 *   - Vocabulary (0-5)
 *   - Grammar (0-5)
 * Total: /15 points.
 *
 * Stores all player text verbatim for researcher review.
 */

// ─── Types ───────────────────────────────────────────────────────────────────

export interface WritingTaskConfig {
  /** Target language the player is writing in */
  targetLanguage: string;
  /** Writing prompts (generated by LLM at assessment start) */
  writingPrompts: string[];
}

export interface WritingSubmission {
  /** Prompt index → player's verbatim text */
  responses: Record<string, string>;
  submittedAt: number;
}

export interface WritingDimensionScore {
  score: number;
  maxScore: number;
  rationale: string;
}

export interface WritingScoringResult {
  totalScore: number;
  maxScore: number;
  dimensionScores: {
    task_completion: WritingDimensionScore;
    vocabulary: WritingDimensionScore;
    grammar: WritingDimensionScore;
  };
  overallRationale: string;
}

export interface WritingPhaseResult {
  scoringResult: WritingScoringResult | null;
  submission: WritingSubmission | null;
  totalScore: number;
  totalMaxPoints: number;
  startedAt: number;
  completedAt: number;
}

export type WritingTaskStatus = 'idle' | 'active' | 'submitted' | 'scored' | 'completed';

export interface WritingTaskCallbacks {
  onStatusChange?: (status: WritingTaskStatus) => void;
  onComplete?: (result: WritingPhaseResult) => void;
}

// ─── Controller ──────────────────────────────────────────────────────────────

export class AssessmentWritingTask {
  private _status: WritingTaskStatus = 'idle';
  private _submission: WritingSubmission | null = null;
  private _scoringResult: WritingScoringResult | null = null;
  private _startedAt = 0;

  private readonly _config: WritingTaskConfig;
  private readonly _callbacks: WritingTaskCallbacks;

  constructor(config: WritingTaskConfig, callbacks: WritingTaskCallbacks = {}) {
    this._config = config;
    this._callbacks = callbacks;
  }

  // ─── Public API ──────────────────────────────────────────────────────────

  get status(): WritingTaskStatus { return this._status; }
  get submission(): WritingSubmission | null { return this._submission; }
  get scoringResult(): WritingScoringResult | null { return this._scoringResult; }
  get writingPrompts(): ReadonlyArray<string> { return this._config.writingPrompts; }
  get totalMaxPoints(): number { return 15; }

  /** Start the writing phase. */
  start(): void {
    if (this._status !== 'idle') {
      throw new Error(`Cannot start: status is ${this._status}`);
    }
    this._startedAt = Date.now();
    this._setStatus('active');
  }

  /** Submit all writing responses. Returns the answers keyed by prompt index (p1, p2, etc.) */
  submit(responses: Record<string, string>): Record<string, string> {
    if (this._status !== 'active') {
      throw new Error(`Cannot submit: status is ${this._status}`);
    }

    this._submission = {
      responses,
      submittedAt: Date.now(),
    };
    this._setStatus('submitted');

    return responses;
  }

  /** Record the scoring result (called after server-side LLM scoring). */
  recordScore(result: WritingScoringResult): void {
    this._scoringResult = result;
    this._setStatus('scored');
    this._setStatus('completed');

    const phaseResult = this.getResult();
    this._callbacks.onComplete?.(phaseResult);
  }

  /** Get the final writing phase result. */
  getResult(): WritingPhaseResult {
    return {
      scoringResult: this._scoringResult,
      submission: this._submission,
      totalScore: this._scoringResult?.totalScore ?? 0,
      totalMaxPoints: this.totalMaxPoints,
      startedAt: this._startedAt,
      completedAt: this._status === 'completed' ? Date.now() : 0,
    };
  }

  // ─── Internal ──────────────────────────────────────────────────────────

  private _setStatus(status: WritingTaskStatus): void {
    this._status = status;
    this._callbacks.onStatusChange?.(status);
  }
}
