/**
 * NPC Spawner
 * Spawns all NPCs at their positions with patrol routes.
 * Generated by Insimul — La Louisiane
 */

import { Scene } from '@babylonjs/core/scene';
import { Vector3 } from '@babylonjs/core/Maths/math';
import { MeshBuilder } from '@babylonjs/core/Meshes/meshBuilder';
import { StandardMaterial } from '@babylonjs/core/Materials/standardMaterial';
import { Color3 } from '@babylonjs/core/Maths/math.color';
import type { ShadowGenerator } from '@babylonjs/core/Lights/Shadows/shadowGenerator';

const NPC_DATA = [] as const;

export class NPCSpawner {
  async spawn(scene: Scene, shadowGen: ShadowGenerator): Promise<void> {
    const bodyMat = new StandardMaterial('npcBodyMat', scene);
    bodyMat.diffuseColor = new Color3(0.6, 0.5, 0.4);
    const headMat = new StandardMaterial('npcHeadMat', scene);
    headMat.diffuseColor = new Color3(0.85, 0.7, 0.6);

    for (const npc of NPC_DATA) {
      // Body capsule
      const body = MeshBuilder.CreateCapsule(
        `npc_body_${npc.characterId}`,
        { height: 1.6, radius: 0.25 },
        scene,
      );
      body.position = new Vector3(npc.position.x, 0.8, npc.position.z);
      body.material = bodyMat;
      shadowGen.addShadowCaster(body);

      // Head sphere
      const head = MeshBuilder.CreateSphere(
        `npc_head_${npc.characterId}`,
        { diameter: 0.35 },
        scene,
      );
      head.position = new Vector3(npc.position.x, 1.8, npc.position.z);
      head.material = headMat;
      shadowGen.addShadowCaster(head);

      // Store metadata on mesh for picking
      body.metadata = {
        characterId: npc.characterId,
        name: npc.name,
        role: npc.role,
        occupation: npc.occupation,
      };
    }
  }
}
