/**
 * Scene Builder
 * Constructs the full 3D scene from world data.
 * Generated by Insimul — La Louisiane
 */

import { Scene } from '@babylonjs/core/scene';
import { Vector3, Color3, Color4 } from '@babylonjs/core/Maths/math';
import { HemisphericLight } from '@babylonjs/core/Lights/hemisphericLight';
import { DirectionalLight } from '@babylonjs/core/Lights/directionalLight';
import { ShadowGenerator } from '@babylonjs/core/Lights/Shadows/shadowGenerator';
import '@babylonjs/core/Lights/Shadows/shadowGeneratorSceneComponent';
import { WorldGenerator } from './world-generator';
import { NPCSpawner } from './npc-spawner';

export async function buildScene(scene: Scene): Promise<void> {
  // Sky / clear color
  scene.clearColor = new Color4(1, 1, 1, 1);

  // Ambient light
  const ambient = new HemisphericLight('ambient', new Vector3(0, 1, 0), scene);
  ambient.diffuse = new Color3(1, 1, 1);
  ambient.intensity = 0.6;
  ambient.groundColor = new Color3(0.2, 0.2, 0.25);

  // Directional light (sun)
  const sun = new DirectionalLight(
    'sun',
    new Vector3(-1, -2, -1),
    scene,
  );
  sun.intensity = 0.8;
  sun.position = new Vector3(0, 50, 0);

  // Shadow generator
  const shadowGen = new ShadowGenerator(2048, sun);
  shadowGen.useBlurExponentialShadowMap = true;
  shadowGen.blurKernel = 32;


  // Generate world geometry
  const worldGenerator = new WorldGenerator();
  await worldGenerator.generate(scene, shadowGen);

  // Spawn NPCs
  const npcSpawner = new NPCSpawner();
  await npcSpawner.spawn(scene, shadowGen);
}
