/**
 * World Generator
 * Creates terrain, buildings, roads, water features, and nature objects.
 * Generated by Insimul — La Louisiane
 */

import { Scene } from '@babylonjs/core/scene';
import { Vector3, Color3 } from '@babylonjs/core/Maths/math';
import { MeshBuilder } from '@babylonjs/core/Meshes/meshBuilder';
import { StandardMaterial } from '@babylonjs/core/Materials/standardMaterial';
import type { ShadowGenerator } from '@babylonjs/core/Lights/Shadows/shadowGenerator';

const TERRAIN_SIZE = 512;

const SETTLEMENTS = [
  {
    "id": "69bfe08a2f34e6ad23a78dc4",
    "name": "Pont Guidry",
    "position": {
      "x": 68.11303155006857,
      "y": 0,
      "z": 195.0500342935528
    },
    "radius": 44.261744966442954,
    "settlementType": "village",
    "terrain": "plains",
    "population": 120,
    "elevationProfile": null,
    "streetSegments": [
      {
        "id": "street_ns_0",
        "name": "1st St",
        "direction": "NS",
        "waypoints": [
          {
            "x": -6.88696844993143,
            "y": 0,
            "z": 120.05003429355281
          },
          {
            "x": -6.88696844993143,
            "y": 0,
            "z": 170.0500342935528
          },
          {
            "x": -6.88696844993143,
            "y": 0,
            "z": 220.0500342935528
          },
          {
            "x": -6.88696844993143,
            "y": 0,
            "z": 270.0500342935528
          }
        ],
        "width": 10
      },
      {
        "id": "street_ns_1",
        "name": "2nd St",
        "direction": "NS",
        "waypoints": [
          {
            "x": 43.11303155006857,
            "y": 0,
            "z": 120.05003429355281
          },
          {
            "x": 43.11303155006857,
            "y": 0,
            "z": 170.0500342935528
          },
          {
            "x": 43.11303155006857,
            "y": 0,
            "z": 220.0500342935528
          },
          {
            "x": 43.11303155006857,
            "y": 0,
            "z": 270.0500342935528
          }
        ],
        "width": 10
      },
      {
        "id": "street_ns_2",
        "name": "3rd St",
        "direction": "NS",
        "waypoints": [
          {
            "x": 93.11303155006857,
            "y": 0,
            "z": 120.05003429355281
          },
          {
            "x": 93.11303155006857,
            "y": 0,
            "z": 170.0500342935528
          },
          {
            "x": 93.11303155006857,
            "y": 0,
            "z": 220.0500342935528
          },
          {
            "x": 93.11303155006857,
            "y": 0,
            "z": 270.0500342935528
          }
        ],
        "width": 10
      },
      {
        "id": "street_ns_3",
        "name": "4th St",
        "direction": "NS",
        "waypoints": [
          {
            "x": 143.11303155006857,
            "y": 0,
            "z": 120.05003429355281
          },
          {
            "x": 143.11303155006857,
            "y": 0,
            "z": 170.0500342935528
          },
          {
            "x": 143.11303155006857,
            "y": 0,
            "z": 220.0500342935528
          },
          {
            "x": 143.11303155006857,
            "y": 0,
            "z": 270.0500342935528
          }
        ],
        "width": 10
      },
      {
        "id": "street_ew_0",
        "name": "Main St",
        "direction": "EW",
        "waypoints": [
          {
            "x": -6.88696844993143,
            "y": 0,
            "z": 120.05003429355281
          },
          {
            "x": 43.11303155006857,
            "y": 0,
            "z": 120.05003429355281
          },
          {
            "x": 93.11303155006857,
            "y": 0,
            "z": 120.05003429355281
          },
          {
            "x": 143.11303155006857,
            "y": 0,
            "z": 120.05003429355281
          }
        ],
        "width": 10
      },
      {
        "id": "street_ew_1",
        "name": "Oak Ave",
        "direction": "EW",
        "waypoints": [
          {
            "x": -6.88696844993143,
            "y": 0,
            "z": 170.0500342935528
          },
          {
            "x": 43.11303155006857,
            "y": 0,
            "z": 170.0500342935528
          },
          {
            "x": 93.11303155006857,
            "y": 0,
            "z": 170.0500342935528
          },
          {
            "x": 143.11303155006857,
            "y": 0,
            "z": 170.0500342935528
          }
        ],
        "width": 10
      },
      {
        "id": "street_ew_2",
        "name": "Maple Ave",
        "direction": "EW",
        "waypoints": [
          {
            "x": -6.88696844993143,
            "y": 0,
            "z": 220.0500342935528
          },
          {
            "x": 43.11303155006857,
            "y": 0,
            "z": 220.0500342935528
          },
          {
            "x": 93.11303155006857,
            "y": 0,
            "z": 220.0500342935528
          },
          {
            "x": 143.11303155006857,
            "y": 0,
            "z": 220.0500342935528
          }
        ],
        "width": 10
      },
      {
        "id": "street_ew_3",
        "name": "Cedar Ave",
        "direction": "EW",
        "waypoints": [
          {
            "x": -6.88696844993143,
            "y": 0,
            "z": 270.0500342935528
          },
          {
            "x": 43.11303155006857,
            "y": 0,
            "z": 270.0500342935528
          },
          {
            "x": 93.11303155006857,
            "y": 0,
            "z": 270.0500342935528
          },
          {
            "x": 143.11303155006857,
            "y": 0,
            "z": 270.0500342935528
          }
        ],
        "width": 10
      }
    ],
    "lots": [
      {
        "id": "69bfe08d2f34e6ad23a78e1f",
        "address": "1 Chemin de la Poste",
        "position": {
          "x": 186.66666666666666,
          "y": 0,
          "z": 190
        },
        "buildingType": "business",
        "buildingId": "69bfe08e2f34e6ad23a78e87"
      },
      {
        "id": "69bfe08d2f34e6ad23a78e20",
        "address": "2 Chemin des Marronniers",
        "position": {
          "x": 186.66666666666666,
          "y": 0,
          "z": 210
        },
        "buildingType": "residence",
        "buildingId": "69bfe08d2f34e6ad23a78e48"
      },
      {
        "id": "69bfe08d2f34e6ad23a78e21",
        "address": "3 Chemin de la Poste",
        "position": {
          "x": 200,
          "y": 0,
          "z": 190
        },
        "buildingType": "residence",
        "buildingId": "69bfe08d2f34e6ad23a78e49"
      },
      {
        "id": "69bfe08d2f34e6ad23a78e22",
        "address": "4 Chemin des Marronniers",
        "position": {
          "x": 200,
          "y": 0,
          "z": 210
        },
        "buildingType": "residence",
        "buildingId": "69bfe08d2f34e6ad23a78e4a"
      },
      {
        "id": "69bfe08d2f34e6ad23a78e23",
        "address": "5 Chemin de la Poste",
        "position": {
          "x": 213.33333333333334,
          "y": 0,
          "z": 190
        },
        "buildingType": "business",
        "buildingId": "69bfe08e2f34e6ad23a78e88"
      },
      {
        "id": "69bfe08d2f34e6ad23a78e24",
        "address": "6 Chemin des Marronniers",
        "position": {
          "x": 213.33333333333334,
          "y": 0,
          "z": 210
        },
        "buildingType": "residence",
        "buildingId": "69bfe08d2f34e6ad23a78e4b"
      },
      {
        "id": "69bfe08d2f34e6ad23a78e25",
        "address": "7 Chemin des Marronniers",
        "position": {
          "x": 186.66666666666666,
          "y": 0,
          "z": 240
        },
        "buildingType": "residence",
        "buildingId": "69bfe08d2f34e6ad23a78e4c"
      },
      {
        "id": "69bfe08d2f34e6ad23a78e26",
        "address": "8 Impasse de Toulouse",
        "position": {
          "x": 186.66666666666666,
          "y": 0,
          "z": 260
        },
        "buildingType": "residence",
        "buildingId": "69bfe08d2f34e6ad23a78e4d"
      },
      {
        "id": "69bfe08d2f34e6ad23a78e27",
        "address": "9 Chemin des Marronniers",
        "position": {
          "x": 200,
          "y": 0,
          "z": 240
        },
        "buildingType": "business",
        "buildingId": "69bfe08e2f34e6ad23a78e89"
      },
      {
        "id": "69bfe08d2f34e6ad23a78e28",
        "address": "10 Impasse de Toulouse",
        "position": {
          "x": 200,
          "y": 0,
          "z": 260
        },
        "buildingType": "residence",
        "buildingId": "69bfe08d2f34e6ad23a78e4e"
      },
      {
        "id": "69bfe08d2f34e6ad23a78e29",
        "address": "11 Chemin des Marronniers",
        "position": {
          "x": 213.33333333333334,
          "y": 0,
          "z": 240
        },
        "buildingType": "residence",
        "buildingId": "69bfe08d2f34e6ad23a78e4f"
      },
      {
        "id": "69bfe08d2f34e6ad23a78e2a",
        "address": "12 Impasse de Toulouse",
        "position": {
          "x": 213.33333333333334,
          "y": 0,
          "z": 260
        },
        "buildingType": "residence",
        "buildingId": "69bfe08d2f34e6ad23a78e50"
      },
      {
        "id": "69bfe08d2f34e6ad23a78e2b",
        "address": "13 Impasse de Toulouse",
        "position": {
          "x": 186.66666666666666,
          "y": 0,
          "z": 290
        },
        "buildingType": "business",
        "buildingId": "69bfe08e2f34e6ad23a78e8a"
      },
      {
        "id": "69bfe08d2f34e6ad23a78e2c",
        "address": "14 Quai Neuf",
        "position": {
          "x": 186.66666666666666,
          "y": 0,
          "z": 310
        },
        "buildingType": "residence",
        "buildingId": "69bfe08d2f34e6ad23a78e51"
      },
      {
        "id": "69bfe08d2f34e6ad23a78e2d",
        "address": "15 Impasse de Toulouse",
        "position": {
          "x": 200,
          "y": 0,
          "z": 290
        },
        "buildingType": "residence",
        "buildingId": "69bfe08d2f34e6ad23a78e52"
      },
      {
        "id": "69bfe08d2f34e6ad23a78e2e",
        "address": "16 Quai Neuf",
        "position": {
          "x": 200,
          "y": 0,
          "z": 310
        },
        "buildingType": "residence",
        "buildingId": "69bfe08d2f34e6ad23a78e53"
      },
      {
        "id": "69bfe08d2f34e6ad23a78e2f",
        "address": "17 Impasse de Toulouse",
        "position": {
          "x": 213.33333333333334,
          "y": 0,
          "z": 290
        },
        "buildingType": "business",
        "buildingId": "69bfe08e2f34e6ad23a78e8b"
      },
      {
        "id": "69bfe08d2f34e6ad23a78e30",
        "address": "18 Quai Neuf",
        "position": {
          "x": 213.33333333333334,
          "y": 0,
          "z": 310
        },
        "buildingType": "residence",
        "buildingId": "69bfe08d2f34e6ad23a78e54"
      },
      {
        "id": "69bfe08d2f34e6ad23a78e31",
        "address": "19 Chemin de la Poste",
        "position": {
          "x": 236.66666666666666,
          "y": 0,
          "z": 190
        },
        "buildingType": "residence",
        "buildingId": "69bfe08d2f34e6ad23a78e55"
      },
      {
        "id": "69bfe08d2f34e6ad23a78e32",
        "address": "20 Chemin des Marronniers",
        "position": {
          "x": 236.66666666666666,
          "y": 0,
          "z": 210
        },
        "buildingType": "residence",
        "buildingId": "69bfe08d2f34e6ad23a78e56"
      },
      {
        "id": "69bfe08d2f34e6ad23a78e33",
        "address": "21 Chemin de la Poste",
        "position": {
          "x": 250,
          "y": 0,
          "z": 190
        },
        "buildingType": "business",
        "buildingId": "69bfe08e2f34e6ad23a78e8c"
      },
      {
        "id": "69bfe08d2f34e6ad23a78e34",
        "address": "22 Chemin des Marronniers",
        "position": {
          "x": 250,
          "y": 0,
          "z": 210
        },
        "buildingType": "residence",
        "buildingId": "69bfe08d2f34e6ad23a78e57"
      },
      {
        "id": "69bfe08d2f34e6ad23a78e35",
        "address": "23 Chemin de la Poste",
        "position": {
          "x": 263.3333333333333,
          "y": 0,
          "z": 190
        },
        "buildingType": "residence",
        "buildingId": "69bfe08d2f34e6ad23a78e58"
      },
      {
        "id": "69bfe08d2f34e6ad23a78e36",
        "address": "24 Chemin des Marronniers",
        "position": {
          "x": 263.3333333333333,
          "y": 0,
          "z": 210
        },
        "buildingType": "residence",
        "buildingId": "69bfe08d2f34e6ad23a78e59"
      },
      {
        "id": "69bfe08d2f34e6ad23a78e37",
        "address": "25 Chemin des Marronniers",
        "position": {
          "x": 236.66666666666666,
          "y": 0,
          "z": 240
        },
        "buildingType": "business",
        "buildingId": "69bfe08e2f34e6ad23a78e8d"
      },
      {
        "id": "69bfe08d2f34e6ad23a78e38",
        "address": "26 Impasse de Toulouse",
        "position": {
          "x": 236.66666666666666,
          "y": 0,
          "z": 260
        },
        "buildingType": "residence",
        "buildingId": "69bfe08d2f34e6ad23a78e5a"
      },
      {
        "id": "69bfe08d2f34e6ad23a78e39",
        "address": "27 Chemin des Marronniers",
        "position": {
          "x": 250,
          "y": 0,
          "z": 240
        },
        "buildingType": "residence",
        "buildingId": "69bfe08d2f34e6ad23a78e5b"
      },
      {
        "id": "69bfe08d2f34e6ad23a78e3a",
        "address": "28 Impasse de Toulouse",
        "position": {
          "x": 250,
          "y": 0,
          "z": 260
        },
        "buildingType": "residence",
        "buildingId": "69bfe08d2f34e6ad23a78e5c"
      },
      {
        "id": "69bfe08d2f34e6ad23a78e3b",
        "address": "29 Chemin des Marronniers",
        "position": {
          "x": 263.3333333333333,
          "y": 0,
          "z": 240
        },
        "buildingType": "business",
        "buildingId": "69bfe08e2f34e6ad23a78e8e"
      },
      {
        "id": "69bfe08d2f34e6ad23a78e3c",
        "address": "30 Impasse de Toulouse",
        "position": {
          "x": 263.3333333333333,
          "y": 0,
          "z": 260
        },
        "buildingType": "residence",
        "buildingId": "69bfe08d2f34e6ad23a78e5d"
      },
      {
        "id": "69bfe08d2f34e6ad23a78e3d",
        "address": "31 Impasse de Toulouse",
        "position": {
          "x": 236.66666666666666,
          "y": 0,
          "z": 290
        },
        "buildingType": "residence",
        "buildingId": "69bfe08d2f34e6ad23a78e5e"
      },
      {
        "id": "69bfe08d2f34e6ad23a78e3e",
        "address": "32 Quai Neuf",
        "position": {
          "x": 236.66666666666666,
          "y": 0,
          "z": 310
        },
        "buildingType": "residence",
        "buildingId": "69bfe08d2f34e6ad23a78e5f"
      },
      {
        "id": "69bfe08d2f34e6ad23a78e3f",
        "address": "33 Impasse de Toulouse",
        "position": {
          "x": 250,
          "y": 0,
          "z": 290
        },
        "buildingType": "business",
        "buildingId": "69bfe08e2f34e6ad23a78e8f"
      },
      {
        "id": "69bfe08d2f34e6ad23a78e40",
        "address": "34 Quai Neuf",
        "position": {
          "x": 250,
          "y": 0,
          "z": 310
        },
        "buildingType": "residence",
        "buildingId": "69bfe08d2f34e6ad23a78e60"
      },
      {
        "id": "69bfe08d2f34e6ad23a78e41",
        "address": "35 Impasse de Toulouse",
        "position": {
          "x": 263.3333333333333,
          "y": 0,
          "z": 290
        },
        "buildingType": "residence",
        "buildingId": "69bfe08d2f34e6ad23a78e61"
      },
      {
        "id": "69bfe08d2f34e6ad23a78e42",
        "address": "36 Quai Neuf",
        "position": {
          "x": 263.3333333333333,
          "y": 0,
          "z": 310
        },
        "buildingType": "residence",
        "buildingId": "69bfe08d2f34e6ad23a78e62"
      },
      {
        "id": "69bfe08d2f34e6ad23a78e43",
        "address": "37 Chemin de la Poste",
        "position": {
          "x": 286.6666666666667,
          "y": 0,
          "z": 190
        },
        "buildingType": "business",
        "buildingId": "69bfe08e2f34e6ad23a78e90"
      },
      {
        "id": "69bfe08d2f34e6ad23a78e44",
        "address": "38 Chemin des Marronniers",
        "position": {
          "x": 286.6666666666667,
          "y": 0,
          "z": 210
        },
        "buildingType": "residence",
        "buildingId": "69bfe08d2f34e6ad23a78e63"
      },
      {
        "id": "69bfe08d2f34e6ad23a78e45",
        "address": "39 Chemin de la Poste",
        "position": {
          "x": 300,
          "y": 0,
          "z": 190
        },
        "buildingType": "residence",
        "buildingId": "69bfe08d2f34e6ad23a78e64"
      },
      {
        "id": "69bfe08d2f34e6ad23a78e46",
        "address": "40 Chemin des Marronniers",
        "position": {
          "x": 300,
          "y": 0,
          "z": 210
        },
        "buildingType": "residence",
        "buildingId": "69bfe08d2f34e6ad23a78e65"
      }
    ],
    "infrastructure": []
  }
] as const;

const BUILDINGS = [
  {
    "id": "bld_69bfe08e2f34e6ad23a78e87",
    "settlementId": "69bfe08a2f34e6ad23a78dc4",
    "position": {
      "x": 186.66666666666666,
      "y": 0,
      "z": 190
    },
    "rotation": 3.141592653589793,
    "spec": {
      "buildingRole": "Bakery",
      "floors": 2,
      "width": 12,
      "depth": 10,
      "hasChimney": true,
      "hasBalcony": false
    },
    "style": {
      "name": "modern_glass",
      "baseColor": {
        "r": 0.6,
        "g": 0.6,
        "b": 0.65
      },
      "roofColor": {
        "r": 0.25,
        "g": 0.25,
        "b": 0.3
      },
      "windowColor": {
        "r": 0.5,
        "g": 0.7,
        "b": 0.9
      },
      "doorColor": {
        "r": 0.3,
        "g": 0.3,
        "b": 0.35
      },
      "materialType": "glass",
      "architectureStyle": "modern"
    },
    "businessId": "69bfe08e2f34e6ad23a78e87",
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69bfe08e2f34e6ad23a78e88",
    "settlementId": "69bfe08a2f34e6ad23a78dc4",
    "position": {
      "x": 186.66666666666666,
      "y": 0,
      "z": 210
    },
    "rotation": 0,
    "spec": {
      "buildingRole": "Restaurant",
      "floors": 2,
      "width": 15,
      "depth": 12,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "modern_glass",
      "baseColor": {
        "r": 0.6,
        "g": 0.6,
        "b": 0.65
      },
      "roofColor": {
        "r": 0.25,
        "g": 0.25,
        "b": 0.3
      },
      "windowColor": {
        "r": 0.5,
        "g": 0.7,
        "b": 0.9
      },
      "doorColor": {
        "r": 0.3,
        "g": 0.3,
        "b": 0.35
      },
      "materialType": "glass",
      "architectureStyle": "modern"
    },
    "businessId": "69bfe08e2f34e6ad23a78e88",
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69bfe08e2f34e6ad23a78e89",
    "settlementId": "69bfe08a2f34e6ad23a78dc4",
    "position": {
      "x": 200,
      "y": 0,
      "z": 190
    },
    "rotation": 3.141592653589793,
    "spec": {
      "buildingRole": "Restaurant",
      "floors": 2,
      "width": 15,
      "depth": 12,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "modern_glass",
      "baseColor": {
        "r": 0.6,
        "g": 0.6,
        "b": 0.65
      },
      "roofColor": {
        "r": 0.25,
        "g": 0.25,
        "b": 0.3
      },
      "windowColor": {
        "r": 0.5,
        "g": 0.7,
        "b": 0.9
      },
      "doorColor": {
        "r": 0.3,
        "g": 0.3,
        "b": 0.35
      },
      "materialType": "glass",
      "architectureStyle": "modern"
    },
    "businessId": "69bfe08e2f34e6ad23a78e89",
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69bfe08e2f34e6ad23a78e8a",
    "settlementId": "69bfe08a2f34e6ad23a78dc4",
    "position": {
      "x": 200,
      "y": 0,
      "z": 210
    },
    "rotation": 0,
    "spec": {
      "buildingRole": "Bank",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "modern_glass",
      "baseColor": {
        "r": 0.6,
        "g": 0.6,
        "b": 0.65
      },
      "roofColor": {
        "r": 0.25,
        "g": 0.25,
        "b": 0.3
      },
      "windowColor": {
        "r": 0.5,
        "g": 0.7,
        "b": 0.9
      },
      "doorColor": {
        "r": 0.3,
        "g": 0.3,
        "b": 0.35
      },
      "materialType": "glass",
      "architectureStyle": "modern"
    },
    "businessId": "69bfe08e2f34e6ad23a78e8a",
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69bfe08e2f34e6ad23a78e8b",
    "settlementId": "69bfe08a2f34e6ad23a78dc4",
    "position": {
      "x": 213.33333333333334,
      "y": 0,
      "z": 190
    },
    "rotation": 3.141592653589793,
    "spec": {
      "buildingRole": "BarberShop",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "modern_glass",
      "baseColor": {
        "r": 0.6,
        "g": 0.6,
        "b": 0.65
      },
      "roofColor": {
        "r": 0.25,
        "g": 0.25,
        "b": 0.3
      },
      "windowColor": {
        "r": 0.5,
        "g": 0.7,
        "b": 0.9
      },
      "doorColor": {
        "r": 0.3,
        "g": 0.3,
        "b": 0.35
      },
      "materialType": "glass",
      "architectureStyle": "modern"
    },
    "businessId": "69bfe08e2f34e6ad23a78e8b",
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69bfe08e2f34e6ad23a78e8c",
    "settlementId": "69bfe08a2f34e6ad23a78dc4",
    "position": {
      "x": 213.33333333333334,
      "y": 0,
      "z": 210
    },
    "rotation": 0,
    "spec": {
      "buildingRole": "GroceryStore",
      "floors": 1,
      "width": 20,
      "depth": 15,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "modern_glass",
      "baseColor": {
        "r": 0.6,
        "g": 0.6,
        "b": 0.65
      },
      "roofColor": {
        "r": 0.25,
        "g": 0.25,
        "b": 0.3
      },
      "windowColor": {
        "r": 0.5,
        "g": 0.7,
        "b": 0.9
      },
      "doorColor": {
        "r": 0.3,
        "g": 0.3,
        "b": 0.35
      },
      "materialType": "glass",
      "architectureStyle": "modern"
    },
    "businessId": "69bfe08e2f34e6ad23a78e8c",
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69bfe08e2f34e6ad23a78e8d",
    "settlementId": "69bfe08a2f34e6ad23a78dc4",
    "position": {
      "x": 186.66666666666666,
      "y": 0,
      "z": 240
    },
    "rotation": 3.141592653589793,
    "spec": {
      "buildingRole": "Shop",
      "floors": 2,
      "width": 10,
      "depth": 8,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "modern_glass",
      "baseColor": {
        "r": 0.6,
        "g": 0.6,
        "b": 0.65
      },
      "roofColor": {
        "r": 0.25,
        "g": 0.25,
        "b": 0.3
      },
      "windowColor": {
        "r": 0.5,
        "g": 0.7,
        "b": 0.9
      },
      "doorColor": {
        "r": 0.3,
        "g": 0.3,
        "b": 0.35
      },
      "materialType": "glass",
      "architectureStyle": "modern"
    },
    "businessId": "69bfe08e2f34e6ad23a78e8d",
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69bfe08e2f34e6ad23a78e8e",
    "settlementId": "69bfe08a2f34e6ad23a78dc4",
    "position": {
      "x": 186.66666666666666,
      "y": 0,
      "z": 260
    },
    "rotation": 0,
    "spec": {
      "buildingRole": "Restaurant",
      "floors": 2,
      "width": 15,
      "depth": 12,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "modern_glass",
      "baseColor": {
        "r": 0.6,
        "g": 0.6,
        "b": 0.65
      },
      "roofColor": {
        "r": 0.25,
        "g": 0.25,
        "b": 0.3
      },
      "windowColor": {
        "r": 0.5,
        "g": 0.7,
        "b": 0.9
      },
      "doorColor": {
        "r": 0.3,
        "g": 0.3,
        "b": 0.35
      },
      "materialType": "glass",
      "architectureStyle": "modern"
    },
    "businessId": "69bfe08e2f34e6ad23a78e8e",
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69bfe08e2f34e6ad23a78e8f",
    "settlementId": "69bfe08a2f34e6ad23a78dc4",
    "position": {
      "x": 200,
      "y": 0,
      "z": 240
    },
    "rotation": 3.141592653589793,
    "spec": {
      "buildingRole": "GroceryStore",
      "floors": 1,
      "width": 20,
      "depth": 15,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "modern_glass",
      "baseColor": {
        "r": 0.6,
        "g": 0.6,
        "b": 0.65
      },
      "roofColor": {
        "r": 0.25,
        "g": 0.25,
        "b": 0.3
      },
      "windowColor": {
        "r": 0.5,
        "g": 0.7,
        "b": 0.9
      },
      "doorColor": {
        "r": 0.3,
        "g": 0.3,
        "b": 0.35
      },
      "materialType": "glass",
      "architectureStyle": "modern"
    },
    "businessId": "69bfe08e2f34e6ad23a78e8f",
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69bfe08e2f34e6ad23a78e90",
    "settlementId": "69bfe08a2f34e6ad23a78dc4",
    "position": {
      "x": 200,
      "y": 0,
      "z": 260
    },
    "rotation": 0,
    "spec": {
      "buildingRole": "Bookstore",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "modern_glass",
      "baseColor": {
        "r": 0.6,
        "g": 0.6,
        "b": 0.65
      },
      "roofColor": {
        "r": 0.25,
        "g": 0.25,
        "b": 0.3
      },
      "windowColor": {
        "r": 0.5,
        "g": 0.7,
        "b": 0.9
      },
      "doorColor": {
        "r": 0.3,
        "g": 0.3,
        "b": 0.35
      },
      "materialType": "glass",
      "architectureStyle": "modern"
    },
    "businessId": "69bfe08e2f34e6ad23a78e90",
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69bfe08a2f34e6ad23a78dc4_10",
    "settlementId": "69bfe08a2f34e6ad23a78dc4",
    "position": {
      "x": 213.33333333333334,
      "y": 0,
      "z": 240
    },
    "rotation": 3.141592653589793,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "modern_glass",
      "baseColor": {
        "r": 0.6,
        "g": 0.6,
        "b": 0.65
      },
      "roofColor": {
        "r": 0.25,
        "g": 0.25,
        "b": 0.3
      },
      "windowColor": {
        "r": 0.5,
        "g": 0.7,
        "b": 0.9
      },
      "doorColor": {
        "r": 0.3,
        "g": 0.3,
        "b": 0.35
      },
      "materialType": "glass",
      "architectureStyle": "modern"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69bfe08a2f34e6ad23a78dc4_11",
    "settlementId": "69bfe08a2f34e6ad23a78dc4",
    "position": {
      "x": 213.33333333333334,
      "y": 0,
      "z": 260
    },
    "rotation": 0,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "modern_glass",
      "baseColor": {
        "r": 0.6,
        "g": 0.6,
        "b": 0.65
      },
      "roofColor": {
        "r": 0.25,
        "g": 0.25,
        "b": 0.3
      },
      "windowColor": {
        "r": 0.5,
        "g": 0.7,
        "b": 0.9
      },
      "doorColor": {
        "r": 0.3,
        "g": 0.3,
        "b": 0.35
      },
      "materialType": "glass",
      "architectureStyle": "modern"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69bfe08a2f34e6ad23a78dc4_12",
    "settlementId": "69bfe08a2f34e6ad23a78dc4",
    "position": {
      "x": 186.66666666666666,
      "y": 0,
      "z": 290
    },
    "rotation": 3.141592653589793,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "modern_glass",
      "baseColor": {
        "r": 0.6,
        "g": 0.6,
        "b": 0.65
      },
      "roofColor": {
        "r": 0.25,
        "g": 0.25,
        "b": 0.3
      },
      "windowColor": {
        "r": 0.5,
        "g": 0.7,
        "b": 0.9
      },
      "doorColor": {
        "r": 0.3,
        "g": 0.3,
        "b": 0.35
      },
      "materialType": "glass",
      "architectureStyle": "modern"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69bfe08a2f34e6ad23a78dc4_13",
    "settlementId": "69bfe08a2f34e6ad23a78dc4",
    "position": {
      "x": 186.66666666666666,
      "y": 0,
      "z": 310
    },
    "rotation": 0,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "modern_glass",
      "baseColor": {
        "r": 0.6,
        "g": 0.6,
        "b": 0.65
      },
      "roofColor": {
        "r": 0.25,
        "g": 0.25,
        "b": 0.3
      },
      "windowColor": {
        "r": 0.5,
        "g": 0.7,
        "b": 0.9
      },
      "doorColor": {
        "r": 0.3,
        "g": 0.3,
        "b": 0.35
      },
      "materialType": "glass",
      "architectureStyle": "modern"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69bfe08a2f34e6ad23a78dc4_14",
    "settlementId": "69bfe08a2f34e6ad23a78dc4",
    "position": {
      "x": 200,
      "y": 0,
      "z": 290
    },
    "rotation": 3.141592653589793,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "modern_glass",
      "baseColor": {
        "r": 0.6,
        "g": 0.6,
        "b": 0.65
      },
      "roofColor": {
        "r": 0.25,
        "g": 0.25,
        "b": 0.3
      },
      "windowColor": {
        "r": 0.5,
        "g": 0.7,
        "b": 0.9
      },
      "doorColor": {
        "r": 0.3,
        "g": 0.3,
        "b": 0.35
      },
      "materialType": "glass",
      "architectureStyle": "modern"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69bfe08a2f34e6ad23a78dc4_15",
    "settlementId": "69bfe08a2f34e6ad23a78dc4",
    "position": {
      "x": 200,
      "y": 0,
      "z": 310
    },
    "rotation": 0,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "modern_glass",
      "baseColor": {
        "r": 0.6,
        "g": 0.6,
        "b": 0.65
      },
      "roofColor": {
        "r": 0.25,
        "g": 0.25,
        "b": 0.3
      },
      "windowColor": {
        "r": 0.5,
        "g": 0.7,
        "b": 0.9
      },
      "doorColor": {
        "r": 0.3,
        "g": 0.3,
        "b": 0.35
      },
      "materialType": "glass",
      "architectureStyle": "modern"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69bfe08a2f34e6ad23a78dc4_16",
    "settlementId": "69bfe08a2f34e6ad23a78dc4",
    "position": {
      "x": 213.33333333333334,
      "y": 0,
      "z": 290
    },
    "rotation": 3.141592653589793,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "modern_glass",
      "baseColor": {
        "r": 0.6,
        "g": 0.6,
        "b": 0.65
      },
      "roofColor": {
        "r": 0.25,
        "g": 0.25,
        "b": 0.3
      },
      "windowColor": {
        "r": 0.5,
        "g": 0.7,
        "b": 0.9
      },
      "doorColor": {
        "r": 0.3,
        "g": 0.3,
        "b": 0.35
      },
      "materialType": "glass",
      "architectureStyle": "modern"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69bfe08a2f34e6ad23a78dc4_17",
    "settlementId": "69bfe08a2f34e6ad23a78dc4",
    "position": {
      "x": 213.33333333333334,
      "y": 0,
      "z": 310
    },
    "rotation": 0,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "modern_glass",
      "baseColor": {
        "r": 0.6,
        "g": 0.6,
        "b": 0.65
      },
      "roofColor": {
        "r": 0.25,
        "g": 0.25,
        "b": 0.3
      },
      "windowColor": {
        "r": 0.5,
        "g": 0.7,
        "b": 0.9
      },
      "doorColor": {
        "r": 0.3,
        "g": 0.3,
        "b": 0.35
      },
      "materialType": "glass",
      "architectureStyle": "modern"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69bfe08a2f34e6ad23a78dc4_18",
    "settlementId": "69bfe08a2f34e6ad23a78dc4",
    "position": {
      "x": 236.66666666666666,
      "y": 0,
      "z": 190
    },
    "rotation": 3.141592653589793,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "modern_glass",
      "baseColor": {
        "r": 0.6,
        "g": 0.6,
        "b": 0.65
      },
      "roofColor": {
        "r": 0.25,
        "g": 0.25,
        "b": 0.3
      },
      "windowColor": {
        "r": 0.5,
        "g": 0.7,
        "b": 0.9
      },
      "doorColor": {
        "r": 0.3,
        "g": 0.3,
        "b": 0.35
      },
      "materialType": "glass",
      "architectureStyle": "modern"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69bfe08a2f34e6ad23a78dc4_19",
    "settlementId": "69bfe08a2f34e6ad23a78dc4",
    "position": {
      "x": 236.66666666666666,
      "y": 0,
      "z": 210
    },
    "rotation": 0,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "modern_glass",
      "baseColor": {
        "r": 0.6,
        "g": 0.6,
        "b": 0.65
      },
      "roofColor": {
        "r": 0.25,
        "g": 0.25,
        "b": 0.3
      },
      "windowColor": {
        "r": 0.5,
        "g": 0.7,
        "b": 0.9
      },
      "doorColor": {
        "r": 0.3,
        "g": 0.3,
        "b": 0.35
      },
      "materialType": "glass",
      "architectureStyle": "modern"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69bfe08a2f34e6ad23a78dc4_20",
    "settlementId": "69bfe08a2f34e6ad23a78dc4",
    "position": {
      "x": 250,
      "y": 0,
      "z": 190
    },
    "rotation": 3.141592653589793,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "modern_glass",
      "baseColor": {
        "r": 0.6,
        "g": 0.6,
        "b": 0.65
      },
      "roofColor": {
        "r": 0.25,
        "g": 0.25,
        "b": 0.3
      },
      "windowColor": {
        "r": 0.5,
        "g": 0.7,
        "b": 0.9
      },
      "doorColor": {
        "r": 0.3,
        "g": 0.3,
        "b": 0.35
      },
      "materialType": "glass",
      "architectureStyle": "modern"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69bfe08a2f34e6ad23a78dc4_21",
    "settlementId": "69bfe08a2f34e6ad23a78dc4",
    "position": {
      "x": 250,
      "y": 0,
      "z": 210
    },
    "rotation": 0,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "modern_glass",
      "baseColor": {
        "r": 0.6,
        "g": 0.6,
        "b": 0.65
      },
      "roofColor": {
        "r": 0.25,
        "g": 0.25,
        "b": 0.3
      },
      "windowColor": {
        "r": 0.5,
        "g": 0.7,
        "b": 0.9
      },
      "doorColor": {
        "r": 0.3,
        "g": 0.3,
        "b": 0.35
      },
      "materialType": "glass",
      "architectureStyle": "modern"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69bfe08a2f34e6ad23a78dc4_22",
    "settlementId": "69bfe08a2f34e6ad23a78dc4",
    "position": {
      "x": 263.3333333333333,
      "y": 0,
      "z": 190
    },
    "rotation": 3.141592653589793,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "modern_glass",
      "baseColor": {
        "r": 0.6,
        "g": 0.6,
        "b": 0.65
      },
      "roofColor": {
        "r": 0.25,
        "g": 0.25,
        "b": 0.3
      },
      "windowColor": {
        "r": 0.5,
        "g": 0.7,
        "b": 0.9
      },
      "doorColor": {
        "r": 0.3,
        "g": 0.3,
        "b": 0.35
      },
      "materialType": "glass",
      "architectureStyle": "modern"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69bfe08a2f34e6ad23a78dc4_23",
    "settlementId": "69bfe08a2f34e6ad23a78dc4",
    "position": {
      "x": 263.3333333333333,
      "y": 0,
      "z": 210
    },
    "rotation": 0,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "modern_glass",
      "baseColor": {
        "r": 0.6,
        "g": 0.6,
        "b": 0.65
      },
      "roofColor": {
        "r": 0.25,
        "g": 0.25,
        "b": 0.3
      },
      "windowColor": {
        "r": 0.5,
        "g": 0.7,
        "b": 0.9
      },
      "doorColor": {
        "r": 0.3,
        "g": 0.3,
        "b": 0.35
      },
      "materialType": "glass",
      "architectureStyle": "modern"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69bfe08a2f34e6ad23a78dc4_24",
    "settlementId": "69bfe08a2f34e6ad23a78dc4",
    "position": {
      "x": 236.66666666666666,
      "y": 0,
      "z": 240
    },
    "rotation": 3.141592653589793,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "modern_glass",
      "baseColor": {
        "r": 0.6,
        "g": 0.6,
        "b": 0.65
      },
      "roofColor": {
        "r": 0.25,
        "g": 0.25,
        "b": 0.3
      },
      "windowColor": {
        "r": 0.5,
        "g": 0.7,
        "b": 0.9
      },
      "doorColor": {
        "r": 0.3,
        "g": 0.3,
        "b": 0.35
      },
      "materialType": "glass",
      "architectureStyle": "modern"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69bfe08a2f34e6ad23a78dc4_25",
    "settlementId": "69bfe08a2f34e6ad23a78dc4",
    "position": {
      "x": 236.66666666666666,
      "y": 0,
      "z": 260
    },
    "rotation": 0,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "modern_glass",
      "baseColor": {
        "r": 0.6,
        "g": 0.6,
        "b": 0.65
      },
      "roofColor": {
        "r": 0.25,
        "g": 0.25,
        "b": 0.3
      },
      "windowColor": {
        "r": 0.5,
        "g": 0.7,
        "b": 0.9
      },
      "doorColor": {
        "r": 0.3,
        "g": 0.3,
        "b": 0.35
      },
      "materialType": "glass",
      "architectureStyle": "modern"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69bfe08a2f34e6ad23a78dc4_26",
    "settlementId": "69bfe08a2f34e6ad23a78dc4",
    "position": {
      "x": 250,
      "y": 0,
      "z": 240
    },
    "rotation": 3.141592653589793,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "modern_glass",
      "baseColor": {
        "r": 0.6,
        "g": 0.6,
        "b": 0.65
      },
      "roofColor": {
        "r": 0.25,
        "g": 0.25,
        "b": 0.3
      },
      "windowColor": {
        "r": 0.5,
        "g": 0.7,
        "b": 0.9
      },
      "doorColor": {
        "r": 0.3,
        "g": 0.3,
        "b": 0.35
      },
      "materialType": "glass",
      "architectureStyle": "modern"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69bfe08a2f34e6ad23a78dc4_27",
    "settlementId": "69bfe08a2f34e6ad23a78dc4",
    "position": {
      "x": 250,
      "y": 0,
      "z": 260
    },
    "rotation": 0,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "modern_glass",
      "baseColor": {
        "r": 0.6,
        "g": 0.6,
        "b": 0.65
      },
      "roofColor": {
        "r": 0.25,
        "g": 0.25,
        "b": 0.3
      },
      "windowColor": {
        "r": 0.5,
        "g": 0.7,
        "b": 0.9
      },
      "doorColor": {
        "r": 0.3,
        "g": 0.3,
        "b": 0.35
      },
      "materialType": "glass",
      "architectureStyle": "modern"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69bfe08a2f34e6ad23a78dc4_28",
    "settlementId": "69bfe08a2f34e6ad23a78dc4",
    "position": {
      "x": 263.3333333333333,
      "y": 0,
      "z": 240
    },
    "rotation": 3.141592653589793,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "modern_glass",
      "baseColor": {
        "r": 0.6,
        "g": 0.6,
        "b": 0.65
      },
      "roofColor": {
        "r": 0.25,
        "g": 0.25,
        "b": 0.3
      },
      "windowColor": {
        "r": 0.5,
        "g": 0.7,
        "b": 0.9
      },
      "doorColor": {
        "r": 0.3,
        "g": 0.3,
        "b": 0.35
      },
      "materialType": "glass",
      "architectureStyle": "modern"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  },
  {
    "id": "bld_69bfe08a2f34e6ad23a78dc4_29",
    "settlementId": "69bfe08a2f34e6ad23a78dc4",
    "position": {
      "x": 263.3333333333333,
      "y": 0,
      "z": 260
    },
    "rotation": 0,
    "spec": {
      "buildingRole": "residence_small",
      "floors": 2,
      "width": 10,
      "depth": 10,
      "hasChimney": false,
      "hasBalcony": false
    },
    "style": {
      "name": "modern_glass",
      "baseColor": {
        "r": 0.6,
        "g": 0.6,
        "b": 0.65
      },
      "roofColor": {
        "r": 0.25,
        "g": 0.25,
        "b": 0.3
      },
      "windowColor": {
        "r": 0.5,
        "g": 0.7,
        "b": 0.9
      },
      "doorColor": {
        "r": 0.3,
        "g": 0.3,
        "b": 0.35
      },
      "materialType": "glass",
      "architectureStyle": "modern"
    },
    "businessId": null,
    "modelAssetKey": null,
    "interior": null
  }
] as const;

const ROADS = [
  {
    "fromId": "node_0_0",
    "toId": "node_3_0",
    "waypoints": [
      {
        "x": -6.88696844993143,
        "y": 0,
        "z": 120.05003429355281
      },
      {
        "x": -6.88696844993143,
        "y": 0,
        "z": 170.0500342935528
      },
      {
        "x": -6.88696844993143,
        "y": 0,
        "z": 220.0500342935528
      },
      {
        "x": -6.88696844993143,
        "y": 0,
        "z": 270.0500342935528
      }
    ],
    "width": 10,
    "materialKey": null
  },
  {
    "fromId": "node_0_1",
    "toId": "node_3_1",
    "waypoints": [
      {
        "x": 43.11303155006857,
        "y": 0,
        "z": 120.05003429355281
      },
      {
        "x": 43.11303155006857,
        "y": 0,
        "z": 170.0500342935528
      },
      {
        "x": 43.11303155006857,
        "y": 0,
        "z": 220.0500342935528
      },
      {
        "x": 43.11303155006857,
        "y": 0,
        "z": 270.0500342935528
      }
    ],
    "width": 10,
    "materialKey": null
  },
  {
    "fromId": "node_0_2",
    "toId": "node_3_2",
    "waypoints": [
      {
        "x": 93.11303155006857,
        "y": 0,
        "z": 120.05003429355281
      },
      {
        "x": 93.11303155006857,
        "y": 0,
        "z": 170.0500342935528
      },
      {
        "x": 93.11303155006857,
        "y": 0,
        "z": 220.0500342935528
      },
      {
        "x": 93.11303155006857,
        "y": 0,
        "z": 270.0500342935528
      }
    ],
    "width": 10,
    "materialKey": null
  },
  {
    "fromId": "node_0_3",
    "toId": "node_3_3",
    "waypoints": [
      {
        "x": 143.11303155006857,
        "y": 0,
        "z": 120.05003429355281
      },
      {
        "x": 143.11303155006857,
        "y": 0,
        "z": 170.0500342935528
      },
      {
        "x": 143.11303155006857,
        "y": 0,
        "z": 220.0500342935528
      },
      {
        "x": 143.11303155006857,
        "y": 0,
        "z": 270.0500342935528
      }
    ],
    "width": 10,
    "materialKey": null
  },
  {
    "fromId": "node_0_0",
    "toId": "node_0_3",
    "waypoints": [
      {
        "x": -6.88696844993143,
        "y": 0,
        "z": 120.05003429355281
      },
      {
        "x": 43.11303155006857,
        "y": 0,
        "z": 120.05003429355281
      },
      {
        "x": 93.11303155006857,
        "y": 0,
        "z": 120.05003429355281
      },
      {
        "x": 143.11303155006857,
        "y": 0,
        "z": 120.05003429355281
      }
    ],
    "width": 10,
    "materialKey": null
  },
  {
    "fromId": "node_1_0",
    "toId": "node_1_3",
    "waypoints": [
      {
        "x": -6.88696844993143,
        "y": 0,
        "z": 170.0500342935528
      },
      {
        "x": 43.11303155006857,
        "y": 0,
        "z": 170.0500342935528
      },
      {
        "x": 93.11303155006857,
        "y": 0,
        "z": 170.0500342935528
      },
      {
        "x": 143.11303155006857,
        "y": 0,
        "z": 170.0500342935528
      }
    ],
    "width": 10,
    "materialKey": null
  },
  {
    "fromId": "node_2_0",
    "toId": "node_2_3",
    "waypoints": [
      {
        "x": -6.88696844993143,
        "y": 0,
        "z": 220.0500342935528
      },
      {
        "x": 43.11303155006857,
        "y": 0,
        "z": 220.0500342935528
      },
      {
        "x": 93.11303155006857,
        "y": 0,
        "z": 220.0500342935528
      },
      {
        "x": 143.11303155006857,
        "y": 0,
        "z": 220.0500342935528
      }
    ],
    "width": 10,
    "materialKey": null
  },
  {
    "fromId": "node_3_0",
    "toId": "node_3_3",
    "waypoints": [
      {
        "x": -6.88696844993143,
        "y": 0,
        "z": 270.0500342935528
      },
      {
        "x": 43.11303155006857,
        "y": 0,
        "z": 270.0500342935528
      },
      {
        "x": 93.11303155006857,
        "y": 0,
        "z": 270.0500342935528
      },
      {
        "x": 143.11303155006857,
        "y": 0,
        "z": 270.0500342935528
      }
    ],
    "width": 10,
    "materialKey": null
  }
] as const;

const WATER_FEATURES = [] as const;

const NATURE_OBJECTS = [] as const;

export class WorldGenerator {
  async generate(scene: Scene, shadowGen: ShadowGenerator): Promise<void> {
    this.createTerrain(scene);
    this.createBuildings(scene, shadowGen);
    this.createStreetNetworks(scene);
    this.createRoads(scene);
    this.createWaterFeatures(scene);
    this.createNatureObjects(scene, shadowGen);
  }

  private createTerrain(scene: Scene): void {
    const ground = MeshBuilder.CreateGround(
      'terrain',
      { width: TERRAIN_SIZE, height: TERRAIN_SIZE, subdivisions: 64 },
      scene,
    );
    const mat = new StandardMaterial('terrainMat', scene);
    mat.diffuseColor = new Color3(0.35, 0.55, 0.25);
    mat.specularColor = new Color3(0.1, 0.1, 0.1);
    ground.material = mat;
    ground.receiveShadows = true;
  }

  private createBuildings(scene: Scene, shadowGen: ShadowGenerator): void {
    for (const b of BUILDINGS) {
      const width = b.spec.width;
      const depth = b.spec.depth;
      const height = b.spec.floors * 3;

      const mesh = MeshBuilder.CreateBox(
        `building_${b.id}`,
        { width, depth, height },
        scene,
      );
      mesh.position = new Vector3(b.position.x, height / 2, b.position.z);
      mesh.rotation.y = b.rotation;

      const mat = new StandardMaterial(`buildingMat_${b.id}`, scene);
      const base = b.style?.baseColor;
      if (base) {
        mat.diffuseColor = new Color3(base.r, base.g, base.b);
      } else {
        mat.diffuseColor = new Color3(0.7, 0.65, 0.6);
      }
      mesh.material = mat;
      mesh.receiveShadows = true;
      shadowGen.addShadowCaster(mesh);

      // Roof
      if (b.spec.floors > 0) {
        const roof = MeshBuilder.CreateBox(
          `roof_${b.id}`,
          { width: width + 0.2, depth: depth + 0.2, height: 0.3 },
          scene,
        );
        roof.position = new Vector3(b.position.x, height + 0.15, b.position.z);
        roof.rotation.y = b.rotation;
        const roofMat = new StandardMaterial(`roofMat_${b.id}`, scene);
        const rc = b.style?.roofColor;
        roofMat.diffuseColor = rc
          ? new Color3(rc.r, rc.g, rc.b)
          : new Color3(0.5, 0.3, 0.2);
        roof.material = roofMat;
        shadowGen.addShadowCaster(roof);
      }
    }
  }

  private createStreetNetworks(scene: Scene): void {
    const streetMat = new StandardMaterial('streetMat', scene);
    streetMat.diffuseColor = new Color3(0.3, 0.3, 0.35);
    streetMat.specularColor = new Color3(0.05, 0.05, 0.05);

    for (const settlement of SETTLEMENTS) {
      for (const segment of settlement.streetSegments) {
        if (segment.waypoints.length < 2) continue;

        const points = segment.waypoints.map(
          (wp: any) => new Vector3(wp.x, 0.02, wp.z),
        );

        const path = MeshBuilder.CreateTube(
          `street_${segment.id}`,
          { path: points, radius: segment.width / 2, tessellation: 8, cap: 2 },
          scene,
        );
        path.material = streetMat;
        path.receiveShadows = true;
      }
    }
  }

  private createRoads(scene: Scene): void {
    const roadMat = new StandardMaterial('roadMat', scene);
    roadMat.diffuseColor = new Color3(0.4, 0.35, 0.3);
    roadMat.specularColor = new Color3(0.05, 0.05, 0.05);

    for (let i = 0; i < ROADS.length; i++) {
      const road = ROADS[i];
      if (road.waypoints.length < 2) continue;

      const points = road.waypoints.map(
        (wp: any) => new Vector3(wp.x, 0.01, wp.z),
      );

      const mesh = MeshBuilder.CreateTube(
        `road_${i}`,
        { path: points, radius: road.width / 2, tessellation: 8, cap: 2 },
        scene,
      );
      mesh.material = roadMat;
      mesh.receiveShadows = true;
    }
  }

  private createWaterFeatures(scene: Scene): void {
    for (const water of WATER_FEATURES) {
      const waterMat = new StandardMaterial(`waterMat_${water.id}`, scene);
      if (water.color) {
        waterMat.diffuseColor = new Color3(water.color.r, water.color.g, water.color.b);
      } else {
        waterMat.diffuseColor = new Color3(0.1, 0.4, 0.7);
      }
      waterMat.alpha = 1 - water.transparency;
      waterMat.specularColor = new Color3(0.3, 0.3, 0.4);

      if (water.shorelinePoints.length >= 3) {
        // Create water surface from shoreline polygon
        const shape = water.shorelinePoints.map(
          (p: any) => new Vector3(p.x, water.waterLevel, p.z),
        );
        const mesh = MeshBuilder.CreatePolygon(
          `water_${water.id}`,
          { shape, depth: 0.1 },
          scene,
        );
        mesh.position.y = water.waterLevel;
        mesh.material = waterMat;
      } else {
        // Fallback: create water surface from bounds
        const w = water.bounds.maxX - water.bounds.minX;
        const d = water.bounds.maxZ - water.bounds.minZ;
        const mesh = MeshBuilder.CreateGround(
          `water_${water.id}`,
          { width: w || water.width, height: d || water.width },
          scene,
        );
        mesh.position = new Vector3(
          water.position.x,
          water.waterLevel,
          water.position.z,
        );
        mesh.material = waterMat;
      }
    }
  }

  private createNatureObjects(scene: Scene, shadowGen: ShadowGenerator): void {
    // Group by type for shared materials
    const treeMat = new StandardMaterial('treeMat', scene);
    treeMat.diffuseColor = new Color3(0.2, 0.5, 0.15);
    const trunkMat = new StandardMaterial('trunkMat', scene);
    trunkMat.diffuseColor = new Color3(0.4, 0.25, 0.1);
    const rockMat = new StandardMaterial('rockMat', scene);
    rockMat.diffuseColor = new Color3(0.5, 0.5, 0.5);
    const bushMat = new StandardMaterial('bushMat', scene);
    bushMat.diffuseColor = new Color3(0.15, 0.4, 0.1);

    for (let i = 0; i < NATURE_OBJECTS.length; i++) {
      const obj = NATURE_OBJECTS[i];
      const pos = new Vector3(obj.position.x, obj.position.y, obj.position.z);

      switch (obj.type) {
        case 'tree': {
          const trunk = MeshBuilder.CreateCylinder(
            `trunk_${i}`,
            { diameter: 0.3 * obj.scale.x, height: 2 * obj.scale.y },
            scene,
          );
          trunk.position = pos.clone();
          trunk.position.y += obj.scale.y;
          trunk.material = trunkMat;
          shadowGen.addShadowCaster(trunk);

          const canopy = MeshBuilder.CreateSphere(
            `canopy_${i}`,
            { diameter: 2 * obj.scale.x },
            scene,
          );
          canopy.position = pos.clone();
          canopy.position.y += 2 * obj.scale.y + obj.scale.x * 0.5;
          canopy.material = treeMat;
          shadowGen.addShadowCaster(canopy);
          break;
        }
        case 'rock': {
          const rock = MeshBuilder.CreateSphere(
            `rock_${i}`,
            { diameter: obj.scale.x },
            scene,
          );
          rock.position = pos;
          rock.scaling = new Vector3(obj.scale.x, obj.scale.y * 0.6, obj.scale.z);
          rock.material = rockMat;
          shadowGen.addShadowCaster(rock);
          break;
        }
        case 'bush': {
          const bush = MeshBuilder.CreateSphere(
            `bush_${i}`,
            { diameter: obj.scale.x },
            scene,
          );
          bush.position = pos;
          bush.position.y += obj.scale.y * 0.3;
          bush.material = bushMat;
          shadowGen.addShadowCaster(bush);
          break;
        }
      }
    }
  }
}
