/**
 * Babylon.js Exporter - Updated to use actual 3DGame files
 */

import * as fsSync from 'fs';
import * as path from 'path';
import { createRequire } from 'module';
import type { WorldIR } from '@shared/game-engine/ir-types';
import type { GeneratedFile } from './babylon-project-generator';
import { generateDataFiles } from './babylon-data-generator';
import { generateSceneFiles } from './babylon-scene-generator';
import { generateProjectFiles } from './babylon-project-generator';
import { GameFileCopier } from './game-file-copier';
import { bundleAssetsFromCollection, bundleCoreAssets } from '../asset-bundler';
import { generateWorldIR } from '../ir-generator';
import type { BabylonExportOptions } from './types';

// createRequire needed for ESM projects.
const require = createRequire(import.meta.url);
let archiver: any;

// ============================================================================
// SHARED TYPES COPY FUNCTION
// ============================================================================

async function copySharedTypes(): Promise<GeneratedFile[]> {
  const sharedDir = path.join(path.dirname(new URL(import.meta.url).pathname), '..', '..', '..', '..', 'shared');
  const files: GeneratedFile[] = [];
  
  if (!fsSync.existsSync(sharedDir)) {
    console.warn(`[Export] Shared directory not found: ${sharedDir}`);
    return files;
  }
  
  const entries = fsSync.readdirSync(sharedDir, { withFileTypes: true });
  
  for (const entry of entries) {
    if (entry.isFile() && (entry.name.endsWith('.ts') || entry.name.endsWith('.js'))) {
      const filePath = path.join(sharedDir, entry.name);
      const content = fsSync.readFileSync(filePath, 'utf8');
      
      files.push({
        path: `src/shared/${entry.name}`,
        content
      });
    }
  }
  
  // Also copy subdirectories like game-genres
  for (const entry of entries) {
    if (entry.isDirectory()) {
      const subDirPath = path.join(sharedDir, entry.name);
      const subEntries = fsSync.readdirSync(subDirPath, { withFileTypes: true });
      
      for (const subEntry of subEntries) {
        if (subEntry.isFile() && (subEntry.name.endsWith('.ts') || subEntry.name.endsWith('.js'))) {
          const filePath = path.join(subDirPath, subEntry.name);
          const content = fsSync.readFileSync(filePath, 'utf8');
          
          files.push({
            path: `src/shared/${entry.name}/${subEntry.name}`,
            content
          });
        }
      }
    }
  }
  
  console.log(`[Export] Copied ${files.length} files from shared`);
  return files;
}

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

function generateAssetManifestJson(manifest: any[]): string {
  const categories: Record<string, any[]> = {};
  
  for (const asset of manifest) {
    if (!categories[asset.category]) {
      categories[asset.category] = [];
    }
    categories[asset.category].push(asset);
  }
  
  return JSON.stringify({
    version: "1.0.0",
    description: "Insimul Base Collection — bundled assets",
    totalFiles: manifest.length,
    totalSizeBytes: manifest.reduce((sum, asset) => sum + asset.fileSize, 0),
    categories,
    assets: manifest
  }, null, 2);
}


function get3DGamePath(): string {
  // Get the path to the 3DGame directory
  const currentDir = path.dirname(new URL(import.meta.url).pathname);
  return path.join(currentDir, '..', '..', '..', '..', 'client', 'src', 'components', '3DGame');
}

function generateMainEntry(ir: WorldIR): string {
  return `/**
 * Main Entry Point for Exported Babylon.js Game
 * Generated by Insimul — ${ir.meta.worldName}
 */

import { Engine } from '@babylonjs/core/Engines/engine';
import '@babylonjs/loaders';
import '@babylonjs/core/Helpers/sceneHelpers';

// Import the actual BabylonGame class
import { BabylonGame } from './index';
import { createDataSource } from './DataSource';

// ── Loading screen helpers ───────────────────────────────────────────────────

const TOTAL_STEPS = 12;
const loadingBar  = document.getElementById('loadingBar')  as HTMLDivElement | null;
const loadingStep = document.getElementById('loadingStep') as HTMLDivElement | null;
const loadingError = document.getElementById('loadingError') as HTMLDivElement | null;

function setLoadingStep(step: number, label: string) {
  if (loadingStep) loadingStep.textContent = label;
  if (loadingBar)  loadingBar.style.width = \`\${Math.round((step / TOTAL_STEPS) * 100)}%\`;
}

function showLoadingError(msg: string) {
  if (loadingError) {
    loadingError.style.display = 'block';
    loadingError.textContent = msg;
  }
  if (loadingStep) loadingStep.textContent = 'Failed to load.';
}

// Intercept console.log to detect BabylonGame step messages and update UI
const _origLog = console.log.bind(console);
console.log = (...args: any[]) => {
  _origLog(...args);
  const msg = typeof args[0] === 'string' ? args[0] : '';
  const match = msg.match(/\\[BabylonGame\\] Step (\\d+)\\/(\\d+): (.+)/);
  if (match) {
    setLoadingStep(parseInt(match[1], 10), match[3].replace('...', '…'));
  }
};

// ── Asset path overrides ─────────────────────────────────────────────────────

(window as any).__ASSET_PATHS__ = {
  '/assets/player/Vincent-frontFacing.babylon': '/assets/characters/player_default.glb',
  '/assets/npc/starterAvatars.babylon': '/assets/characters/npc_guard.glb',
  '/assets/footstep_carpet_000.ogg': '/assets/audio/footstep.ogg'
};

// Monkey-patch fetch to redirect asset requests
const originalFetch = window.fetch;
window.fetch = async function(input: RequestInfo | URL, init?: RequestInit) {
  const url = typeof input === 'string' ? input : input.toString();
  if ((window as any).__ASSET_PATHS__[url]) {
    _origLog('[Asset Redirect]', url, '->', (window as any).__ASSET_PATHS__[url]);
    return originalFetch.call(this, (window as any).__ASSET_PATHS__[url], init);
  }
  return originalFetch.call(this, input, init);
};

// ── Engine & game ────────────────────────────────────────────────────────────

const canvas = document.getElementById('renderCanvas') as HTMLCanvasElement;
if (!canvas) throw new Error('Canvas not found');

const engine = new Engine(canvas, true);
const dataSource = createDataSource();

const game = new BabylonGame(canvas, {
  worldId: '${ir.meta.worldId}',
  worldName: '${ir.meta.worldName}',
  worldType: '${ir.meta.worldType || 'fantasy'}',
  dataSource: dataSource
});

// Timeout: if init takes longer than 3 minutes, surface a message
const loadTimeout = setTimeout(() => {
  showLoadingError(
    'Loading is taking longer than expected.\\n' +
    'The game may still be loading assets. Press F12 to open the developer console for details.'
  );
}, 3 * 60 * 1000);

setLoadingStep(0, 'Starting…');

game.init().then(() => {
  clearTimeout(loadTimeout);
  _origLog('[Insimul] ${ir.meta.worldName} loaded successfully.');

  const loadingScreen = document.getElementById('loadingScreen');
  if (loadingScreen) loadingScreen.classList.add('hidden');

  engine.runRenderLoop(() => {
    if (game.scene && game.engine) game.scene.render();
  });
}).catch(error => {
  clearTimeout(loadTimeout);
  console.error('Failed to initialize game:', error);
  showLoadingError(\`Error: \${error?.message || String(error)}\`);
});

window.addEventListener('resize', () => engine.resize());
`;
}

// ============================================================================
// MAIN EXPORT FUNCTION
// ============================================================================

export async function exportBabylonProject(
  worldId: string,
  options: BabylonExportOptions
): Promise<Buffer> {
  console.log('[Export] Generating Babylon.js electron project for world', worldId);
  
  // 1. Generate the World IR
  console.log('[Export] Starting Babylon.js export for world:', worldId);
  const ir = await generateWorldIR(worldId);
  
  // 2. Generate data files
  console.log('[Export] Generating data files...');
  const dataFiles = generateDataFiles(ir);
  
  // 3. Generate scene files
  console.log('[Export] Generating scene files...');
  const sceneFiles = generateSceneFiles(ir);
  
  // 4. Copy actual game files from 3DGame directory
  console.log('[Export] Copying game files from 3DGame...');
  const gameFileCopier = new GameFileCopier(
    get3DGamePath(),
    '/tmp/export'
  );
  const gameFiles = await gameFileCopier.copyAllFiles();
  
  // 5. Copy shared types
  console.log('[Export] Copying shared types...');
  const sharedTypesFiles = await copySharedTypes();
  
  // 6. Generate project configuration files
  console.log('[Export] Generating project files...');
  const projectFiles = generateProjectFiles(ir, options);
  
  // 7. Create the main entry file that uses the real game
  // DataSource.ts and index.ts are provided by game-file-copier from the 3DGame source
  const mainEntryFile: GeneratedFile = {
    path: 'src/main.ts',
    content: generateMainEntry(ir)
  };
  
  // 10. Bundle assets from the world's selected collection
  console.log('[Export] Bundling assets...');
  let assetBundle;
  const selectedCollectionId = (ir.meta as any).selectedAssetCollectionId;
  if (selectedCollectionId) {
    console.log(`[Export] Using asset collection: ${selectedCollectionId}`);
    assetBundle = await bundleAssetsFromCollection(selectedCollectionId);
    
    // If no assets were bundled from the collection, fall back to core assets
    if (assetBundle.assets.length === 0) {
      console.log('[Export] Collection had no assets, falling back to core assets');
      assetBundle = await bundleCoreAssets();
    }
  } else {
    console.log('[Export] No asset collection selected, using core assets');
    assetBundle = await bundleCoreAssets();
  }
  
  // 10. Generate asset manifest
  const manifestJson = generateAssetManifestJson(assetBundle.manifest);
  
  // Combine all files
  const allFiles: GeneratedFile[] = [
    ...dataFiles,
    ...sceneFiles,
    ...gameFiles,
    ...sharedTypesFiles,
    mainEntryFile,
    ...projectFiles,
    { path: 'public/data/asset-manifest.json', content: manifestJson },
  ];
  
  // Create ZIP archive
  console.log('[Export] Creating ZIP archive...');
  if (!archiver) {
    archiver = require('archiver');
  }
  
  return new Promise((resolve, reject) => {
    const archive = archiver('zip');
    const chunks: Buffer[] = [];
    
    archive.on('data', (chunk: Buffer) => {
      chunks.push(chunk);
    });
    
    archive.on('end', () => {
      resolve(Buffer.concat(chunks));
    });
    
    archive.on('error', (err: Error) => {
      reject(err);
    });
    
    // Add all files to archive
    for (const file of allFiles) {
      if (file.isBinary) {
        archive.append(file.content, { name: file.path });
      } else {
        archive.append(file.content, { name: file.path });
      }
    }
    
    // Add assets - include for both web and electron modes
    for (const asset of assetBundle.assets) {
      archive.append(asset.buffer, { name: `public/${asset.exportPath}` });
    }
    
    archive.finalize();
  });
}

// Export the project as a ZIP buffer (alias for compatibility)
export async function exportBabylonProjectAsZip(
  worldId: string,
  options: BabylonExportOptions
): Promise<Buffer> {
  return exportBabylonProject(worldId, options);
}
