/**
 * Babylon.js Code Generator
 *
 * Generates all TypeScript source files for a standalone Babylon.js game:
 * main entry point, player controller, NPC system, world generator,
 * game systems (actions, quests, combat, dialogue, inventory, rules),
 * and UI (HUD, quest tracker, game menu).
 */

import type { WorldIR } from '@shared/game-engine/ir-types';
import type { GeneratedFile } from './babylon-project-generator';

// ─────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────

function bakeVec3(v: { x: number; y: number; z: number } | [number, number, number]): string {
  if (Array.isArray(v)) return `new Vector3(${v[0]}, ${v[1]}, ${v[2]})`;
  return `new Vector3(${v.x}, ${v.y}, ${v.z})`;
}

// ─────────────────────────────────────────────
// main.ts — entry point
// ─────────────────────────────────────────────

function generateMain(ir: WorldIR): string {
  return `/**
 * Main Entry Point
 * Generated by Insimul — ${ir.meta.worldName}
 */

import { Engine } from '@babylonjs/core/Engines/engine';
import { Scene } from '@babylonjs/core/scene';
import { Vector3 } from '@babylonjs/core/Maths/math';
import { ArcRotateCamera } from '@babylonjs/core/Cameras/arcRotateCamera';

// Side-effect imports for loaders
import '@babylonjs/loaders';
import '@babylonjs/core/Helpers/sceneHelpers';

import { buildScene } from './game/scene-builder';
import { createPlayer } from './game/player';
import { WorldGenerator } from './game/world-generator';
import { NPCSpawner } from './game/npc-spawner';
import { ActionSystem } from './game/systems/action-system';
import { QuestSystem } from './game/systems/quest-system';
import { CombatSystem } from './game/systems/combat-system';
import { DialogueSystem } from './game/systems/dialogue-system';
import { InventorySystem } from './game/systems/inventory-system';
import { RuleEnforcer } from './game/systems/rule-enforcer';
import { HUD } from './game/ui/hud';
import { GameMenu } from './game/ui/game-menu';
import { AssetLoader } from './game/asset-loader';

// Data imports
import themeData from './data/theme.json';
import npcsData from './data/npcs.json';
import questsData from './data/quests.json';
import actionsData from './data/actions.json';
import rulesData from './data/rules.json';
import geographyData from './data/geography.json';
import buildingsData from './data/buildings.json';
import roadsData from './data/roads.json';
import natureData from './data/nature.json';
import playerData from './data/player.json';
import combatData from './data/combat.json';

async function main() {
  const canvas = document.getElementById('renderCanvas') as HTMLCanvasElement;
  const loadingScreen = document.getElementById('loadingScreen');

  // Create engine
  const engine = new Engine(canvas, true, {
    preserveDrawingBuffer: true,
    stencil: true,
    antialias: true,
  });

  const scene = new Scene(engine);
  scene.collisionsEnabled = true;
  scene.gravity = new Vector3(0, -9.81 / 60, 0);

  // Asset loader — preload all bundled assets
  const assetLoader = new AssetLoader(scene);
  const loadingText = loadingScreen?.querySelector('p');
  await assetLoader.preloadAll((progress) => {
    if (loadingText) {
      loadingText.textContent = \`Loading assets… \${progress.percent}% (\${progress.currentFile})\`;
    }
  });

  // Camera (3rd person arc rotate, will be attached to player)
  const camera = new ArcRotateCamera(
    'camera',
    -Math.PI / 2,
    Math.PI / 3,
    12,
    Vector3.Zero(),
    scene,
  );
  camera.lowerRadiusLimit = 3;
  camera.upperRadiusLimit = 25;
  camera.lowerBetaLimit = 0.3;
  camera.upperBetaLimit = Math.PI / 2.2;
  camera.attachControl(canvas, true);

  // Initialise systems
  const actionSystem = new ActionSystem(actionsData);
  const questSystem = new QuestSystem(questsData);
  const combatSystem = new CombatSystem(combatData);
  const dialogueSystem = new DialogueSystem(npcsData);
  const inventorySystem = new InventorySystem();
  const ruleEnforcer = new RuleEnforcer(rulesData);

  // World generator
  const worldGenerator = new WorldGenerator(
    geographyData,
    buildingsData,
    roadsData,
    natureData,
  );

  // NPC spawner
  const npcSpawner = new NPCSpawner(npcsData, dialogueSystem);

  // Build scene
  const sceneConfig = {
    terrainSize: geographyData.terrainSize || ${ir.geography.terrainSize},
    ambientColor: themeData.ambientLighting?.color || [${ir.theme.ambientLighting.color.join(', ')}],
    ambientIntensity: themeData.ambientLighting?.intensity || ${ir.theme.ambientLighting.intensity},
    sunDirection: themeData.directionalLight?.direction || [${ir.theme.directionalLight.direction.join(', ')}],
    sunIntensity: themeData.directionalLight?.intensity || ${ir.theme.directionalLight.intensity},
    fog: themeData.fog || null,
    skyColor: themeData.ambientLighting?.color || [0.5, 0.7, 1.0],
  };

  await buildScene(scene, sceneConfig as any, worldGenerator, npcSpawner);

  // Create player (async — loads GLB model)
  const player = await createPlayer(scene, camera, playerData);

  // HUD
  const hud = new HUD(scene, player, questSystem, inventorySystem);

  // Game menu
  const gameMenu = new GameMenu(scene, engine);

  // Hide loading screen
  if (loadingScreen) loadingScreen.classList.add('hidden');

  // Render loop
  engine.runRenderLoop(() => {
    const dt = engine.getDeltaTime() / 1000;
    player.update(dt);
    npcSpawner.update(dt, player.position);
    questSystem.update(dt);
    combatSystem.update(dt);
    ruleEnforcer.update(dt);
    hud.update();
    scene.render();
  });

  // Resize
  window.addEventListener('resize', () => engine.resize());

  console.log('[Insimul] ${ir.meta.worldName} loaded successfully.');
}

main().catch(console.error);
`;
}

// ─────────────────────────────────────────────
// player.ts
// ─────────────────────────────────────────────

function generatePlayer(ir: WorldIR): string {
  return `/**
 * Player Controller
 * 3rd-person character with WASD movement, jump, and interaction.
 * Loads GLB model from bundled assets with procedural fallback.
 */

import { Scene } from '@babylonjs/core/scene';
import { Vector3 } from '@babylonjs/core/Maths/math';
import { MeshBuilder } from '@babylonjs/core/Meshes/meshBuilder';
import { StandardMaterial } from '@babylonjs/core/Materials/standardMaterial';
import { Color3 } from '@babylonjs/core/Maths/math.color';
import { ArcRotateCamera } from '@babylonjs/core/Cameras/arcRotateCamera';
import { SceneLoader } from '@babylonjs/core/Loading/sceneLoader';
import { AbstractMesh } from '@babylonjs/core/Meshes/abstractMesh';
import type { Mesh } from '@babylonjs/core/Meshes/mesh';

export interface PlayerConfig {
  speed: number;
  jumpForce: number;
  health: number;
  maxHealth: number;
  energy: number;
  maxEnergy: number;
}

export class Player {
  mesh: Mesh | AbstractMesh;
  scene: Scene;
  camera: ArcRotateCamera;
  config: PlayerConfig;

  // State
  health: number;
  maxHealth: number;
  energy: number;
  maxEnergy: number;
  isGrounded = true;
  velocity = Vector3.Zero();

  // Input
  private keys: Record<string, boolean> = {};

  get position(): Vector3 {
    return this.mesh.position;
  }

  constructor(scene: Scene, camera: ArcRotateCamera, mesh: Mesh | AbstractMesh, config: PlayerConfig) {
    this.scene = scene;
    this.camera = camera;
    this.mesh = mesh;
    this.config = config;
    this.health = config.health;
    this.maxHealth = config.maxHealth;
    this.energy = config.energy;
    this.maxEnergy = config.maxEnergy;

    // Input listeners
    window.addEventListener('keydown', (e) => { this.keys[e.key.toLowerCase()] = true; });
    window.addEventListener('keyup', (e) => { this.keys[e.key.toLowerCase()] = false; });
  }

  update(dt: number): void {
    const speed = this.config.speed * dt;
    const forward = this.camera.getForwardRay().direction;
    forward.y = 0;
    forward.normalize();
    const right = Vector3.Cross(forward, Vector3.Up()).normalize();

    const move = Vector3.Zero();
    if (this.keys['w'] || this.keys['arrowup']) move.addInPlace(forward.scale(speed));
    if (this.keys['s'] || this.keys['arrowdown']) move.addInPlace(forward.scale(-speed));
    if (this.keys['a'] || this.keys['arrowleft']) move.addInPlace(right.scale(-speed));
    if (this.keys['d'] || this.keys['arrowright']) move.addInPlace(right.scale(speed));

    // Jump
    if ((this.keys[' '] || this.keys['space']) && this.isGrounded) {
      this.velocity.y = this.config.jumpForce;
      this.isGrounded = false;
    }

    // Gravity
    this.velocity.y -= 9.81 * dt;

    // Apply movement
    this.mesh.position.addInPlace(move);
    this.mesh.position.addInPlace(this.velocity.scale(dt));

    // Ground collision (simple)
    if (this.mesh.position.y <= 1) {
      this.mesh.position.y = 1;
      this.velocity.y = 0;
      this.isGrounded = true;
    }

    // Face movement direction
    if (move.length() > 0.001) {
      const angle = Math.atan2(move.x, move.z);
      this.mesh.rotation.y = angle;
    }

    // Camera follow
    this.camera.target = this.mesh.position.clone();

    // Energy regen
    this.energy = Math.min(this.maxEnergy, this.energy + 2 * dt);
  }

  takeDamage(amount: number): void {
    this.health = Math.max(0, this.health - amount);
  }

  heal(amount: number): void {
    this.health = Math.min(this.maxHealth, this.health + amount);
  }
}

export async function createPlayer(scene: Scene, camera: ArcRotateCamera, playerData: any): Promise<Player> {
  let mesh: Mesh | AbstractMesh;

  // Try to load GLB model from bundled assets
  try {
    const result = await SceneLoader.ImportMeshAsync(
      '',
      '/assets/characters/',
      'player_default.glb',
      scene,
    );
    if (result.meshes.length > 0) {
      mesh = result.meshes[0];
      mesh.name = 'player';
      mesh.position = new Vector3(0, 0, 0);
      mesh.scaling = new Vector3(1, 1, 1);
      mesh.checkCollisions = true;
      console.log('[Player] Loaded GLB model');
    } else {
      throw new Error('No meshes in GLB');
    }
  } catch (err) {
    console.warn('[Player] GLB not available, using procedural mesh:', err);
    // Fallback: procedural capsule
    const capsule = MeshBuilder.CreateCapsule('player', { height: 2, radius: 0.4 }, scene);
    capsule.position = new Vector3(0, 1, 0);
    capsule.checkCollisions = true;
    const mat = new StandardMaterial('playerMat', scene);
    mat.diffuseColor = new Color3(0.2, 0.6, 1.0);
    capsule.material = mat;
    mesh = capsule;
  }

  const config: PlayerConfig = {
    speed: playerData?.moveSpeed || 8,
    jumpForce: playerData?.jumpForce || 5,
    health: playerData?.startingHealth || 100,
    maxHealth: playerData?.startingHealth || 100,
    energy: playerData?.startingEnergy || 100,
    maxEnergy: playerData?.startingEnergy || 100,
  };

  return new Player(scene, camera, mesh, config);
}
`;
}

// ─────────────────────────────────────────────
// npc-controller.ts
// ─────────────────────────────────────────────

function generateNPCController(): string {
  return `/**
 * NPC Controller
 * Handles individual NPC behaviour: idle, patrol, interact.
 */

import { Vector3 } from '@babylonjs/core/Maths/math';
import type { Mesh } from '@babylonjs/core/Meshes/mesh';

export type NPCState = 'idle' | 'patrol' | 'interact' | 'combat';

export interface NPCData {
  characterId: string;
  name: string;
  role: string;
  homePosition: { x: number; y: number; z: number };
  patrolRadius: number;
  disposition: number;
  greeting: string | null;
  questIds: string[];
}

export class NPCController {
  mesh: Mesh;
  data: NPCData;
  state: NPCState = 'idle';
  private patrolTarget: Vector3 | null = null;
  private stateTimer = 0;
  private idleDuration = 3 + Math.random() * 4;

  constructor(mesh: Mesh, data: NPCData) {
    this.mesh = mesh;
    this.data = data;
  }

  update(dt: number, playerPos: Vector3): void {
    this.stateTimer += dt;

    switch (this.state) {
      case 'idle':
        if (this.stateTimer > this.idleDuration) {
          this.state = 'patrol';
          this.stateTimer = 0;
          this.pickPatrolTarget();
        }
        break;

      case 'patrol':
        if (this.patrolTarget) {
          const dir = this.patrolTarget.subtract(this.mesh.position);
          dir.y = 0;
          if (dir.length() < 0.5) {
            this.state = 'idle';
            this.stateTimer = 0;
            this.idleDuration = 3 + Math.random() * 4;
          } else {
            dir.normalize();
            this.mesh.position.addInPlace(dir.scale(2 * dt));
            this.mesh.rotation.y = Math.atan2(dir.x, dir.z);
          }
        }
        break;

      case 'interact':
        // Face the player
        const toPlayer = playerPos.subtract(this.mesh.position);
        toPlayer.y = 0;
        if (toPlayer.length() > 0.1) {
          this.mesh.rotation.y = Math.atan2(toPlayer.x, toPlayer.z);
        }
        break;
    }
  }

  private pickPatrolTarget(): void {
    const home = this.data.homePosition;
    const r = this.data.patrolRadius;
    const angle = Math.random() * Math.PI * 2;
    const dist = Math.random() * r;
    this.patrolTarget = new Vector3(
      home.x + Math.cos(angle) * dist,
      home.y,
      home.z + Math.sin(angle) * dist,
    );
  }

  startInteraction(): void {
    this.state = 'interact';
    this.stateTimer = 0;
  }

  endInteraction(): void {
    this.state = 'idle';
    this.stateTimer = 0;
  }
}
`;
}

// ─────────────────────────────────────────────
// npc-spawner.ts
// ─────────────────────────────────────────────

function generateNPCSpawner(): string {
  return `/**
 * NPC Spawner
 * Creates NPC meshes and controllers from data.
 * Loads GLB models from bundled assets with procedural fallback.
 */

import { Scene } from '@babylonjs/core/scene';
import { Vector3 } from '@babylonjs/core/Maths/math';
import { Color3 } from '@babylonjs/core/Maths/math.color';
import { MeshBuilder } from '@babylonjs/core/Meshes/meshBuilder';
import { StandardMaterial } from '@babylonjs/core/Materials/standardMaterial';
import { SceneLoader } from '@babylonjs/core/Loading/sceneLoader';
import type { AbstractMesh } from '@babylonjs/core/Meshes/abstractMesh';
import type { ShadowGenerator } from '@babylonjs/core/Lights/Shadows/shadowGenerator';
import { NPCController, type NPCData } from './npc-controller';
import type { DialogueSystem } from './systems/dialogue-system';

/** Maps NPC roles to GLB model filenames in /assets/characters/ */
const ROLE_MODEL_MAP: Record<string, string> = {
  guard: 'npc_guard.glb',
  merchant: 'npc_merchant.glb',
  questgiver: 'npc_merchant.glb',
  civilian: 'npc_civilian_male.glb',
};

const ROLE_COLORS: Record<string, [number, number, number]> = {
  questgiver: [1, 0.85, 0],
  merchant: [0.2, 0.8, 0.2],
  guard: [0.6, 0.6, 0.7],
  civilian: [0.8, 0.6, 0.4],
};

export class NPCSpawner {
  private npcs: NPCController[] = [];
  private npcDataList: NPCData[];
  private dialogueSystem: DialogueSystem;

  constructor(npcDataList: NPCData[], dialogueSystem: DialogueSystem) {
    this.npcDataList = npcDataList;
    this.dialogueSystem = dialogueSystem;
  }

  async spawn(scene: Scene, shadowGen: ShadowGenerator): Promise<void> {
    for (const data of this.npcDataList) {
      let mesh: AbstractMesh;

      // Try loading a role-specific GLB model
      const modelFile = ROLE_MODEL_MAP[data.role] || 'npc_civilian_male.glb';
      try {
        const result = await SceneLoader.ImportMeshAsync(
          '',
          '/assets/characters/',
          modelFile,
          scene,
        );
        if (result.meshes.length > 0) {
          mesh = result.meshes[0];
          mesh.name = \`npc_\${data.characterId}\`;
          mesh.position = new Vector3(
            data.homePosition.x,
            data.homePosition.y,
            data.homePosition.z,
          );
          mesh.scaling = new Vector3(1, 1, 1);
          mesh.checkCollisions = true;
          shadowGen.addShadowCaster(mesh);
        } else {
          throw new Error('No meshes in GLB');
        }
      } catch {
        // Fallback: procedural capsule
        const capsule = MeshBuilder.CreateCapsule(
          \`npc_\${data.characterId}\`,
          { height: 1.8, radius: 0.35 },
          scene,
        );
        capsule.position = new Vector3(
          data.homePosition.x,
          data.homePosition.y + 0.9,
          data.homePosition.z,
        );
        capsule.checkCollisions = true;

        const mat = new StandardMaterial(\`npcMat_\${data.characterId}\`, scene);
        const color = ROLE_COLORS[data.role] || ROLE_COLORS.civilian;
        mat.diffuseColor = new Color3(...color);
        capsule.material = mat;

        shadowGen.addShadowCaster(capsule);
        mesh = capsule;
      }

      const controller = new NPCController(mesh as any, data);
      this.npcs.push(controller);
    }

    console.log(\`[NPCSpawner] Spawned \${this.npcs.length} NPCs\`);
  }

  update(dt: number, playerPos: Vector3): void {
    for (const npc of this.npcs) {
      npc.update(dt, playerPos);
    }
  }

  /** Find nearest interactable NPC within range */
  findNearest(playerPos: Vector3, maxRange = 3): NPCController | null {
    let closest: NPCController | null = null;
    let closestDist = maxRange;

    for (const npc of this.npcs) {
      const dist = Vector3.Distance(playerPos, npc.mesh.position);
      if (dist < closestDist) {
        closestDist = dist;
        closest = npc;
      }
    }

    return closest;
  }
}
`;
}

// ─────────────────────────────────────────────
// world-generator.ts
// ─────────────────────────────────────────────

function generateWorldGenerator(ir: WorldIR): string {
  return `/**
 * World Generator
 * Procedurally generates terrain, buildings, roads, and nature objects.
 */

import { Scene } from '@babylonjs/core/scene';
import { Vector3, Color3 } from '@babylonjs/core/Maths/math';
import { MeshBuilder } from '@babylonjs/core/Meshes/meshBuilder';
import { StandardMaterial } from '@babylonjs/core/Materials/standardMaterial';
import { Texture } from '@babylonjs/core/Materials/Textures/texture';
import { SceneLoader } from '@babylonjs/core/Loading/sceneLoader';
import type { ShadowGenerator } from '@babylonjs/core/Lights/Shadows/shadowGenerator';

// Map building types/names to KayKit GLTF models
const BUILDING_MODEL_MAP: Record<string, string> = {
  house: 'building_home_A_blue.gltf',
  home: 'building_home_A_blue.gltf',
  residence: 'building_home_A_blue.gltf',
  tavern: 'building_tavern_blue.gltf',
  inn: 'building_tavern_blue.gltf',
  blacksmith: 'building_blacksmith_blue.gltf',
  forge: 'building_blacksmith_blue.gltf',
  smith: 'building_blacksmith_blue.gltf',
  church: 'building_church_blue.gltf',
  temple: 'building_church_blue.gltf',
  chapel: 'building_church_blue.gltf',
  barracks: 'building_barracks_blue.gltf',
  garrison: 'building_barracks_blue.gltf',
  guardhouse: 'building_barracks_blue.gltf',
  castle: 'building_castle_blue.gltf',
  keep: 'building_castle_blue.gltf',
  fortress: 'building_castle_blue.gltf',
  market: 'building_market_blue.gltf',
  shop: 'building_market_blue.gltf',
  store: 'building_market_blue.gltf',
  mill: 'building_windmill_blue.gltf',
  windmill: 'building_windmill_blue.gltf',
  lumbermill: 'building_lumbermill_blue.gltf',
  mine: 'building_mine_blue.gltf',
  well: 'building_well_blue.gltf',
};

export class WorldGenerator {
  private geography: any;
  private buildings: any[];
  private roads: any[];
  private nature: any[];

  constructor(geography: any, buildings: any[], roads: any[], nature: any[]) {
    this.geography = geography;
    this.buildings = buildings;
    this.roads = roads;
    this.nature = nature;
  }

  async generate(scene: Scene, shadowGen: ShadowGenerator): Promise<void> {
    this.generateTerrain(scene);
    await this.generateBuildings(scene, shadowGen);
    this.generateRoads(scene);
    this.generateNature(scene, shadowGen);
  }

  private generateTerrain(scene: Scene): void {
    const size = this.geography.terrainSize || ${ir.geography.terrainSize};
    const ground = MeshBuilder.CreateGroundFromHeightMap(
      'ground',
      '/assets/ground/ground_heightMap.png',
      {
        width: size,
        height: size,
        subdivisions: 128,
        minHeight: 0,
        maxHeight: 5,
      },
      scene,
    );
    ground.receiveShadows = true;
    ground.checkCollisions = true;

    const mat = new StandardMaterial('groundMat', scene);

    // Load bundled ground textures
    try {
      const diffuse = new Texture('/assets/ground/ground.jpg', scene);
      diffuse.uScale = size / 10;
      diffuse.vScale = size / 10;
      mat.diffuseTexture = diffuse;

      const normal = new Texture('/assets/ground/ground-normal.png', scene);
      normal.uScale = size / 10;
      normal.vScale = size / 10;
      mat.bumpTexture = normal;
    } catch {
      // Fallback to flat color if textures not available
      mat.diffuseColor = new Color3(0.35, 0.55, 0.25);
    }

    mat.specularColor = new Color3(0.05, 0.05, 0.05);
    ground.material = mat;
  }

  private resolveBuildingModel(bldg: any): string | null {
    // Try matching by building type, name, or business type
    const typeName = (bldg.buildingType || bldg.type || bldg.name || '').toLowerCase();
    for (const [key, model] of Object.entries(BUILDING_MODEL_MAP)) {
      if (typeName.includes(key)) return model;
    }
    return null;
  }

  private async generateBuildings(scene: Scene, shadowGen: ShadowGenerator): Promise<void> {
    let glbLoaded = 0;
    let proceduralFallback = 0;

    for (const bldg of this.buildings) {
      const pos = bldg.position || { x: 0, y: 0, z: 0 };
      const rotation = bldg.rotation || 0;
      const modelFile = this.resolveBuildingModel(bldg);

      if (modelFile) {
        try {
          const result = await SceneLoader.ImportMeshAsync(
            '',
            '/assets/buildings/',
            modelFile,
            scene,
          );
          if (result.meshes.length > 0) {
            const root = result.meshes[0];
            root.position = new Vector3(pos.x, 0, pos.z);
            root.rotation.y = rotation;
            root.checkCollisions = true;

            for (const mesh of result.meshes) {
              mesh.checkCollisions = true;
              shadowGen.addShadowCaster(mesh);
            }
            glbLoaded++;
            continue;
          }
        } catch {
          // Fall through to procedural
        }
      }

      // Procedural fallback
      const spec = bldg.spec || {};
      const w = spec.width || 6;
      const h = spec.floors ? spec.floors * 3 : spec.height || 5;
      const d = spec.depth || 6;

      const box = MeshBuilder.CreateBox(\`bldg_\${bldg.id}\`, { width: w, height: h, depth: d }, scene);
      box.position = new Vector3(pos.x, h / 2, pos.z);
      box.rotation.y = rotation;
      box.checkCollisions = true;

      const mat = new StandardMaterial(\`bldgMat_\${bldg.id}\`, scene);
      const style = bldg.style || {};
      const wallColor = style.wallColor;
      if (wallColor) {
        mat.diffuseColor = new Color3(wallColor.r || 0.7, wallColor.g || 0.65, wallColor.b || 0.6);
      } else {
        mat.diffuseColor = new Color3(0.7, 0.65, 0.6);
      }
      box.material = mat;

      shadowGen.addShadowCaster(box);

      // Simple pitched roof
      if (spec.floors || spec.roofType) {
        const roof = MeshBuilder.CreateCylinder(\`roof_\${bldg.id}\`, {
          diameterTop: 0,
          diameterBottom: Math.max(w, d) * 1.3,
          height: 2.5,
          tessellation: 4,
        }, scene);
        roof.position = new Vector3(pos.x, h + 1.25, pos.z);
        roof.rotation.y = rotation;

        const roofMat = new StandardMaterial(\`roofMat_\${bldg.id}\`, scene);
        const roofColor = style.roofColor;
        if (roofColor) {
          roofMat.diffuseColor = new Color3(roofColor.r || 0.5, roofColor.g || 0.3, roofColor.b || 0.2);
        } else {
          roofMat.diffuseColor = new Color3(0.5, 0.3, 0.2);
        }
        roof.material = roofMat;
        shadowGen.addShadowCaster(roof);
      }
      proceduralFallback++;
    }

    console.log(\`[World] Generated \${this.buildings.length} buildings (\${glbLoaded} GLB, \${proceduralFallback} procedural)\`);
  }

  private generateRoads(scene: Scene): void {
    const roadMat = new StandardMaterial('roadMat', scene);
    roadMat.diffuseColor = new Color3(0.35, 0.35, 0.35);
    roadMat.specularColor = new Color3(0.05, 0.05, 0.05);

    for (const road of this.roads) {
      if (!road.path || road.path.length < 2) continue;

      // Simple flat boxes along path segments
      for (let i = 0; i < road.path.length - 1; i++) {
        const a = road.path[i];
        const b = road.path[i + 1];
        const dx = b.x - a.x;
        const dz = b.z - a.z;
        const len = Math.sqrt(dx * dx + dz * dz);
        const angle = Math.atan2(dx, dz);
        const width = road.width || 4;

        const seg = MeshBuilder.CreateBox(\`road_\${road.id}_\${i}\`, {
          width: width,
          height: 0.05,
          depth: len,
        }, scene);
        seg.position = new Vector3(
          (a.x + b.x) / 2,
          0.025,
          (a.z + b.z) / 2,
        );
        seg.rotation.y = angle;
        seg.material = roadMat;
      }
    }

    console.log(\`[World] Generated \${this.roads.length} roads\`);
  }

  private generateNature(scene: Scene, shadowGen: ShadowGenerator): void {
    for (const obj of this.nature) {
      const pos = obj.position || { x: 0, y: 0, z: 0 };
      const kind = (obj.objectType || obj.kind || 'tree').toLowerCase();

      if (kind.includes('tree')) {
        // Trunk
        const trunk = MeshBuilder.CreateCylinder(\`trunk_\${obj.id}\`, {
          height: 3,
          diameterTop: 0.3,
          diameterBottom: 0.5,
        }, scene);
        trunk.position = new Vector3(pos.x, 1.5, pos.z);
        const trunkMat = new StandardMaterial(\`trunkMat_\${obj.id}\`, scene);
        trunkMat.diffuseColor = new Color3(0.4, 0.25, 0.1);
        trunk.material = trunkMat;

        // Canopy
        const canopy = MeshBuilder.CreateSphere(\`canopy_\${obj.id}\`, {
          diameter: 3 + Math.random() * 2,
          segments: 8,
        }, scene);
        canopy.position = new Vector3(pos.x, 4, pos.z);
        const canopyMat = new StandardMaterial(\`canopyMat_\${obj.id}\`, scene);
        canopyMat.diffuseColor = new Color3(0.15 + Math.random() * 0.1, 0.5 + Math.random() * 0.2, 0.1);
        canopy.material = canopyMat;

        shadowGen.addShadowCaster(trunk);
        shadowGen.addShadowCaster(canopy);
      } else if (kind.includes('rock') || kind.includes('boulder')) {
        const rock = MeshBuilder.CreateSphere(\`rock_\${obj.id}\`, {
          diameter: 1 + Math.random() * 1.5,
          segments: 6,
        }, scene);
        rock.position = new Vector3(pos.x, 0.5, pos.z);
        rock.scaling = new Vector3(1, 0.6 + Math.random() * 0.4, 1);
        const rockMat = new StandardMaterial(\`rockMat_\${obj.id}\`, scene);
        rockMat.diffuseColor = new Color3(0.5, 0.5, 0.5);
        rock.material = rockMat;
        shadowGen.addShadowCaster(rock);
      } else if (kind.includes('bush') || kind.includes('shrub')) {
        const bush = MeshBuilder.CreateSphere(\`bush_\${obj.id}\`, {
          diameter: 1.2 + Math.random(),
          segments: 6,
        }, scene);
        bush.position = new Vector3(pos.x, 0.5, pos.z);
        const bushMat = new StandardMaterial(\`bushMat_\${obj.id}\`, scene);
        bushMat.diffuseColor = new Color3(0.2, 0.45, 0.15);
        bush.material = bushMat;
        shadowGen.addShadowCaster(bush);
      }
    }

    console.log(\`[World] Generated \${this.nature.length} nature objects\`);
  }
}
`;
}

// ─────────────────────────────────────────────
// Game Systems
// ─────────────────────────────────────────────

function generateActionSystem(): string {
  return `/**
 * Action System
 * Manages available actions, cooldowns, and execution.
 */

export interface ActionData {
  id: string;
  name: string;
  description: string | null;
  actionType: string;
  duration: number;
  difficulty: number;
  energyCost: number;
  cooldown: number;
  range: number;
  isAvailable: boolean;
  isActive: boolean;
  tags: string[];
}

export class ActionSystem {
  private actions: ActionData[];
  private cooldowns: Map<string, number> = new Map();

  constructor(actionsData: any[]) {
    this.actions = actionsData.filter((a: any) => a.isActive !== false);
    console.log(\`[ActionSystem] Loaded \${this.actions.length} actions\`);
  }

  getAvailable(playerEnergy: number): ActionData[] {
    return this.actions.filter(a => {
      if (!a.isAvailable) return false;
      if (a.energyCost > playerEnergy) return false;
      const cd = this.cooldowns.get(a.id) || 0;
      if (cd > 0) return false;
      return true;
    });
  }

  execute(actionId: string): boolean {
    const action = this.actions.find(a => a.id === actionId);
    if (!action) return false;
    this.cooldowns.set(actionId, action.cooldown || 0);
    return true;
  }

  update(dt: number): void {
    for (const [id, cd] of this.cooldowns) {
      if (cd > 0) this.cooldowns.set(id, cd - dt);
      else this.cooldowns.delete(id);
    }
  }
}
`;
}

function generateQuestSystem(): string {
  return `/**
 * Quest System
 * Tracks active, completed, and available quests.
 */

export interface QuestData {
  id: string;
  title: string;
  description: string;
  questType: string;
  difficulty: string;
  objectives: any[];
  experienceReward: number;
  rewards: Record<string, any>;
  assignedBy: string | null;
  status: string;
  tags: string[];
}

export type QuestStatus = 'available' | 'active' | 'completed' | 'failed';

export class QuestSystem {
  private quests: Map<string, QuestData> = new Map();
  private statuses: Map<string, QuestStatus> = new Map();

  constructor(questsData: any[]) {
    for (const q of questsData) {
      this.quests.set(q.id, q);
      this.statuses.set(q.id, 'available');
    }
    console.log(\`[QuestSystem] Loaded \${this.quests.size} quests\`);
  }

  getAvailable(): QuestData[] {
    return [...this.quests.values()].filter(q => this.statuses.get(q.id) === 'available');
  }

  getActive(): QuestData[] {
    return [...this.quests.values()].filter(q => this.statuses.get(q.id) === 'active');
  }

  getCompleted(): QuestData[] {
    return [...this.quests.values()].filter(q => this.statuses.get(q.id) === 'completed');
  }

  accept(questId: string): boolean {
    if (this.statuses.get(questId) !== 'available') return false;
    this.statuses.set(questId, 'active');
    return true;
  }

  complete(questId: string): QuestData | null {
    if (this.statuses.get(questId) !== 'active') return null;
    this.statuses.set(questId, 'completed');
    return this.quests.get(questId) || null;
  }

  getStatus(questId: string): QuestStatus | undefined {
    return this.statuses.get(questId);
  }

  update(_dt: number): void {
    // Objective checking would go here
  }
}
`;
}

function generateCombatSystem(): string {
  return `/**
 * Combat System
 * Handles combat interactions between player and NPCs.
 */

export class CombatSystem {
  private config: any;

  constructor(combatData: any) {
    this.config = combatData;
    console.log('[CombatSystem] Initialised');
  }

  calculateDamage(attackerPower: number, defenderArmor: number): number {
    const base = attackerPower * (this.config?.damageMultiplier || 1);
    const reduction = defenderArmor * (this.config?.armorReduction || 0.5);
    return Math.max(1, Math.round(base - reduction));
  }

  update(_dt: number): void {
    // Combat tick logic
  }
}
`;
}

function generateDialogueSystem(): string {
  return `/**
 * Dialogue System
 * Manages NPC dialogue, greetings, and conversation state.
 */

export interface DialogueEntry {
  npcId: string;
  npcName: string;
  greeting: string;
  questIds: string[];
}

export class DialogueSystem {
  private entries: Map<string, DialogueEntry> = new Map();
  private activeDialogue: DialogueEntry | null = null;

  constructor(npcsData: any[]) {
    for (const npc of npcsData) {
      this.entries.set(npc.characterId, {
        npcId: npc.characterId,
        npcName: npc.name || npc.characterId,
        greeting: npc.greeting || \`Hello, traveler. I am \${npc.name || 'a villager'}.\`,
        questIds: npc.questIds || [],
      });
    }
    console.log(\`[DialogueSystem] Loaded \${this.entries.size} NPC dialogues\`);
  }

  startDialogue(npcId: string): DialogueEntry | null {
    const entry = this.entries.get(npcId);
    if (!entry) return null;
    this.activeDialogue = entry;
    return entry;
  }

  endDialogue(): void {
    this.activeDialogue = null;
  }

  getActive(): DialogueEntry | null {
    return this.activeDialogue;
  }
}
`;
}

function generateInventorySystem(): string {
  return `/**
 * Inventory System
 * Manages player items, equipment, and resources.
 */

export interface InventoryItem {
  id: string;
  name: string;
  description: string;
  quantity: number;
  type: 'weapon' | 'armor' | 'consumable' | 'quest' | 'material' | 'misc';
  value: number;
}

export class InventorySystem {
  private items: Map<string, InventoryItem> = new Map();
  gold = 0;

  constructor() {
    console.log('[InventorySystem] Initialised');
  }

  addItem(item: Omit<InventoryItem, 'quantity'>, quantity = 1): void {
    const existing = this.items.get(item.id);
    if (existing) {
      existing.quantity += quantity;
    } else {
      this.items.set(item.id, { ...item, quantity });
    }
  }

  removeItem(itemId: string, quantity = 1): boolean {
    const item = this.items.get(itemId);
    if (!item || item.quantity < quantity) return false;
    item.quantity -= quantity;
    if (item.quantity <= 0) this.items.delete(itemId);
    return true;
  }

  getAll(): InventoryItem[] {
    return [...this.items.values()];
  }

  has(itemId: string, quantity = 1): boolean {
    const item = this.items.get(itemId);
    return !!item && item.quantity >= quantity;
  }

  addGold(amount: number): void {
    this.gold += amount;
  }
}
`;
}

function generateRuleEnforcer(): string {
  return `/**
 * Rule Enforcer
 * Evaluates world rules and applies effects.
 */

export interface RuleData {
  id: string;
  name: string;
  description: string | null;
  ruleType: string;
  priority: number;
  likelihood: number;
  conditions: any[];
  effects: any[];
  isActive: boolean;
  tags: string[];
}

export class RuleEnforcer {
  private rules: RuleData[];

  constructor(rulesData: any[]) {
    this.rules = rulesData.filter((r: any) => r.isActive !== false);
    this.rules.sort((a, b) => (b.priority || 0) - (a.priority || 0));
    console.log(\`[RuleEnforcer] Loaded \${this.rules.length} active rules\`);
  }

  evaluate(context: Record<string, any>): RuleData[] {
    // Return rules whose conditions match the context
    return this.rules.filter(rule => {
      if (!rule.conditions || rule.conditions.length === 0) return false;
      // Simplified: check if likelihood passes
      return Math.random() < (rule.likelihood || 0.5);
    });
  }

  update(_dt: number): void {
    // Periodic rule evaluation
  }
}
`;
}

// ─────────────────────────────────────────────
// UI Components
// ─────────────────────────────────────────────

function generateHUD(): string {
  return `/**
 * HUD — Heads-Up Display
 * Shows health, energy, quest tracker, and interaction prompts.
 */

import { Scene } from '@babylonjs/core/scene';
import { AdvancedDynamicTexture, TextBlock, StackPanel, Rectangle, Control } from '@babylonjs/gui';
import type { Player } from '../player';
import type { QuestSystem } from '../systems/quest-system';
import type { InventorySystem } from '../systems/inventory-system';

export class HUD {
  private ui: AdvancedDynamicTexture;
  private healthText: TextBlock;
  private energyText: TextBlock;
  private goldText: TextBlock;
  private questText: TextBlock;
  private player: Player;
  private questSystem: QuestSystem;
  private inventorySystem: InventorySystem;

  constructor(scene: Scene, player: Player, questSystem: QuestSystem, inventorySystem: InventorySystem) {
    this.player = player;
    this.questSystem = questSystem;
    this.inventorySystem = inventorySystem;

    this.ui = AdvancedDynamicTexture.CreateFullscreenUI('HUD', true, scene);

    // Top-left panel: health & energy
    const topLeft = new StackPanel('topLeft');
    topLeft.horizontalAlignment = Control.HORIZONTAL_ALIGNMENT_LEFT;
    topLeft.verticalAlignment = Control.VERTICAL_ALIGNMENT_TOP;
    topLeft.paddingTop = '10px';
    topLeft.paddingLeft = '15px';
    topLeft.width = '250px';
    this.ui.addControl(topLeft);

    this.healthText = this.makeLabel('❤ 100 / 100');
    topLeft.addControl(this.healthText);

    this.energyText = this.makeLabel('⚡ 100 / 100');
    topLeft.addControl(this.energyText);

    this.goldText = this.makeLabel('💰 0');
    topLeft.addControl(this.goldText);

    // Top-right: active quest
    const topRight = new StackPanel('topRight');
    topRight.horizontalAlignment = Control.HORIZONTAL_ALIGNMENT_RIGHT;
    topRight.verticalAlignment = Control.VERTICAL_ALIGNMENT_TOP;
    topRight.paddingTop = '10px';
    topRight.paddingRight = '15px';
    topRight.width = '300px';
    this.ui.addControl(topRight);

    this.questText = this.makeLabel('No active quests', '14px');
    this.questText.textHorizontalAlignment = Control.HORIZONTAL_ALIGNMENT_RIGHT;
    topRight.addControl(this.questText);
  }

  private makeLabel(text: string, size = '16px'): TextBlock {
    const tb = new TextBlock();
    tb.text = text;
    tb.color = 'white';
    tb.fontSize = size;
    tb.height = '24px';
    tb.textHorizontalAlignment = Control.HORIZONTAL_ALIGNMENT_LEFT;
    tb.shadowColor = 'black';
    tb.shadowOffsetX = 1;
    tb.shadowOffsetY = 1;
    return tb;
  }

  update(): void {
    this.healthText.text = \`❤ \${Math.round(this.player.health)} / \${this.player.maxHealth}\`;
    this.energyText.text = \`⚡ \${Math.round(this.player.energy)} / \${this.player.maxEnergy}\`;
    this.goldText.text = \`💰 \${this.inventorySystem.gold}\`;

    const active = this.questSystem.getActive();
    if (active.length > 0) {
      this.questText.text = \`📋 \${active[0].title}\`;
    } else {
      this.questText.text = 'No active quests';
    }
  }
}
`;
}

function generateGameMenu(): string {
  return `/**
 * Game Menu
 * Pause menu with resume, options, and quit.
 */

import { Scene } from '@babylonjs/core/scene';
import { Engine } from '@babylonjs/core/Engines/engine';
import { AdvancedDynamicTexture, Button, StackPanel, Rectangle, TextBlock, Control } from '@babylonjs/gui';

export class GameMenu {
  private ui: AdvancedDynamicTexture;
  private panel: Rectangle;
  private isOpen = false;
  private engine: Engine;

  constructor(scene: Scene, engine: Engine) {
    this.engine = engine;
    this.ui = AdvancedDynamicTexture.CreateFullscreenUI('GameMenu', true, scene);

    // Background overlay
    this.panel = new Rectangle('menuBg');
    this.panel.width = '100%';
    this.panel.height = '100%';
    this.panel.background = 'rgba(0, 0, 0, 0.7)';
    this.panel.isVisible = false;
    this.ui.addControl(this.panel);

    const stack = new StackPanel('menuStack');
    stack.width = '280px';
    this.panel.addControl(stack);

    // Title
    const title = new TextBlock('menuTitle', 'PAUSED');
    title.color = 'white';
    title.fontSize = '32px';
    title.height = '60px';
    stack.addControl(title);

    // Resume button
    const resumeBtn = this.makeButton('Resume', () => this.close());
    stack.addControl(resumeBtn);

    // Fullscreen toggle
    const fsBtn = this.makeButton('Toggle Fullscreen', () => {
      if (document.fullscreenElement) {
        document.exitFullscreen();
      } else {
        document.documentElement.requestFullscreen();
      }
    });
    stack.addControl(fsBtn);

    // ESC handler
    window.addEventListener('keydown', (e) => {
      if (e.key === 'Escape') {
        if (this.isOpen) this.close();
        else this.open();
      }
    });
  }

  private makeButton(label: string, onClick: () => void): Button {
    const btn = Button.CreateSimpleButton(\`btn_\${label}\`, label);
    btn.width = '260px';
    btn.height = '45px';
    btn.color = 'white';
    btn.background = 'rgba(255,255,255,0.1)';
    btn.cornerRadius = 8;
    btn.paddingTop = '5px';
    btn.onPointerClickObservable.add(onClick);
    return btn;
  }

  open(): void {
    this.isOpen = true;
    this.panel.isVisible = true;
  }

  close(): void {
    this.isOpen = false;
    this.panel.isVisible = false;
  }
}
`;
}

// ─────────────────────────────────────────────
// asset-loader.ts
// ─────────────────────────────────────────────

function generateAssetLoader(): string {
  return `/**
 * Asset Loader
 * Centralized asset loading with progress tracking and caching.
 * Generated by Insimul
 */

import { Scene } from '@babylonjs/core/scene';
import { SceneLoader } from '@babylonjs/core/Loading/sceneLoader';
import { Texture } from '@babylonjs/core/Materials/Textures/texture';
import { Sound } from '@babylonjs/core/Audio/sound';
import type { ISceneLoaderAsyncResult } from '@babylonjs/core/Loading/sceneLoader';

export interface AssetManifest {
  version: string;
  generatedAt: string;
  totalFiles: number;
  totalSizeBytes: number;
  categories: Record<string, { files: ManifestEntry[] }>;
}

interface ManifestEntry {
  exportPath: string;
  originalName: string;
  sizeBytes: number;
  mimeType: string;
}

export type LoadProgress = {
  loaded: number;
  total: number;
  percent: number;
  currentFile: string;
};

type ProgressCallback = (progress: LoadProgress) => void;

export class AssetLoader {
  private scene: Scene;
  private modelCache = new Map<string, ISceneLoaderAsyncResult>();
  private textureCache = new Map<string, Texture>();
  private soundCache = new Map<string, Sound>();
  private manifest: AssetManifest | null = null;

  constructor(scene: Scene) {
    this.scene = scene;
  }

  async loadManifest(url = '/asset-manifest.json'): Promise<AssetManifest> {
    if (this.manifest) return this.manifest;

    try {
      const resp = await fetch(url);
      this.manifest = await resp.json();
      console.log('[AssetLoader] Manifest loaded:', this.manifest!.totalFiles, 'files');
    } catch {
      console.warn('[AssetLoader] No manifest found, assets will load on demand');
      this.manifest = { version: '0', generatedAt: '', totalFiles: 0, totalSizeBytes: 0, categories: {} };
    }
    return this.manifest!;
  }

  async loadModel(dir: string, file: string): Promise<ISceneLoaderAsyncResult> {
    const key = dir + file;
    const cached = this.modelCache.get(key);
    if (cached) return cached;

    const result = await SceneLoader.ImportMeshAsync('', dir, file, this.scene);
    this.modelCache.set(key, result);
    return result;
  }

  loadTexture(url: string): Texture {
    const cached = this.textureCache.get(url);
    if (cached) return cached;

    const tex = new Texture(url, this.scene);
    this.textureCache.set(url, tex);
    return tex;
  }

  loadSound(name: string, url: string, options: { loop?: boolean; autoplay?: boolean; volume?: number } = {}): Sound {
    const cached = this.soundCache.get(name);
    if (cached) return cached;

    const sound = new Sound(name, url, this.scene, null, {
      loop: options.loop ?? false,
      autoplay: options.autoplay ?? false,
      volume: options.volume ?? 1.0,
    });
    this.soundCache.set(name, sound);
    return sound;
  }

  async preloadAll(onProgress?: ProgressCallback): Promise<void> {
    const manifest = await this.loadManifest();
    const allFiles: { category: string; entry: ManifestEntry }[] = [];

    for (const [cat, data] of Object.entries(manifest.categories)) {
      for (const entry of data.files) {
        allFiles.push({ category: cat, entry });
      }
    }

    const total = allFiles.length;
    let loaded = 0;

    for (const { category, entry } of allFiles) {
      const path = '/assets/' + entry.exportPath;

      try {
        if (entry.mimeType.includes('gltf') || entry.mimeType.includes('glb') || entry.mimeType.includes('octet-stream')) {
          const dir = path.substring(0, path.lastIndexOf('/') + 1);
          const file = path.substring(path.lastIndexOf('/') + 1);
          await this.loadModel(dir, file);
        } else if (entry.mimeType.startsWith('image/')) {
          this.loadTexture(path);
        } else if (entry.mimeType.startsWith('audio/')) {
          this.loadSound(entry.originalName, path);
        }
      } catch (err) {
        console.warn('[AssetLoader] Failed to preload', path, err);
      }

      loaded++;
      onProgress?.({
        loaded,
        total,
        percent: Math.round((loaded / total) * 100),
        currentFile: entry.originalName,
      });
    }

    console.log('[AssetLoader] Preload complete:', loaded, '/', total, 'assets');
  }

  getModel(dir: string, file: string): ISceneLoaderAsyncResult | undefined {
    return this.modelCache.get(dir + file);
  }

  getTexture(url: string): Texture | undefined {
    return this.textureCache.get(url);
  }

  getSound(name: string): Sound | undefined {
    return this.soundCache.get(name);
  }

  dispose(): void {
    for (const result of this.modelCache.values()) {
      for (const mesh of result.meshes) mesh.dispose();
    }
    for (const tex of this.textureCache.values()) tex.dispose();
    for (const snd of this.soundCache.values()) snd.dispose();
    this.modelCache.clear();
    this.textureCache.clear();
    this.soundCache.clear();
  }
}
`;
}

// ─────────────────────────────────────────────
// Public API
// ─────────────────────────────────────────────

export function generateCodeFiles(ir: WorldIR): GeneratedFile[] {
  return [
    { path: 'src/main.ts', content: generateMain(ir) },
    { path: 'src/game/asset-loader.ts', content: generateAssetLoader() },
    { path: 'src/game/player.ts', content: generatePlayer(ir) },
    { path: 'src/game/npc-controller.ts', content: generateNPCController() },
    { path: 'src/game/npc-spawner.ts', content: generateNPCSpawner() },
    { path: 'src/game/world-generator.ts', content: generateWorldGenerator(ir) },
    { path: 'src/game/systems/action-system.ts', content: generateActionSystem() },
    { path: 'src/game/systems/quest-system.ts', content: generateQuestSystem() },
    { path: 'src/game/systems/combat-system.ts', content: generateCombatSystem() },
    { path: 'src/game/systems/dialogue-system.ts', content: generateDialogueSystem() },
    { path: 'src/game/systems/inventory-system.ts', content: generateInventorySystem() },
    { path: 'src/game/systems/rule-enforcer.ts', content: generateRuleEnforcer() },
    { path: 'src/game/ui/hud.ts', content: generateHUD() },
    { path: 'src/game/ui/game-menu.ts', content: generateGameMenu() },
  ];
}
