/**
 * Babylon.js Scene Generator
 *
 * Generates the scene-builder.ts file that constructs the 3D world
 * from the loaded data at runtime.
 */

import type { WorldIR } from '@shared/game-engine/ir-types';
import type { GeneratedFile } from './babylon-project-generator';

export function generateSceneFiles(ir: WorldIR): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  // ── scene-builder.ts ──
  files.push({
    path: 'src/game/scene-builder.ts',
    content: `/**
 * Scene Builder
 * Constructs the full 3D scene from world data.
 * Generated by Insimul — ${ir.meta.worldName}
 */

import { Scene } from '@babylonjs/core/scene';
import { Vector3, Color3, Color4 } from '@babylonjs/core/Maths/math';
import { HemisphericLight } from '@babylonjs/core/Lights/hemisphericLight';
import { DirectionalLight } from '@babylonjs/core/Lights/directionalLight';
import { MeshBuilder } from '@babylonjs/core/Meshes/meshBuilder';
import { StandardMaterial } from '@babylonjs/core/Materials/standardMaterial';
import { ShadowGenerator } from '@babylonjs/core/Lights/Shadows/shadowGenerator';
import type { WorldGenerator } from './world-generator';
import type { NPCSpawner } from './npc-spawner';

export interface SceneConfig {
  terrainSize: number;
  ambientColor: [number, number, number];
  ambientIntensity: number;
  sunDirection: [number, number, number];
  sunIntensity: number;
  fog: { mode: string; density: number; color: [number, number, number] } | null;
  skyColor: [number, number, number];
}

export async function buildScene(
  scene: Scene,
  config: SceneConfig,
  worldGenerator: WorldGenerator,
  npcSpawner: NPCSpawner,
): Promise<void> {
  // Sky / clear color
  scene.clearColor = new Color4(
    config.skyColor[0] ?? 0.5,
    config.skyColor[1] ?? 0.7,
    config.skyColor[2] ?? 1.0,
    1,
  );

  // Ambient light
  const ambient = new HemisphericLight('ambient', new Vector3(0, 1, 0), scene);
  ambient.diffuse = new Color3(...config.ambientColor);
  ambient.intensity = config.ambientIntensity;
  ambient.groundColor = new Color3(0.2, 0.2, 0.25);

  // Directional light (sun)
  const sun = new DirectionalLight(
    'sun',
    new Vector3(config.sunDirection[0], config.sunDirection[1], config.sunDirection[2]),
    scene,
  );
  sun.intensity = config.sunIntensity;
  sun.position = new Vector3(0, 50, 0);

  // Shadow generator
  const shadowGen = new ShadowGenerator(2048, sun);
  shadowGen.useBlurExponentialShadowMap = true;
  shadowGen.blurKernel = 32;

  // Fog
  if (config.fog) {
    scene.fogMode = Scene.FOGMODE_EXP2;
    scene.fogDensity = config.fog.density;
    scene.fogColor = new Color3(...config.fog.color);
  }

  // Generate world geometry (async — loads building GLB models)
  await worldGenerator.generate(scene, shadowGen);

  // Spawn NPCs (async — loads GLB models)
  await npcSpawner.spawn(scene, shadowGen);
}
`,
  });

  return files;
}
