/**
 * Babylon.js Exporter - Copies actual 3DGame files
 * 
 * Instead of generating new code, this copies the existing 3DGame files
 * and creates a wrapper that uses file-based data loading.
 */

import type { WorldIR } from '@shared/game-engine/ir-types';
import type { GeneratedFile } from './babylon-project-generator';
import * as fs from 'fs';
import * as path from 'path';

// List of 3DGame files to export (in dependency order)
const GAME_FILES = [
  // Core types and utilities
  'types/actions.ts',
  'types/index.ts',
  
  // Core systems
  'DataSource.ts',
  'TextureManager.ts',
  'AudioManager.ts',
  'CameraManager.ts',
  'CharacterController.ts',
  'HealthBar.ts',
  
  // World generation
  'WorldScaleManager.ts',
  'ProceduralBuildingGenerator.ts',
  'ProceduralNatureGenerator.ts',
  'ProceduralDungeonGenerator.ts',
  'RoadGenerator.ts',
  
  // Game systems
  'actions/ActionManager.ts',
  'actions/index.ts',
  'ActionManager.ts', // Legacy - might be referenced
  'RuleEnforcer.ts',
  'CombatSystem.ts',
  'RangedCombatSystem.ts',
  'FightingCombatSystem.ts',
  'TurnBasedCombatSystem.ts',
  'CraftingSystem.ts',
  'ResourceSystem.ts',
  'SurvivalNeedsSystem.ts',
  'RunManager.ts',
  
  // Quest and dialogue
  'QuestObjectManager.ts',
  'QuestIndicatorManager.ts',
  'QuestWaypointManager.ts',
  
  // UI Systems
  'BabylonGUIManager.ts',
  'BabylonChatPanel.ts',
  'BabylonDialogueActions.ts',
  'BabylonInventory.ts',
  'BabylonMinimap.ts',
  'BabylonQuestTracker.ts',
  'BabylonRadialMenu.ts',
  'BabylonRulesPanel.ts',
  'CombatUI.ts',
  'GameMenuSystem.ts',
  'GenreUIManager.ts',
  
  // Building and interior
  'BuildingInfoDisplay.ts',
  'BuildingInteriorGenerator.ts',
  'BuildingPlacementSystem.ts',
  
  // NPC systems
  'NPCTalkingIndicator.ts',
  'NPCAmbientConversationManager.ts',
  
  // VR systems (optional - might not be needed for export)
  // 'VRManager.ts',
  // 'VRUIPanel.ts',
  // 'VRInteractionManager.ts',
  // 'VRHUDManager.ts',
  // 'VRCombatAdapter.ts',
  // 'VRChatPanel.ts',
  // 'VRVocabularyLabels.ts',
  // 'VRHandTrackingManager.ts',
  // 'VRAccessibilityManager.ts',
  
  // Debug and utilities
  'DebugLabelUtils.ts',
  'LanguageProgressTracker.ts',
  
  // Main game class
  'BabylonGame.ts',
];

// Directories to create
const DIRECTORIES = [
  'game',
  'game/systems',
  'game/actions',
  'types',
  'data',
  'assets',
  'assets/characters',
  'assets/buildings',
  'assets/ground',
  'assets/quest-objects',
  'assets/audio',
];

export function generateCodeFiles(ir: WorldIR): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  
  // Create the main entry file that sets up file-based loading
  files.push({
    path: 'src/main.ts',
    content: generateMain(ir)
  });
  
  // Create a simplified world loader
  files.push({
    path: 'src/world-loader.ts',
    content: generateWorldLoader()
  });
  
  // Copy all 3DGame files (in a real implementation, these would be read from the filesystem)
  // For now, we'll create placeholder imports that reference the copied files
  files.push({
    path: 'src/game-imports.ts',
    content: generateGameImports()
  });
  
  // Create a Vite config that handles the paths correctly
  files.push({
    path: 'vite.config.ts',
    content: generateViteConfig()
  });
  
  return files;
}

function generateMain(ir: WorldIR): string {
  return `/**
 * Main Entry Point for Exported Babylon.js Game
 * Generated by Insimul — ${ir.meta.worldName}
 */

import { Engine } from '@babylonjs/core/Engines/engine';
import { Scene } from '@babylonjs/core/scene';
import { Vector3 } from '@babylonjs/core/Maths/math';
import { ArcRotateCamera } from '@babylonjs/core/Cameras/arcRotateCamera';

// Side-effect imports for loaders
import '@babylonjs/loaders';
import '@babylonjs/core/Helpers/sceneHelpers';

// Import the actual BabylonGame class
import { BabylonGame } from './game-imports';

// Import file-based data source
import { createDataSource } from './game-imports';

// Canvas setup
const canvas = document.getElementById('renderCanvas') as HTMLCanvasElement;
if (!canvas) throw new Error('Canvas not found');

// Create engine
const engine = new Engine(canvas, true);

// Create data source (file-based for exported games)
const dataSource = createDataSource();

// Create and initialize the game
const game = new BabylonGame(canvas, {
  worldId: '${ir.meta.worldId}',
  worldName: '${ir.meta.worldName}',
  worldType: '${ir.meta.worldType || 'fantasy'}',
  // Override the data loading to use files instead of API
  dataSource: dataSource
});

// Initialize the game
game.init().then(() => {
  console.log('Game initialized successfully');
  
  // Hide loading screen
  const loadingScreen = document.getElementById('loadingScreen');
  if (loadingScreen) {
    loadingScreen.classList.add('hidden');
  }
  
  // Run the render loop
  engine.runRenderLoop(() => {
    if (game.scene) {
      game.scene.render();
    }
  });
}).catch(error => {
  console.error('Failed to initialize game:', error);
  
  // Show error message
  const loadingScreen = document.getElementById('loadingScreen');
  if (loadingScreen) {
    loadingScreen.innerHTML = \`
      <h1>Error Loading Game</h1>
      <p>\${error.message || 'Unknown error'}</p>
    \`;
  }
});

// Handle window resize
window.addEventListener('resize', () => {
  engine.resize();
});

// Handle visibility change to pause/resume
document.addEventListener('visibilitychange', () => {
  if (document.hidden) {
    engine.stopRenderLoop();
  } else {
    engine.runRenderLoop(() => {
      if (game.scene) {
        game.scene.render();
      }
    });
  }
});
`;
}

function generateWorldLoader(): string {
  return `/**
 * World Loader for Exported Games
 * 
 * This module provides a bridge between the file-based data
 * and the BabylonGame class expectations.
 */

import { FileDataSource } from './game-imports';

// Create a singleton data source
export const worldDataSource = new FileDataSource();

// Export functions that match the API interface
export async function loadWorldData(worldId: string) {
  return {
    world: await worldDataSource.loadWorld(worldId),
    characters: await worldDataSource.loadCharacters(worldId),
    npcs: await worldDataSource.loadNPCs(worldId),
    actions: await worldDataSource.loadActions(worldId),
    baseActions: await worldDataSource.loadBaseActions(),
    quests: await worldDataSource.loadQuests(worldId),
    settlements: await worldDataSource.loadSettlements(worldId),
    rules: await worldDataSource.loadRules(worldId),
    baseRules: await worldDataSource.loadBaseRules(),
    countries: await worldDataSource.loadCountries(worldId),
    states: await worldDataSource.loadStates(worldId),
    baseResources: await worldDataSource.loadBaseResources(worldId),
    assets: await worldDataSource.loadAssets(worldId),
    config3D: await worldDataSource.loadConfig3D(worldId),
    truths: await worldDataSource.loadTruths(worldId),
  };
}
`;
}

function generateGameImports(): string {
  return `/**
 * Game Imports - Re-exports from the copied 3DGame files
 * 
 * This file acts as a barrel export for all the game components.
 * In the actual export implementation, these would be the copied files.
 */

// Core game class (this would be copied from client/src/components/3DGame/BabylonGame.ts)
export { BabylonGame } from './BabylonGame';

// Data source
export { createDataSource, FileDataSource, ApiDataSource, type DataSource } from './DataSource';

// All other exports (these would be copied from the 3DGame directory)
export * from './types';
export * from './TextureManager';
export * from './AudioManager';
export * from './CameraManager';
export * from './CharacterController';
export * from './HealthBar';
export * from './WorldScaleManager';
export * from './ProceduralBuildingGenerator';
export * from './ProceduralNatureGenerator';
export * from './ProceduralDungeonGenerator';
export * from './RoadGenerator';
export * from './actions/ActionManager';
export * from './RuleEnforcer';
export * from './CombatSystem';
export * from './RangedCombatSystem';
export * from './FightingCombatSystem';
export * from './TurnBasedCombatSystem';
export * from './CraftingSystem';
export * from './ResourceSystem';
export * from './SurvivalNeedsSystem';
export * from './RunManager';
export * from './QuestObjectManager';
export * from './QuestIndicatorManager';
export * from './QuestWaypointManager';
export * from './BabylonGUIManager';
export * from './BabylonChatPanel';
export * from './BabylonDialogueActions';
export * from './BabylonInventory';
export * from './BabylonMinimap';
export * from './BabylonQuestTracker';
export * from './BabylonRadialMenu';
export * from './BabylonRulesPanel';
export * from './CombatUI';
export * from './GameMenuSystem';
export * from './GenreUIManager';
export * from './BuildingInfoDisplay';
export * from './BuildingInteriorGenerator';
export * from './BuildingPlacementSystem';
export * from './NPCTalkingIndicator';
export * from './NPCAmbientConversationManager';
export * from './DebugLabelUtils';
export * from './LanguageProgressTracker';
`;
}

function generateViteConfig(): string {
  return `import { defineConfig } from 'vite';
import electron from 'vite-plugin-electron';

export default defineConfig({
  plugins: [
    electron({
      entry: 'electron/main.ts',
      vite: {
        build: {
          outDir: 'dist-electron',
        },
      },
    }),
  ],
  resolve: {
    alias: {
      '@': '/src',
    },
  },
  base: './',
  build: {
    target: 'esnext',
    outDir: 'dist',
    ...(process.env.ELECTRON && {
      rollupOptions: {
        input: {
          main: './src/main.ts'
        },
        output: {
          entryFileNames: 'index.js',
          chunkFileNames: 'assets/[name]-[hash].js',
          assetFileNames: 'assets/[name]-[hash].[ext]'
        }
      }
    })
  },
  optimizeDeps: {
    include: [
      '@babylonjs/core',
      '@babylonjs/gui',
      '@babylonjs/loaders',
      '@babylonjs/materials',
    ],
  },
});
`;
}

// Helper function to actually copy files (would be used in the real implementation)
export async function copyGameFiles(sourceDir: string, targetDir: string): Promise<GeneratedFile[]> {
  const files: GeneratedFile[] = [];
  
  for (const file of GAME_FILES) {
    const sourcePath = path.join(sourceDir, file);
    const targetPath = path.join('src', file);
    
    try {
      if (fs.existsSync(sourcePath)) {
        const content = fs.readFileSync(sourcePath, 'utf-8');
        files.push({ path: targetPath, content });
      }
    } catch (error) {
      console.warn(\`Failed to copy file: \${file}\`, error);
    }
  }
  
  return files;
}
