/**
 * Babylon.js Project Generator
 *
 * Generates the project scaffolding for a standalone Babylon.js web app:
 * package.json, index.html, vite.config.ts, tsconfig.json, .gitignore, README.
 */

import type { WorldIR } from '@shared/game-engine/ir-types';

export interface GeneratedFile {
  path: string;
  content: string;
}

function sanitiseName(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, '_');
}

// ─────────────────────────────────────────────
// package.json
// ─────────────────────────────────────────────

function generatePackageJson(ir: WorldIR): string {
  const worldSafe = sanitiseName(ir.meta.worldName).toLowerCase();
  return JSON.stringify({
    name: `insimul-export-${worldSafe}`,
    version: '1.0.0',
    private: true,
    type: 'module',
    scripts: {
      dev: 'vite',
      build: 'tsc && vite build',
      preview: 'vite preview',
    },
    dependencies: {
      '@babylonjs/core': '^7.0.0',
      '@babylonjs/gui': '^7.0.0',
      '@babylonjs/loaders': '^7.0.0',
      '@babylonjs/materials': '^7.0.0',
    },
    devDependencies: {
      typescript: '^5.4.0',
      vite: '^5.4.0',
    },
  }, null, 2);
}

// ─────────────────────────────────────────────
// index.html
// ─────────────────────────────────────────────

function generateIndexHtml(ir: WorldIR): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${ir.meta.worldName} — Insimul Export</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    html, body { width: 100%; height: 100%; overflow: hidden; background: #000; }
    #renderCanvas {
      width: 100%; height: 100%;
      touch-action: none; outline: none;
    }
    #loadingScreen {
      position: fixed; inset: 0; display: flex;
      flex-direction: column; align-items: center; justify-content: center;
      background: #111; color: #fff; font-family: system-ui, sans-serif; z-index: 1000;
    }
    #loadingScreen h1 { font-size: 2rem; margin-bottom: 0.5rem; }
    #loadingScreen p { color: #888; }
    #loadingScreen.hidden { display: none; }
  </style>
</head>
<body>
  <div id="loadingScreen">
    <h1>${ir.meta.worldName}</h1>
    <p>Loading world…</p>
  </div>
  <canvas id="renderCanvas"></canvas>
  <script type="module" src="/src/main.ts"></script>
</body>
</html>`;
}

// ─────────────────────────────────────────────
// vite.config.ts
// ─────────────────────────────────────────────

function generateViteConfig(): string {
  return `import { defineConfig } from 'vite';

export default defineConfig({
  resolve: {
    alias: {
      '@': '/src',
    },
  },
  build: {
    target: 'esnext',
    outDir: 'dist',
  },
  optimizeDeps: {
    include: [
      '@babylonjs/core',
      '@babylonjs/gui',
      '@babylonjs/loaders',
      '@babylonjs/materials',
    ],
  },
});
`;
}

// ─────────────────────────────────────────────
// tsconfig.json
// ─────────────────────────────────────────────

function generateTsConfig(): string {
  return JSON.stringify({
    compilerOptions: {
      target: 'ESNext',
      module: 'ESNext',
      moduleResolution: 'bundler',
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      forceConsistentCasingInFileNames: true,
      resolveJsonModule: true,
      isolatedModules: true,
      noEmit: true,
      jsx: 'preserve',
      baseUrl: '.',
      paths: { '@/*': ['src/*'] },
    },
    include: ['src'],
  }, null, 2);
}

// ─────────────────────────────────────────────
// .gitignore
// ─────────────────────────────────────────────

function generateGitignore(): string {
  return `node_modules/
dist/
.vite/
*.local
`;
}

// ─────────────────────────────────────────────
// README.md
// ─────────────────────────────────────────────

function generateReadme(ir: WorldIR): string {
  const charCount = ir.entities.characters.length;
  const npcCount = ir.entities.npcs.length;
  const questCount = ir.systems.quests.length;
  const settlementCount = ir.geography.settlements.length;

  return `# ${ir.meta.worldName} — Babylon.js Export

> Generated by Insimul v${ir.meta.insimulVersion} on ${ir.meta.exportTimestamp}

## Quick Start

\`\`\`bash
npm install
npm run dev
\`\`\`

Open \`http://localhost:5173\` in your browser.

## Build for Production

\`\`\`bash
npm run build
npm run preview
\`\`\`

## World Stats

| Stat | Value |
|------|-------|
| World Type | ${ir.meta.worldType} |
| Characters | ${charCount} |
| NPCs | ${npcCount} |
| Quests | ${questCount} |
| Settlements | ${settlementCount} |
| Terrain Size | ${ir.geography.terrainSize}×${ir.geography.terrainSize} |

## Controls

| Key | Action |
|-----|--------|
| WASD | Move |
| Space | Jump |
| E | Interact |
| LMB | Attack |
| ESC | Pause / Menu |
| Tab | Quest Log |
| I | Inventory |

## Project Structure

\`\`\`
src/
  main.ts              Entry point — creates engine & scene
  game/
    scene-builder.ts   Builds the 3D scene from world data
    player.ts          Player controller (3rd person, GLB model)
    npc-controller.ts  NPC AI & behaviour
    npc-spawner.ts     Spawns NPCs from data (GLB models)
    world-generator.ts Terrain (heightmap + textures), buildings, roads, nature
    systems/
      action-system.ts   Game actions
      quest-system.ts    Quest tracking
      combat-system.ts   Combat mechanics
      dialogue-system.ts NPC dialogue
      inventory-system.ts Inventory management
      rule-enforcer.ts   World rules
    ui/
      hud.ts           Heads-up display
      game-menu.ts     Pause menu
  data/
    world_ir.json        Full intermediate representation
    asset-manifest.json  Bundled asset manifest
    characters.json      Character data
    npcs.json            NPC data
    quests.json          Quest data
    actions.json         Action definitions
    rules.json           World rules
    geography.json       Geography & settlements
    theme.json           Visual theme
public/
  assets/
    characters/        GLB character models (player + NPC roles)
    buildings/         KayKit medieval building GLTF models
    ground/            Terrain textures (diffuse, normal, heightmap)
    quest-objects/     Quest item GLB models
    audio/             Ambient, footstep, and interaction sounds
\`\`\`
`;
}

// ─────────────────────────────────────────────
// Public API
// ─────────────────────────────────────────────

export function generateProjectFiles(ir: WorldIR): GeneratedFile[] {
  return [
    { path: 'package.json', content: generatePackageJson(ir) },
    { path: 'index.html', content: generateIndexHtml(ir) },
    { path: 'vite.config.ts', content: generateViteConfig() },
    { path: 'tsconfig.json', content: generateTsConfig() },
    { path: '.gitignore', content: generateGitignore() },
    { path: 'README.md', content: generateReadme(ir) },
  ];
}
