/**
 * Godot Project Generator
 *
 * Generates the Godot 4.x project scaffolding: project.godot,
 * export_presets.cfg, .gitignore, default_bus_layout.tres, and README.
 */

import type { WorldIR } from '@shared/game-engine/ir-types';

export interface GeneratedFile {
  path: string;
  content: string;
}

// ─────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────

function sanitiseName(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, '_');
}

// ─────────────────────────────────────────────
// project.godot
// ─────────────────────────────────────────────

function generateProjectGodot(ir: WorldIR): string {
  const worldSafe = sanitiseName(ir.meta.worldName);
  return `; Engine configuration file.
; Generated by Insimul v${ir.meta.insimulVersion}

[application]

config/name="InsimulExport_${worldSafe}"
config/description="${ir.meta.worldName} — ${ir.meta.worldType || 'default'} world"
run/main_scene="res://scenes/main.tscn"
config/features=PackedStringArray("4.3", "Forward Plus")
config/icon="res://icon.svg"

[autoload]

GameManager="*res://scripts/core/game_manager.gd"
DataLoader="*res://scripts/core/data_loader.gd"
ActionSystem="*res://scripts/systems/action_system.gd"
QuestSystem="*res://scripts/systems/quest_system.gd"
CombatSystem="*res://scripts/systems/combat_system.gd"
RuleEnforcer="*res://scripts/systems/rule_enforcer.gd"
InventorySystem="*res://scripts/systems/inventory_system.gd"
DialogueSystem="*res://scripts/systems/dialogue_system.gd"

[display]

window/size/viewport_width=1920
window/size/viewport_height=1080
window/stretch/mode="canvas_items"

[input]

move_forward={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":87,"physical_keycode":0,"key_label":0,"unicode":119,"location":0,"echo":false,"script":null)]
}
move_backward={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":83,"physical_keycode":0,"key_label":0,"unicode":115,"location":0,"echo":false,"script":null)]
}
move_left={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":65,"physical_keycode":0,"key_label":0,"unicode":97,"location":0,"echo":false,"script":null)]
}
move_right={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":68,"physical_keycode":0,"key_label":0,"unicode":100,"location":0,"echo":false,"script":null)]
}
jump={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":32,"physical_keycode":0,"key_label":0,"unicode":32,"location":0,"echo":false,"script":null)]
}
attack={
"deadzone": 0.5,
"events": [Object(InputEventMouseButton,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"button_mask":1,"position":Vector2(0,0),"global_position":Vector2(0,0),"factor":1.0,"button_index":1,"canceled":false,"pressed":true,"double_click":false,"script":null)]
}
interact={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":69,"physical_keycode":0,"key_label":0,"unicode":101,"location":0,"echo":false,"script":null)]
}
menu={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":4194305,"physical_keycode":0,"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)]
}

[layer_names]

3d_physics/layer_1="Default"
3d_physics/layer_2="Terrain"
3d_physics/layer_3="Buildings"
3d_physics/layer_4="NPCs"
3d_physics/layer_5="Interactable"
3d_physics/layer_6="Player"

[navigation]

3d/default_cell_size=0.25
3d/default_agent_radius=0.5
`;
}

// ─────────────────────────────────────────────
// export_presets.cfg
// ─────────────────────────────────────────────

function generateExportPresets(): string {
  return `[preset.0]

name="Windows Desktop"
platform="Windows Desktop"
runnable=true
dedicated_server=false
custom_features=""
export_filter="all_resources"
include_filter=""
exclude_filter=""

[preset.1]

name="Linux"
platform="Linux/X11"
runnable=true
dedicated_server=false
custom_features=""
export_filter="all_resources"
include_filter=""
exclude_filter=""
`;
}

// ─────────────────────────────────────────────
// default_bus_layout.tres
// ─────────────────────────────────────────────

function generateBusLayout(): string {
  return `[gd_resource type="AudioBusLayout" format=3]

[resource]
`;
}

// ─────────────────────────────────────────────
// icon.svg (minimal placeholder)
// ─────────────────────────────────────────────

function generateIcon(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128">
  <rect width="128" height="128" rx="16" fill="#478cbf"/>
  <text x="64" y="78" text-anchor="middle" font-family="sans-serif" font-size="48" fill="white" font-weight="bold">I</text>
</svg>`;
}

// ─────────────────────────────────────────────
// .gitignore
// ─────────────────────────────────────────────

function generateGitignore(): string {
  return `# Godot 4
.godot/
*.import
export.cfg
export_credentials.cfg

# OS
.DS_Store
Thumbs.db

# Build
build/
*.exe
*.x86_64
*.pck
`;
}

// ─────────────────────────────────────────────
// .gitattributes
// ─────────────────────────────────────────────

function generateGitattributes(): string {
  return `# Normalize EOL for all files that Git considers text files.
* text=auto eol=lf
*.gd text
*.tscn text
*.tres text
*.cfg text
*.godot text
`;
}

// ─────────────────────────────────────────────
// README
// ─────────────────────────────────────────────

function generateReadme(ir: WorldIR): string {
  const g = ir.meta.genreConfig;
  return `# ${ir.meta.worldName} — Godot 4 Export

Generated by Insimul v${ir.meta.insimulVersion} on ${ir.meta.exportTimestamp}

## Quick Start

1. **Requirements**: Godot Engine 4.3+ (standard or .NET build)
2. Open the project folder in Godot → "Import" → select \`project.godot\`
3. Press F5 (or the Play button) to run

## World Info

| Property | Value |
|---|---|
| World Name | ${ir.meta.worldName} |
| World Type | ${ir.meta.worldType || 'default'} |
| Genre | ${g.name} (${g.id}) |
| Terrain Size | ${ir.geography.terrainSize}×${ir.geography.terrainSize} |
| Countries | ${ir.geography.countries.length} |
| States | ${ir.geography.states.length} |
| Settlements | ${ir.geography.settlements.length} |
| Characters | ${ir.entities.characters.length} |
| NPCs | ${ir.entities.npcs.length} |
| Buildings | ${ir.entities.buildings.length} |
| Roads | ${ir.entities.roads.length} |
| Rules | ${ir.systems.rules.length} |
| Actions | ${ir.systems.actions.length} |
| Quests | ${ir.systems.quests.length} |

## Project Structure

\`\`\`
res://
├── project.godot
├── scenes/
│   └── main.tscn           Main world scene
├── scripts/
│   ├── core/                GameManager, DataLoader (autoloads)
│   ├── characters/          PlayerController, NPCController
│   ├── systems/             Action, combat, quest, inventory, etc. (autoloads)
│   ├── world/               Procedural generators
│   └── ui/                  HUD, minimap, quest tracker, dialogue
├── data/                    JSON data files (WorldIR, characters, actions, etc.)
├── models/                  Place .glb/.gltf models here
├── textures/                Place textures here
└── materials/               Create materials in the editor
\`\`\`

## Architecture

- **Autoloads**: GameManager, DataLoader, and all game systems are singletons
- **Scene tree**: Main scene has WorldEnvironment, DirectionalLight3D, Player, and generator nodes
- **Data loading**: \`DataLoader.load_world_data()\` reads \`res://data/world_ir.json\`
- **NPC AI**: Uses NavigationServer3D — bake NavMesh after placing terrain
- **Input**: WASD + Space (jump) + E (interact) + LMB (attack) + Esc (menu)

## Notes

- Models/textures must be imported via the Godot editor
- Extend scripts via inheritance or composition
- UI uses Godot's Control nodes (CanvasLayer)
`;
}

// ═════════════════════════════════════════════
// Public API
// ═════════════════════════════════════════════

export function generateProjectFiles(ir: WorldIR): GeneratedFile[] {
  return [
    { path: 'project.godot', content: generateProjectGodot(ir) },
    { path: 'export_presets.cfg', content: generateExportPresets() },
    { path: 'default_bus_layout.tres', content: generateBusLayout() },
    { path: 'icon.svg', content: generateIcon() },
    { path: '.gitignore', content: generateGitignore() },
    { path: '.gitattributes', content: generateGitattributes() },
    { path: 'README.md', content: generateReadme(ir) },
  ];
}
