/**
 * Main Entry Point for Exported Babylon.js Game
 * Generated by Insimul — La Louisiane
 */

import { Engine } from '@babylonjs/core/Engines/engine';
import '@babylonjs/loaders';
import '@babylonjs/core/Helpers/sceneHelpers';

// Import directly to avoid barrel file pulling in all modules eagerly
import { BabylonGame } from './BabylonGame';
import { createDataSource } from './DataSource';

// ── Loading screen helpers ───────────────────────────────────────────────────

const TOTAL_STEPS = 12;
const loadingBar  = document.getElementById('loadingBar')  as HTMLDivElement | null;
const loadingStep = document.getElementById('loadingStep') as HTMLDivElement | null;
const loadingError = document.getElementById('loadingError') as HTMLDivElement | null;

function setLoadingStep(step: number, label: string) {
  if (loadingStep) loadingStep.textContent = label;
  if (loadingBar)  loadingBar.style.width = `${Math.round((step / TOTAL_STEPS) * 100)}%`;
}

function showLoadingError(msg: string) {
  if (loadingError) {
    loadingError.style.display = 'block';
    loadingError.textContent = msg;
  }
  if (loadingStep) loadingStep.textContent = 'Failed to load.';
}

// Intercept console.log to detect BabylonGame step messages and update UI
const _origLog = console.log.bind(console);
console.log = (...args: any[]) => {
  _origLog(...args);
  const msg = typeof args[0] === 'string' ? args[0] : '';
  const match = msg.match(/\[BabylonGame\] Step (\d+)\/(\d+): (.+)/);
  if (match) {
    setLoadingStep(parseInt(match[1], 10), match[3].replace('...', '…'));
  }
};

// ── Engine & game ────────────────────────────────────────────────────────────

const canvas = document.getElementById('renderCanvas') as HTMLCanvasElement;
if (!canvas) throw new Error('Canvas not found');

console.log('[main] Creating engine...');
const engine = new Engine(canvas, true);
console.log('[main] Creating data source...');
const dataSource = createDataSource();
console.log('[main] Data source created:', dataSource.constructor.name);

console.log('[main] Creating BabylonGame...');
const game = new BabylonGame(canvas, {
  worldId: '69bfc926b7a6c8040746a5ae',
  worldName: 'La Louisiane',
  worldType: 'modern-realistic',
  dataSource: dataSource,
});

// Timeout: if init takes longer than 3 minutes, surface a message
const loadTimeout = setTimeout(() => {
  showLoadingError(
    'Loading is taking longer than expected.\n' +
    'The game may still be loading assets. Press F12 to open the developer console for details.'
  );
}, 3 * 60 * 1000);

setLoadingStep(0, 'Starting…');
console.log('[main] Calling game.init()...');

game.init().then(() => {
  clearTimeout(loadTimeout);
  _origLog('[Insimul] La Louisiane loaded successfully.');

  const loadingScreen = document.getElementById('loadingScreen');
  if (loadingScreen) loadingScreen.classList.add('hidden');

  engine.runRenderLoop(() => {
    if (game.scene && game.engine) game.scene.render();
  });
}).catch(error => {
  clearTimeout(loadTimeout);
  console.error('Failed to initialize game:', error);
  showLoadingError(`Error: ${error?.message || String(error)}`);
});

window.addEventListener('resize', () => engine.resize());
