/**
 * Unity Project Generator
 *
 * Generates the Unity project scaffolding: Packages/manifest.json,
 * ProjectSettings, assembly definition, and README.
 */

import type { WorldIR } from '@shared/game-engine/ir-types';

export interface GeneratedFile {
  path: string;
  content: string;
}

// ─────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────

function sanitiseName(name: string): string {
  return name.replace(/[^a-zA-Z0-9]/g, '');
}

// ─────────────────────────────────────────────
// Packages/manifest.json
// ─────────────────────────────────────────────

function generateManifest(): string {
  return JSON.stringify({
    dependencies: {
      'com.unity.inputsystem': '1.8.2',
      'com.unity.cinemachine': '2.10.1',
      'com.unity.ai.navigation': '2.0.4',
      'com.unity.textmeshpro': '3.2.0-pre.10',
      'com.unity.ugui': '2.0.0',
      'com.unity.modules.ai': '1.0.0',
      'com.unity.modules.animation': '1.0.0',
      'com.unity.modules.audio': '1.0.0',
      'com.unity.modules.imageconversion': '1.0.0',
      'com.unity.modules.jsonserialize': '1.0.0',
      'com.unity.modules.physics': '1.0.0',
      'com.unity.modules.ui': '1.0.0',
      'com.unity.modules.unitywebrequest': '1.0.0',
    },
  }, null, 2);
}

// ─────────────────────────────────────────────
// ProjectSettings
// ─────────────────────────────────────────────

function generateProjectSettingsYaml(ir: WorldIR): string {
  const worldSafe = sanitiseName(ir.meta.worldName);
  return `%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!129 &1
PlayerSettings:
  productName: InsimulExport_${worldSafe}
  companyName: Insimul
  defaultScreenWidth: 1920
  defaultScreenHeight: 1080
  runInBackground: 1
  activeInputHandler: 2
  apiCompatibilityLevel: 6
`;
}

function generateInputManagerYaml(): string {
  return `%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!13 &1
InputManager:
  m_ObjectHideFlags: 0
  serializedVersion: 2
  m_Axes: []
`;
}

function generateTagManagerYaml(): string {
  return `%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!78 &1
TagManager:
  serializedVersion: 2
  tags:
  - NPC
  - Building
  - Settlement
  - QuestObject
  - Resource
  layers:
  - Default
  - TransparentFX
  - Ignore Raycast
  - Water
  - UI
  - Terrain
  - Buildings
  - NPCs
  - Interactable
`;
}

function generateQualitySettingsYaml(): string {
  return `%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!47 &1
QualitySettings:
  m_ObjectHideFlags: 0
  serializedVersion: 5
  m_CurrentQuality: 3
`;
}

// ─────────────────────────────────────────────
// Assembly Definition
// ─────────────────────────────────────────────

function generateAsmDef(): string {
  return JSON.stringify({
    name: 'Insimul',
    rootNamespace: 'Insimul',
    references: [
      'Unity.InputSystem',
      'Unity.TextMeshPro',
      'Unity.AI.Navigation',
    ],
    includePlatforms: [],
    excludePlatforms: [],
    allowUnsafeCode: false,
    overrideReferences: false,
    precompiledReferences: [],
    autoReferenced: true,
    defineConstraints: [],
    versionDefines: [],
    noEngineReferences: false,
  }, null, 2);
}

// ─────────────────────────────────────────────
// .gitignore
// ─────────────────────────────────────────────

function generateGitignore(): string {
  return `/[Ll]ibrary/
/[Tt]emp/
/[Oo]bj/
/[Bb]uild/
/[Bb]uilds/
/[Ll]ogs/
/[Uu]ser[Ss]ettings/
*.csproj
*.sln
*.suo
*.tmp
*.user
*.userprefs
*.pidb
*.booproj
*.svd
*.pdb
*.mdb
*.opendb
*.VC.db
*.pidb.meta
*.pdb.meta
*.mdb.meta
sysinfo.txt
*.apk
*.aab
*.unitypackage
*.app
crashlytics-buildid.txt
`;
}

// ─────────────────────────────────────────────
// README
// ─────────────────────────────────────────────

function generateReadme(ir: WorldIR): string {
  const g = ir.meta.genreConfig;
  return `# ${ir.meta.worldName} — Unity Export

Generated by Insimul v${ir.meta.insimulVersion} on ${ir.meta.exportTimestamp}

## Quick Start

1. **Requirements**: Unity 2022.3 LTS or newer (with New Input System package)
2. Open the project folder in Unity Hub → "Add project from disk"
3. Wait for package resolution and script compilation
4. Open \`Assets/Scenes/MainWorld.unity\` (or let InsimulDataLoader auto-create)
5. Press Play to test

## World Info

| Property | Value |
|---|---|
| World Name | ${ir.meta.worldName} |
| World Type | ${ir.meta.worldType || 'default'} |
| Genre | ${g.name} (${g.id}) |
| Terrain Size | ${ir.geography.terrainSize}×${ir.geography.terrainSize} |
| Countries | ${ir.geography.countries.length} |
| States | ${ir.geography.states.length} |
| Settlements | ${ir.geography.settlements.length} |
| Characters | ${ir.entities.characters.length} |
| NPCs | ${ir.entities.npcs.length} |
| Buildings | ${ir.entities.buildings.length} |
| Roads | ${ir.entities.roads.length} |
| Rules | ${ir.systems.rules.length} |
| Actions | ${ir.systems.actions.length} |
| Quests | ${ir.systems.quests.length} |

## Project Structure

\`\`\`
Assets/
├── Scripts/
│   ├── Core/            Game manager, data loader
│   ├── Characters/      Player + NPC controllers
│   ├── Systems/         Action, combat, quest, inventory, crafting, etc.
│   ├── World/           Procedural generators
│   └── UI/              HUD, minimap, inventory, dialogue, quest tracker
├── Resources/
│   └── Data/            JSON data files (WorldIR, characters, actions, etc.)
├── Prefabs/             Create prefabs for Player, NPC, Buildings, etc.
├── Scenes/              Main world scene
└── Materials/           Create materials in the editor
\`\`\`

## Data Loading

The game loads \`Resources/Data/WorldIR.json\` at runtime via
\`InsimulDataLoader.LoadWorldData()\`. Individual JSON files in
\`Resources/Data/\` can also be loaded independently.

## Notes

- Prefabs and Scenes must be created in the Unity Editor
- C# scripts provide all system logic; extend via inheritance or composition
- NPC AI uses Unity NavMesh — bake navigation after placing terrain
- UI uses Unity's Canvas system with TextMeshPro
- Input uses the New Input System (InputActions asset should be created in editor)
`;
}

// ═════════════════════════════════════════════
// Public API
// ═════════════════════════════════════════════

export function generateProjectFiles(ir: WorldIR): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  // Package manifest
  files.push({ path: 'Packages/manifest.json', content: generateManifest() });

  // Project settings
  files.push({ path: 'ProjectSettings/ProjectSettings.asset', content: generateProjectSettingsYaml(ir) });
  files.push({ path: 'ProjectSettings/InputManager.asset', content: generateInputManagerYaml() });
  files.push({ path: 'ProjectSettings/TagManager.asset', content: generateTagManagerYaml() });
  files.push({ path: 'ProjectSettings/QualitySettings.asset', content: generateQualitySettingsYaml() });

  // Assembly definition
  files.push({ path: 'Assets/Scripts/Insimul.asmdef', content: generateAsmDef() });

  // Misc
  files.push({ path: '.gitignore', content: generateGitignore() });
  files.push({ path: 'README.md', content: generateReadme(ir) });

  return files;
}
