init:
	python -m venv talktown
	talktown/bin/pip install -r requirements.txt

run:
	talktown/bin/python test.py

ensemble-export:
	talktown/bin/python ensemble.py

exporter:
	talktown/bin/python exporter.py