cast{
	mitch:"Mitch",
	jeremy:"Jeremy",
	george:"George",
	danika:"Danika",
	chris:"Chris",
	doug:"Doug",
	chloe:"Chloe",
	brax:"Braz",
	grunt:"Grunt",
	taelor:"Taelor",
	al:"Al",
	bob:"Bob",
	carla:"Carla",
	diane:"Diane",
	mr_woof:"Mr. Woof",
	chaplin:"Chaplin",
	fritze:"Fritze",
	sasha:"Sasha",
	madame_meow:"Madame Meow",
	kitty:"Kitty",
	nanny:"Nanny",
	jacob_chauvin:"Jacob Chauvin",
	alphonse_martin:"Alphonse Martin",
	grace_huval:"Grace Huval",
	ralph_aucoin:"Ralph Aucoin",
	cora_de_cuir:"Cora DeCuir",
	francois_le_blanc:"Francois LeBlanc",
	jean_billeaud:"Jean Billeaud",
	christophe_bertrand:"Christophe Bertrand",
	elizabeth_landry:"Elizabeth Landry",
	renee_hebert:"Renee Hebert",
	victoria_guidry:"Victoria Guidry",
	adrianne_billedeaux:"Adrianne Billedeaux",
	jeanne_comeaux:"Jeanne Comeaux",
	dustin_gaspard:"Dustin Gaspard",
	mary_delahoussaye:"Mary Delahoussaye",
	th_o_arnaud:"Théo Arnaud",
	celila_broussard:"Celila Broussard",
	amy_robichaux:"Amy Robichaux",
	charles_devillier:"Charles Devillier",
	elie_charpentier:"Elie Charpentier",
	claude_gaudet:"Claude Gaudet",
	ralph_langlois:"Ralph Langlois",
	jeanne_moutard:"Jeanne Moutard",
	alexandre_nezat:"Alexandre Nezat",
	lucien_noel:"Lucien Noel",
	joseph_roy:"Joseph Roy",
	marie_claire_savoie:"Marie-Claire Savoie",
	claude_robin:"Claude Robin",
	nicolas_bordelon:"Nicolas Bordelon",
	alexis_autin:"Alexis Autin",
	judith_arceneaux:"Judith Arceneaux",
	marie_guidroz:"Marie Guidroz",
	elizabeth_huff:"Elizabeth Huff",
	marie_lavergne:"Marie Lavergne",
	pierre_melancon:"Pierre Melancon",
	catherine_poirier:"Catherine Poirier",
	marie_louise_sorbier:"Marie-Louise Sorbier",
	anne_drouillon:"Anne Drouillon",
	marcel_patin:"Marcel Patin",
	cogsworth:"Cogsworth",
	clayton:"Clayton",
	brim:"Brim",
	emma:"Emma",
	mick:"Mick",
	stan:"Stan",
	belle:"Belle",
	gus:"Gus",
	keith:"Keith",
	claire:"Claire",
	olivia:"Olivia",
	leo:"Leo",
	steven:"Steven",
	rachel:"Rachel",
	luke:"Luke",
	tara:"Tara",
	edward:"Edward",
	simon:"Simon",
	town_constable:"TownConstable",
	border_guard_officer:"BorderGuardOfficer",
	tavern_owner:"TavernOwner",
	tecomarian_traveler:"TecomarianTraveler",
	sellsword:"Sellsword"
}.