schema{
	trait:[artemisian, black_perilla, grisel_highlander, highlander, lowlander, tecomarian, academic, aggressive, agreeable, ambitious, amorous, anxious, anyone, aristocrat, attendee, awkward, beautiful, boastful, boorish, border_guard_officer, bourgeois, braggart, brave, calm, cat, chaotic, charming, child, cinema_buff, clergy, clever, close_minded, cold, confident, cowardly, credulous, criminal, cruel, deceitful, deceptive, devout, diplomatic, disdainful, dishonest, disloyal, distrustful, dog, eagle_eyed, eccentric, educated, elegantly_dressed, empathetic, employee, evil, fearful, female, flirtatious, foreigner, friendly, generous, good, government_official, greedy, grumpy, hardy, has_a_great_smile, has_a_kind_face, haughty, helpful, hero, honest, human, humble, humorous, hypocritical, impudent, impulsive, inconsistent, indifferent, indiscreet, innocent_looking, insecure, intellectual, intelligent, intimidating, jealous, jerk, joker, kind, lawful, local, love, loyal, lucky, male, mean, merchant, middle_class, middle_class, mocking, modest, music_nerd, musician, nice, nimble, noble, non_noble, not_prone_to_seduction, not_sociable, old, open_minded, optimistic, organizer, outgoing, peasant, penetrating, personable, pessimistic, pickpocket, police_officer, poor, poorly_dressed, prideful, proud, provincial, punctual, refined, religious, rich, rival, romantic, security_guard, seductive, selfish, sellsword, serious, servant, shy, sneaky, social, sound_sleeper, sports_fan, stagehand, strong_willed, submissive, supercilious, taciturn, talkative, tavern_owner, thief, town_constable, traveler, trusting, trustworthy, unctuous, uneducated, unfriendly, unsophisticated, vain, violent, virtuous, wealthy, wearing_a_first_responder_uniform, wearing_a_uniform, well_known, witty, xenophobic, young],
	attribute:[age, altruism, charisma, constitution, cultural_knowledge, cunningness, dexterity, diplomacy, happiness, honor, humor, intelligence, nosiness, propriety, self_assuredness, sensitiveness, social_standing, sophistication, status_individual, strength, trustfulness, wisdom],
	status:[amused, attracted_to, bemused, confident, dead, embarrassed, exhausted, expelled, family, fan_of_restaurant, fatigued, fearful, feeling_socially_connected, fired_up, flattered, gobsmacked, grateful, grieving, guilty, hangry, happy, heartbroken, hungry, in_party, inebriated, injured, involved_with, lonely, on_break, outsider, popular, popular, recovering, resting, sad, self_involved, sleeping, successful, tired, unsure, upset, worried],
	mood:[confident, depressed, happy, offended, unsure],
	directed_status:[afraid_of, annoyed_at, attracted_to, betrayed_by, cares_for, crushing_on, envy, esteems, feuding, financially_dependent_on, hates, have_met, idolize, intimidated_by, intimidates, is_boss_of, jealous_of, loves, offended_by, owes_a_favor_to, playful_towards, public_friends, publicly_romantically_committed_to, resentful_of, ridicules, rivals, suspicious_of, threatened_by, trusts, upset_with, worried_about],
	relationship:[ally, comrades, coworker, dating, enemies_with, esteem, family, friends, friends_with, involved_with, lovers, married, met, playmates, rivals, strangers],
	bond:[duty, kinship, magicka_link, vengeance],
	network:[affinity, antagonism, attraction, buddy, closeness, cool, credibility, curiosity, distance, emulation, familial, familiarity, fear, friendship, gratitude, indebted, respect, romance, trust],
	event:[caught_in_a_lie_by, did_a_favor_for, embarrassment, family_reference, flirted_with, formal, harassed, harmed, helped, impressed, informal, made_a_faux_pas_around, mean, met, negative, neutral, nice, positive, respectful, romantic, romantic_advance, romantic_failure, rude, tried_to_bribe],
	event_undirected:[embarrassment, self_involved],
	intent:[antagonize, befriend, beg, candid, deceive, deny, depressed, desire_to_be_mean, desire_to_be_nice, disdain, dismiss, dominate, express_affection, express_anxiety, favor, fight, flirt, get_exercise, help, honor, hospitable, humble, idealize, impress, indifferent, ingratiate, jokearound, kind, manipulate, play_with, putdown, reluctant, rest, romance, romance, rude, shutdown, suckup, trust]
}.