/**
 * Main Entry Point for Exported Babylon.js Game
 * Generated by Insimul — {{WORLD_NAME}}
 */

import '@babylonjs/loaders';
import '@babylonjs/core/Helpers/sceneHelpers';
import { Tools } from '@babylonjs/core';

// Ensure all asset paths resolve relative to dist/index.html.
// Some paths from IR data lack the ./ prefix and resolve against the app CWD.
const originalPreprocess = Tools.PreprocessUrl;
Tools.PreprocessUrl = (url: string): string => {
  let resolved = originalPreprocess(url);
  if (resolved.startsWith('/assets/')) {
    resolved = '.' + resolved;
  }
  if (resolved.startsWith('assets/')) {
    resolved = './' + resolved;
  }
  return resolved;
};

// Import the actual BabylonGame class
import { BabylonGame } from './index';
import { createDataSource } from './DataSource';

// ── Loading screen helpers ───────────────────────────────────────────────────

const TOTAL_STEPS = 12;
const loadingBar  = document.getElementById('loadingBar')  as HTMLDivElement | null;
const loadingStep = document.getElementById('loadingStep') as HTMLDivElement | null;
const loadingError = document.getElementById('loadingError') as HTMLDivElement | null;

function setLoadingStep(step: number, label: string) {
  if (loadingStep) loadingStep.textContent = label;
  if (loadingBar)  loadingBar.style.width = `${Math.round((step / TOTAL_STEPS) * 100)}%`;
}

function showLoadingError(msg: string) {
  if (loadingError) {
    loadingError.style.display = 'block';
    loadingError.textContent = msg;
  }
  if (loadingStep) loadingStep.textContent = 'Failed to load.';
}

// Intercept console.log to detect BabylonGame step messages and update UI
const _origLog = console.log.bind(console);
console.log = (...args: any[]) => {
  _origLog(...args);
  const msg = typeof args[0] === 'string' ? args[0] : '';
  const match = msg.match(/\[BabylonGame\] Step (\d+)\/(\d+): (.+)/);
  if (match) {
    setLoadingStep(parseInt(match[1], 10), match[3].replace('...', '…'));
  }
};

// ── Engine & game ────────────────────────────────────────────────────────────

const canvas = document.getElementById('renderCanvas') as HTMLCanvasElement;
if (!canvas) throw new Error('Canvas not found');

const dataSource = createDataSource();

// API URL for cloud saves — set during export, or empty for offline-only mode
const API_URL = '{{API_URL}}';

const game = new BabylonGame(canvas, {
  worldId: '{{WORLD_ID}}',
  worldName: '{{WORLD_NAME}}',
  worldType: '{{WORLD_TYPE}}',
  dataSource: dataSource,
  apiUrl: API_URL || undefined,
});

// Timeout: if init takes longer than 3 minutes, surface a message
const loadTimeout = setTimeout(() => {
  showLoadingError(
    'Loading is taking longer than expected.\n' +
    'The game may still be loading assets. Press F12 to open the developer console for details.'
  );
}, 3 * 60 * 1000);

setLoadingStep(0, 'Starting…');

game.init().then(() => {
  clearTimeout(loadTimeout);
  _origLog('[Insimul] {{WORLD_NAME}} loaded successfully.');

  const loadingScreen = document.getElementById('loadingScreen');
  if (loadingScreen) loadingScreen.classList.add('hidden');
}).catch(error => {
  clearTimeout(loadTimeout);
  console.error('Failed to initialize game:', error);
  showLoadingError(`Error: ${error?.message || String(error)}`);
});

// BabylonGame handles its own resize listener internally
